### ISSUE TITLE
create docstrings

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/talos#1]
The following calls need to have proper docstrings: 

- Hyperio()
- utils.lr_normalizer()
- data...

**Comment by x94carbone** [comment]
I'm currently writing the doc string for the `Scan` class (which to my understanding is the newer version of `Hyperio`). The class has a ton of methods that seem to just be redefinitions of the parameters, so for now I'm not going to write the doc string for the methods, just the parameters. I think it makes sense to refactor `Scan` before doing so.

`utils.lr_normalizer()` does not seem to exist anymore.

I will do my best to write doc strings for as much as I can though and open a pull request when I'm done.

**Comment by mikkokotila** [comment]
@x94carbone That is wonderful! 

re lr_normalizer() that's now [here](https://github.com/autonomio/talos/blob/master/talos/model/normalizers.py) 

Thanks so much and look forward to the PR! :)

**Comment by x94carbone** [comment]
My pleasure! I'm happy Talos exists. It has been very helpful to me and with your permission, obviously, I think I might want to build more on top of it.

There are some things I'm still confused about (hard to track down where certain attributes end up when they're passed to other functions) but we can figure that out in the PR.

**Comment by x94carbone** [comment]
Hi, I've written doc strings for `Scan` and `Reporting` (less for `Reporting`!).

I am a bit confused as to why `lr_normalizer()` is necessary. For the optimizers listed there (mostly Adam and its derivatives) people usually don't change the default learning rates. Might I ask what we're normalizing them with respect to and why?

Once I do that I'll open a PR and we can work through it some more!

**Comment by mikkokotila** [comment]
Regarding lr_normalizer() it handles the case where you want to scan through learning rates but have more than one optimizer which has its default learning rate in a different order of magnitude. This way we can just key in one value, and have it effect different optimizers as a multiplier rather than an absolute value. For example SGD is in the order of 0.01 were as RMSprop is in the order of 0.001.

**Comment by mikkokotila** [comment]
Really great regarding the doc strings! :) I'll do Reporting after your PR.

**Comment by x94carbone** [comment]
Ah makes total sense. I'll add that to the documentation!
