### ISSUE TITLE
How can I handle the inputs of seq2seq structure

### ISSUE THREAD

**Issue by chjq201410695** [autonomio/talos#123]
Since a 'teacher forcing' stype seq2seq has two inputs (encoder_input and decoder_input), so theh shape of my input seems like 
                                          ( [encoder_input, decoder_input], decoder_output ), 
but the ta.scan(x=x, y=y) just could be feeded ONE input how could I handle this issue.
Moreover, my input shape is 3-D.  like (None, 1, 27) .   the second-dimention -- 1, means one time step.

-----------------------------------------------------------------------------------------
Here is my error:

  0%|          | 0/1 [00:00<?, ?it/s]

Train on 2454936 samples, validate on 433224 samples
Epoch 1/200

 - 56s - loss: 521.4868 - val_loss: 280.2057
Epoch 2/200
 - 54s - loss: 167.9164 - val_loss: 128.9195
Epoch 3/200
 - 54s - loss: 68.5409 - val_loss: 108.7375
Epoch 4/200
 - 54s - loss: 45.1891 - val_loss: 105.2479
Epoch 5/200
 - 54s - loss: 39.3365 - val_loss: 103.3062
Epoch 6/200
 - 54s - loss: 37.2608 - val_loss: 106.7455
Epoch 7/200
 - 54s - loss: 36.0576 - val_loss: 103.5695

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-52-af111a56260c> in <module>()
     23             grid_downsample=0.0001,
     24             seed= 2018,
---> 25             functional_model=True
     26            )

~/.conda/envs/ML_DNN/lib/python3.6/site-packages/talos/scan/Scan.py in __init__(self, x, y, params, model, dataset_name, experiment_no, x_val, y_val, val_split, shuffle, round_limit, grid_downsample, random_method, seed, search_method, reduction_method, reduction_interval, reduction_window, reduction_threshold, reduction_metric, reduce_loss, last_epoch_value, talos_log_name, clear_tf_session, functional_model, disable_progress_bar, print_params, debug)
    164         # input parameters section ends
    165 
--> 166         self._null = self.runtime()
    167 
    168     def runtime(self):

~/.conda/envs/ML_DNN/lib/python3.6/site-packages/talos/scan/Scan.py in runtime(self)
    169 
    170         self = scan_prepare(self)
--> 171         self = scan_run(self)

~/.conda/envs/ML_DNN/lib/python3.6/site-packages/talos/scan/scan_run.py in scan_run(self)
     19                      disable=self.disable_progress_bar)
     20     while len(self.param_log) != 0:
---> 21         self = scan_round(self)
     22         self.pbar.update(1)
     23     self.pbar.close()

~/.conda/envs/ML_DNN/lib/python3.6/site-packages/talos/scan/scan_round.py in scan_round(self)
     45 
     46     _hr_out = run_round_results(self, _hr_out)
---> 47     self._val_score = get_score(self)
     48     write_log(self)
     49     self.result.append(_hr_out)

~/.conda/envs/ML_DNN/lib/python3.6/site-packages/talos/metrics/score_model.py in get_score(self)
     33         # for functional model experimental support
     34         if self.functional_model:
---> 35             y_pred = _functional_predict(self.keras_model, self.x_val)
     36         # all other cases
     37         else:

~/.conda/envs/ML_DNN/lib/python3.6/site-packages/talos/metrics/score_model.py in _functional_predict(model, x, batch_size, verbose)
      9     proba = model.predict(x,
     10                           batch_size=batch_size,
---> 11                           verbose=verbose)
     12 
     13     if proba.shape[-1] > 1:

~/.conda/envs/ML_DNN/lib/python3.6/site-packages/keras/engine/training.py in predict(self, x, batch_size, verbose, steps)
   1815         x = _standardize_input_data(x, self._feed_input_names,
   1816                                     self._feed_input_shapes,
-> 1817                                     check_batch_axis=False)
   1818         if self.stateful:
   1819             if x[0].shape[0] > batch_size and x[0].shape[0] % batch_size != 0:

~/.conda/envs/ML_DNN/lib/python3.6/site-packages/keras/engine/training.py in _standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
     84                 'Expected to see ' + str(len(names)) + ' array(s), '
     85                 'but instead got the following list of ' +
---> 86                 str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
     87         elif len(names) > 1:
     88             raise ValueError(

ValueError: Error when checking model : the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[15.7583  ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        [ 9.34305 ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ]],

       [[19.6959 ...

--------------------------------------------------------------------------------------
Here are my talos params and ta.Scan() :

p = {
    'first_neuron': [32, 64, 96],
    'second_neuron': [32, 64, 96],
    'fourth_neuron': [16, 32, 64],
    'lr': [0.001,0.01,0.1,1,10],
    'activation': [relu, elu, linear],
    'optimizer':[Adam, Nadam],
    'dropout':[0.2,0.3,0.4,0.5,0.6],
    'batch_size': [128, 256, 512]
    }
t = ta.Scan(x = train,
            y = train[:,1:,[0]],
            model= model_experiment,
            params=p,
            random_method='quantum',
            dataset_name="Xi'an_taxi",
            experiment_no='1',
            x_val = test,
            y_val = test[:,1:,[0]],
            seed= 2018,
            functional_model=True
            )

---------------------------------------------------------------------------- 
Here is my keras model:

def model_experiment(x_train, y_train, x_test, y_test, params):
    global EPOHS
    n_input_dim = 27
    x_train_encoder, x_train_decoder = train[: , : , :], train[: , 0, :].reshape(len(train), 1, 27)
    x_test_encoder, x_test_decoder = test[ : , : , :], test[: , 0, :].reshape(len(test), 1, 27)

    #Encoder
    encoder_inputs = Input(shape=(None,n_input_dim),name='encoder_inputs')
    dropout1 = Dropout(params['dropout'])(encoder_inputs)
    encoder_lstm1 = CuDNNLSTM(params['first_neuron'],kernel_initializer='orthogonal',return_sequences=True,name='encoder_lstm1')
    encoder_lstm1_output = encoder_lstm1(dropout1)
    dropout2 = Dropout(params['dropout'])(encoder_lstm1_output)
    encoder_lstm2 = CuDNNLSTM(params['second_neuron'],kernel_initializer='orthogonal',return_sequences=False,return_state=True,name='encoder_lstm2')
    encoder_outputs, state_h, state_c = encoder_lstm2(dropout2)
    encoder_states = [state_h, state_c]
    
    #Decoder
    decoder_inputs = Input(shape=(None,n_input_dim),name='decoder_inputs')

    decoder_lstm1 = CuDNNLSTM(params['second_neuron'],return_sequences=True,return_state=False,name='decoder_lstm1')
    decoder_lstm1_output = decoder_lstm1(decoder_inputs,initial_state=encoder_states)

    dropout3 = Dropout(params['dropout'])(decoder_lstm1_output)

    decoder_lstm2 = CuDNNLSTM(params['fourth_neuron'],return_sequences=True,return_state=False,name='decoder_lstm2')
    decoder_output = decoder_lstm2(dropout3)

    dropout4 = Dropout(params['dropout'])(decoder_output)

    decoder_dense = Dense(1, activation= params['activation'],name='last_layer_dense')

    decoder_outputs= decoder_dense(dropout4)

    model = Model( [encoder_inputs,decoder_inputs], decoder_outputs, 'model')

    model.compile(optimizer=params['optimizer'](lr_normalizer(params['lr'], params['optimizer'])), 
                                                loss='rmse')

    reduce_LROnPlateau = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=2, mode='auto',min_delta=0, min_lr=0.000001)

    earlyStopping = EarlyStopping(monitor='val_loss', min_delta=0, patience=20, verbose=2, mode='auto')

    out = model.fit([x_train_encoder,x_train_decoder], y_train, 
                        batch_size = params['batch_size'],
                        epochs = EPOCHS,
                        verbose = 2,
                        callbacks = [reduce_LROnPlateau, earlyStopping],
                        validation_data=([x_test_encoder,x_test_decoder], y_test)
                        )
    return out, model

-------------------------------------------------------------------------
It seems like my input shape is not suitable for talos' requirement ? Is there any advise? Thanks.

**Comment by chjq201410695** [comment]
Sorry for my mistake. the error just caused by a misuse of a ")". Now, it is runing after I fixed the mistake. So, I close it.

**Comment by chjq201410695** [comment]
Sorry for my mistake. the error just caused by a misuse of a ")". Now, it is runing after I fixed the mistake. So, I close it.

**Comment by mikkokotila** [comment]
There is no issue with any shape in Talos; if you can use the shape in Keras, you can use the shape in Talos. Did you confirm that your model works in Keras already?

**Comment by chjq201410695** [comment]
> There is no issue with any shape in Talos; if you can use the shape in Keras, you can use the shape in Talos. Did you confirm that your model works in Keras already?

Thanks for response !

Yes, I'm sure it works in keras. You can see that the model was trainning to 7th epoch in talos, and then error appears, which says " Error when checking model : the list of Numpy arrays that you are passing to your model is not the size the model expected."

any other advise? thanks again !

**Comment by mikkokotila** [comment]
To be clear, when you run the exact same model in Keras you get past the 7th epoch? Also could you repeat the above a few times, and see if it always stops in the same epoch. This does not seem like a Talos issue, but let's make sure to the extent we can. There might be a few steps for us to go through.

**Comment by mikkokotila** [comment]
In the current version of Talos, this will work. See [the corresponding section in the docs](https://autonomio.github.io/talos/#/Examples_Multiple_Inputs) for an example of multi-input model.

Closing here.
