### ISSUE TITLE
Import error: can not import name 'log cosh'

### ISSUE THREAD

**Issue by SBNoor** [autonomio/talos#128]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [] I'm up-to-date with the latest release:
    
      pip install -U talos

- [ 2] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

-------------------------------------------------------------------------
I am trying to use talos for optimising my deep convolution neural network. However, every time I run my code, it gives me an error "Import error: cannot import name 'logcosh'" even though I am explicitly import it in the beginning. I've attached a screenshot of my error too.

<img width="564" alt="screen shot 2018-11-12 at 14 32 17" src="https://user-images.githubusercontent.com/23297354/48350535-cf700a80-e687-11e8-8ffc-fad69b1260bc.png">

Could you please tell what am I doing wrong here.

**Comment by mikkokotila** [comment]
Can you share the command you run which produces this. 

How if you just do: 

`from keras.losses import logcosh`

...do you get the same error?

**Comment by SBNoor** [comment]
So I write

<img width="575" alt="screen shot 2018-11-12 at 15 09 36" src="https://user-images.githubusercontent.com/23297354/48352473-0694ea80-e68d-11e8-8856-a02acdf7df0b.png">


And I'm using it:
<img width="435" alt="screen shot 2018-11-12 at 15 10 25" src="https://user-images.githubusercontent.com/23297354/48352506-1c0a1480-e68d-11e8-88b5-56d9711fc1d5.png">

**Comment by SBNoor** [comment]
I tried what  you suggested and I still get the same error. Keras is properly installed because I've implemented neural networks before using Keras with Tensorflow backend. I don't know what is wrong then. 

<img width="565" alt="screen shot 2018-11-14 at 15 29 06" src="https://user-images.githubusercontent.com/23297354/48488903-16920300-e822-11e8-85e4-bcd75aededc0.png">

**Comment by mikkokotila** [comment]
This means the error is coming from your Keras installation for some reason. I would just try: 

```
virtualenv -p python3 new_env
source new_env/bin/activate
pip install keras tensorflow talos
```
...and see if you still get the same error. If yes, then still inside the new_env environment: 

```
pip uninstall keras 
pip install git+https://github.com/keras-team/keras
```

Other than that, because you get the error upon importing from Keras and before anything happens at Talos level, I suggest to post an issue in https://github.com/keras-team/keras/issues.
