### ISSUE TITLE
Run parameter optimization on Spark

### ISSUE THREAD

**Issue by anamf** [autonomio/talos#131]
Hi Team,
Do you have any plan to add some functionality to run this on Spark?
Do you have any recommendation to do the optimization in parallel?
Best,
Ana

**Comment by mikkokotila** [comment]
Hey :) The current situation regarding parallelization can be best captured from #55 and #100. I think [Horodov](https://github.com/uber/horovod) looks very promising and @manofdesign mentioned that he is looking at implementing it. Multi-machine parallelization is definitely an important development track and it will be important to cover it well.

**Comment by anamf** [comment]
Many thanks for your quick response.
I will certainly keep an eye on the developments in this line.
When running on a single GPU, is the hyperparameter optimization run on parallel (multi-threaded)? Or is it only the keras model underneath that is optimized?

**Comment by mikkokotila** [comment]
When you run on a single GPU, there is no option at the moment to split a single Talos experiment in to several threads. What you could do, is use the local parallelism to run several experiments simultaneously with a single GPU.

**Comment by mikkokotila** [comment]
Merging with #566
