### ISSUE TITLE
How do I pass in a list of inputs?

### ISSUE THREAD

**Issue by off99555** [autonomio/talos#132]
In most talos code examples, X input seems to be a 2D numpy array.
But in some of my keras models, it requires a list of 2D numpy arrays because my models are not `Sequential`.
Example list: `[numpyarray1, numpyarray2, numpyarray3]`.

It seems that when I try to pass this list to the `ta.Scan` function, things break.

How do I pass in a list of inputs?

Also, I'm not sure if `talos` supports `pandas` DataFrame or not. But I think it does not support so please do make support for it.

**Comment by off99555** [comment]
By support I mean I can input a list of data frames into the Scan function like so `[df1, df2, df3]`.

**Comment by off99555** [comment]
So with the new talos version, I can use a list of array now?

**Comment by mikkokotila** [comment]
You could do it now in the form of [df1.values, df2.values, df3.values] which is exactly the same as [df1, df2, df3] with support for dataframe :)

**Comment by off99555** [comment]
Yes. I'm feeding a list of numpy arrays now not dataframe. I just think it would be good if talos is flexible to accept both types of inputs.
Anyway, I tried feeding the list of inputs and here's the output:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-61-5f0c25e20311> in <module>()
      3 }
      4 h = ta.Scan(X_train_keras, y_train.values, params, build_deep_model, val_split=0.2,
----> 5             dataset_name='em-wave-pos', experiment_no='1')

c:\users\admin\anaconda3\lib\site-packages\talos\scan\Scan.py in __init__(self, x, y, params, model, dataset_name, experiment_no, x_val, y_val, val_split, shuffle, round_limit, grid_downsample, random_method, seed, search_method, reduction_method, reduction_interval, reduction_window, reduction_threshold, reduction_metric, reduce_loss, last_epoch_value, clear_tf_session, disable_progress_bar, print_params, debug)
    161         # input parameters section ends
    162 
--> 163         self._null = self.runtime()
    164 
    165     def runtime(self):

c:\users\admin\anaconda3\lib\site-packages\talos\scan\Scan.py in runtime(self)
    165     def runtime(self):
    166 
--> 167         self = scan_prepare(self)
    168         self = scan_run(self)

c:\users\admin\anaconda3\lib\site-packages\talos\scan\scan_prepare.py in scan_prepare(self)
     57     # create the data asset
     58     self.y_max = self.y.max()
---> 59     self = validation_split(self)
     60     self.shape = classify(self.y)
     61     self.last_neuron = last_neuron(self)

c:\users\admin\anaconda3\lib\site-packages\talos\utils\validation_split.py in validation_split(self)
     16     else:
     17         if self.shuffle:
---> 18             random_shuffle(self)
     19 
     20         limit = int(len(self.x) * (1 - self.val_split))

c:\users\admin\anaconda3\lib\site-packages\talos\utils\validation_split.py in random_shuffle(self)
     40     np.random.shuffle(random_index)
     41 
---> 42     self.x = self.x[random_index]
     43     self.y = self.y[random_index]
     44 

TypeError: only integer scalar arrays can be converted to a scalar index
```
This is the code:
```python
params = {
    
}
h = ta.Scan(X_train_keras, y_train.values, params, build_deep_model, val_split=0.2,
            dataset_name='em-wave-pos', experiment_no='1')
```
`X_train_keras` is a list containing 4 numpy arrays. What is the issue here? I've already updated to v0.4.4

**Comment by mikkokotila** [comment]
Can you input a list of 4 numpy arrays to a Keras model? Have you tried that what you are trying to do with Talos works with a Keras model as a standalone?

Also as a small pointer check the parameter order for Scan() as it changed for 0.4.4. and just in case it's better to use argument names as well the values (e.g. val_split=0.2 good, and params not good).

**Comment by off99555** [comment]
It works with standalone keras model. The keras accepts 4 numpy arrays fine.
Also the parameter is correct, I also put named parameter and it still doesn't work.

**Comment by mikkokotila** [comment]
What is your use-case for passing a list of 2d-arrays as opposed to passing a single 3d-array? 

Are the four arrays all of the same shape, and what is the shape? 

What is the error message you are getting now (it can't be the same as in 0.4.3 as the functionality is completely changed regarding functional models).

**Comment by off99555** [comment]
Here's the shape of each array. 3 of them are 2D but one of them is 1D:
```
    input_x = keras.Input(shape=(200,1), name='x')
    input_y = keras.Input(shape=(200,1), name='y')
    input_z = keras.Input(shape=(200,1), name='z')
    input_q = keras.Input(shape=(4,), name='q')
```
So you cannot just pass a single 3D array and that's definitely a hack not a solution.
The error above is from version 0.4.4 as I have already printed the version to the notebook in the same session and it said 0.4.4.

I can make this kinda work by sending a numpy array of shape (None, 604) into the Scan function instead of sending the list. And then I would split it into a list later inside the model function. But that means the data is being splitted every single time the model function is called.

**Comment by off99555** [comment]
Here's the model function:
```python
# build and train then return the history and the model
def build_deep_model(X_train, y_train, X_val, y_val, params):
#     X_train_keras = wave_df_to_keras_inputs(X_train)
#     X_val_keras = wave_df_to_keras_inputs(X_val)
    X_train_keras = X_train
    X_val_keras = X_val
    print(X_val_keras)
    input_x = keras.Input(shape=(200,1), name='x')
    input_y = keras.Input(shape=(200,1), name='y')
    input_z = keras.Input(shape=(200,1), name='z')
    input_q = keras.Input(shape=(4,), name='q')
    def compute_wave_features(x, name=None):
        x = keras.layers.Conv1D(32, 5, strides=2, padding='same', activation='relu')(x)
        x = keras.layers.Conv1D(32, 5, strides=2, padding='same', activation='relu')(x)
        x = keras.layers.Conv1D(32, 5, strides=2, padding='same', activation='relu')(x)
        x = keras.layers.Conv1D(32, 5, strides=2, padding='valid', activation='relu')(x)
        x = keras.layers.Flatten()(x)
        x = keras.layers.Dense(64, activation='relu', name=name)(x)
        return x
    feature_x = compute_wave_features(input_x, 'feature_x')
    feature_y = compute_wave_features(input_y, 'feature_y')
    feature_z = compute_wave_features(input_z, 'feature_z')
    features = keras.layers.Concatenate()([feature_x, feature_y, feature_z, input_q])
    features = keras.layers.Dense(32, activation='relu')(features)
    readout = keras.layers.Dense(y_train.shape[1], activation='linear', name='readout')(features)
    deep_model = keras.models.Model(inputs=[input_x, input_y, input_z, input_q], outputs=readout)
    deep_model.compile('adam', loss='mse', metrics=['mae', r2_keras])
#     deep_model.summary()

    callbacks = [
        keras.callbacks.EarlyStopping(patience=3)
    ]
    history = deep_model.fit(X_train_keras, y_train, epochs=500, validation_data=[X_val_keras, y_val], callbacks=callbacks, verbose=2)
    best_r2 = np.max(history.history['val_r2_keras'])
    epochs = history.epoch[-1] + 1
    print("Best val_r2_keras score:", best_r2, 'Epochs:', epochs)
    return history, deep_model
```

**Comment by off99555** [comment]
Here's how I think the error occurs:
When I give Scan() a list of numpy arrays, and then Scan() will need to split the data into train and validation right?
But a list cannot be splitted easily compared to an array. So I think you need to investigate how you do split when a list is being fed.

**Comment by mikkokotila** [comment]
That's right, I can see now the error message is from the latest version. What happens there is that Talos tries to perform validation split, but is unable to do it as the input is a list with 4 arrays, so the approach you mention makes sense here. As long as you do the split on numpy array level, this should not make much difference in terms of performance. 

To have a better understanding of your purpose for doing things in this way, what are the four arrays inside the list (what do they represent) and what is that you are trying to predict?

**Comment by mikkokotila** [comment]
Well, splitting arrays inside a list would be very simple in the sense of treating each array separately. But first I need to understand what is that we're trying to do here (as this is the first time I come across the need to pass arrays inside a list into a single model).

**Comment by off99555** [comment]
There are many scenarios where passing a list is important.
Suppose you have a problem of predicting the profession of a person in the picture.
You have picture as the input and luckily, you also have the age and gender of the person along with the picture.
You now need to send 3 information, image, age, and gender to keras. Keras then need to classify whether the person is a programmer or a singer.
And the information along with the image is very important, if you are male, you are more likely to be a programmer.
You cannot just squeeze them into one array because each information is of different type.

FYI, my problem is about predicting a position of an electromagnetic wave receiver.
The wave has 3 axis, XYZ and I also have another device (an IMU) that measures the orientation of the receiver.

**Comment by mikkokotila** [comment]
By the way, once we resolve your case, I think it will make sense to create a notebook example that deals with a typical wave positional prediction case. Generally speaking the optimal Keras way of doing something is far simpler than what the user thinks.

**Comment by off99555** [comment]
The difference is also about the abstraction level.
For example, pixel is a low-level but for gender it's quite high level.
This means you can feed the gender at a later layer.

E.g. the image will be convolved and about 2 layers later then you concatenate with gender feature, then connect to dense layer. This cannot be done when you have only one input.

Keras also has example about multi-inputs so you can take a look at it. We need list of inputs to feed to the model. https://keras.io/getting-started/functional-api-guide/

**Comment by off99555** [comment]
Another problem when I Evaluate:
```python
e = ta.Evaluate(h)
e.evaluate(X_train.values, y_train.values, metric='val_r2_keras')
```
I use the exact same way of inputting the data. That is feeding the array but now the model expects the list.
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-88-3c803f58efff> in <module>()
      1 e = ta.Evaluate(h)
----> 2 e.evaluate(X_train.values, y_train.values, metric='val_loss')

c:\users\admin\anaconda3\lib\site-packages\talos\commands\evaluate.py in evaluate(self, x, y, model_id, folds, shuffle, average, metric, asc)
     37 
     38         for i in range(folds):
---> 39             y_pred = model.predict(kx[i]) >= 0.5
     40             scores = f1_score(y_pred, ky[i], average=average)
     41             out.append(scores * 100)

c:\users\admin\anaconda3\lib\site-packages\keras\engine\training.py in predict(self, x, batch_size, verbose, steps)
   1147                              'argument.')
   1148         # Validate user data.
-> 1149         x, _, _ = self._standardize_user_data(x)
   1150         if self.stateful:
   1151             if x[0].shape[0] > batch_size and x[0].shape[0] % batch_size != 0:

c:\users\admin\anaconda3\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    749             feed_input_shapes,
    750             check_batch_axis=False,  # Don't enforce the batch size.
--> 751             exception_prefix='input')
    752 
    753         if y is not None:

c:\users\admin\anaconda3\lib\site-packages\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    100                 'Expected to see ' + str(len(names)) + ' array(s), '
    101                 'but instead got the following list of ' +
--> 102                 str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
    103         elif len(names) > 1:
    104             raise ValueError(

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 4 array(s), but instead got the following list of 1 arrays: [array([[-0.01658162, -0.88896018, -1.08376316, ...,  0.28      ,
        -0.66      ,  0.61      ],
       [ 0.20363044, -2.47279311, -3.06567174, ...,  0.28      ,
        -0.66      ,  0.61      ],...
```

**Comment by mikkokotila** [comment]
Got it. This is an interesting approach you are articulating, and it sounds relevant to consider. Would it be possible for you to produce the simplest possible example of Keras model and dummy dataset so I can play around with the wave position prediction task. Without any consideration to Talos, just something that works in Keras. I could try and do it later today. Will try a couple of things to make sure I'm on the same page with you on this, and then we could discuss next steps.

**Comment by off99555** [comment]
And when I do feed it the list the model said it cannot do KFold:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-89-4e43c53b25f9> in <module>()
      1 e = ta.Evaluate(h)
----> 2 e.evaluate(X_train_keras, y_train.values, metric='val_r2_keras')

c:\users\admin\anaconda3\lib\site-packages\talos\commands\evaluate.py in evaluate(self, x, y, model_id, folds, shuffle, average, metric, asc)
     34         model = activate_model(self.scan_object, model_id)
     35 
---> 36         kx, ky = kfold(x, y, folds, shuffle)
     37 
     38         for i in range(folds):

c:\users\admin\anaconda3\lib\site-packages\talos\utils\validation_split.py in kfold(x, y, folds, shuffled)
     47 
     48     if shuffled is True:
---> 49         x, y = shuffle(x, y)
     50 
     51     out_x = []

c:\users\admin\anaconda3\lib\site-packages\wrangle\shuffle.py in shuffle(x, y)
      9     random.shuffle(random_index)
     10 
---> 11     x = x[random_index]
     12     y = y[random_index]
     13 

TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by off99555** [comment]
OK. Another quetsion, after I do the Scan(), how do I access the trained model other than Deploying and Restoring from disk?
I want to evaluate the model myself.
Is there something I can do like `scan.get_best_model().predict(stuff)`?

**Comment by mikkokotila** [comment]
You could use `best_model()` to identify the id of the best model, and then `model = activate_model(id)` and finally `model.predict(x)`.

You can access it by: 

`from talos.utils.best_model import best_model, activate_model`

All the models are stored in saved_models in the Scan() object and weights in saved_weights, so you could also hand pick any based on analyzing the results and then activate it. 

If you want to do it in a one-liner, you can: 

`activate_model(scan_object, best_model(scan_object, 'val_acc', False)).predict(X)`

**Comment by mikkokotila** [comment]
Thanks, I checked it and everything seems to be in place. I'm working on something else at the moment, but most likely later this evening would spend sometime learning about this problem. 

Very cool prediction problem you are working on.

**Comment by mikkokotila** [comment]
@off99555 I've made the changes on my local branch to support the case where input is a list of arrays. Because this is in the mainline of the program, it will take a little bit time before it will make its way to production, but I think I should be able to have it in daily-dev in the next few days (if not already later today). Thanks for making the case.

**Comment by mikkokotila** [comment]
I've looked more into this as well as going through the actual example you had provided, and realized that it's super simple to overcome this by explicitly passing validation data from Scan(). This way you have full control over both datasets, and the error you had posted would not arise. So I've decide not to add this into Talos as a feature.

Regarding the best_model ... check out the scan object in the new version v.0.4.5 and you will find new properties there that meet your requirement. There is also a new higher level command Autom8() which radically simplifies the workflow (effectively reducing it to a single command). Autom8 is still early in the sense that it accepts bare minimum of arguments, but gives an indication of the simplicity towards we can go.

Closing here.

**Comment by sbhttcha** [comment]
could you may be give an example of the Scan() call for the Keras functional API based model where you have multiple inputs?

**Comment by mikkokotila** [comment]
> I've looked more into this as well as going through the actual example you had provided, and realized that it's super simple to overcome this by explicitly passing validation data from Scan(). 

Have you tried that?

**Comment by sbhttcha** [comment]
Yes. This is what I'd like my scan to look like where I am passing multiple inputs to a multi-channel keras model: ta.Scan(x=[a_train, b_train],
            y=y_train,
            x_val=[a_test, b_test],
            y_val=y_test,
            model=test_model,
            params=p,
            dataset_name='test',
            experiment_no='1', clear_tf_session=False)

The keras model inputs this:
model = Model(inputs=[a_input, b_input], outputs=output)

Compile looks like this:
history = model.fit([a_train, b_train], y_train, validation_data=([a_test, b_test], y_test), callbacks=[live()], epochs=100, shuffle=True, verbose=1)

**Comment by sbhttcha** [comment]
> 
> 
> @sbhttcha
> 
> > I've looked more into this as well as going through the actual example you had provided, and realized that it's super simple to overcome this by explicitly passing validation data from Scan().
> 
> Have you tried that?

Hi, I was wondering if you had any thoughts to the multiple input as in the above example? Thanks!

**Comment by mikkokotila** [comment]
Have you tried to run what you already have? I don't see any reason why it would not work.

**Comment by sbhttcha** [comment]
Thank you for pointer. I was getting a strange error with the dependent variable but found the solution in one of the other posted issues. I'm able to execute my model now. Thanks for a developing this great package to track hyperparameters.

**Comment by jdonzallaz** [comment]
Hi, you said that we can add x_val/y_val to avoid validation split. It works great.
But there is still the problem to evaluate the models with cross-validation.
I tried with the last version (0.5.0), there is still the error when passing a list of inputs.

```python
e = ta.Evaluate(h)
e.evaluate([X_test_image, X_test_others], y_val)

# AttributeError: 'list' object has no attribute 'shape'
```

Related are #155, #145, #178.
