### ISSUE TITLE
Correlate does not work with metrics that are not named in `metric_names()`

### ISSUE THREAD

**Issue by renxida** [autonomio/talos#136]
At

https://github.com/autonomio/talos/blob/01fd639741167d379abc46e8e1846a2b89ea3d99/talos/commands/reporting.py#L55

When a metric name not  in the return value of `metric_names()` is supplied, I get a `ValueError: cannot insert abracadabra, already exists`

A long term solution is to allow talos to infer metric names from the history object.

But for now I would like to change

```
        columns = [c for c in self.data.columns if c not in metric_names()]
        out = self.data[columns]
        out.insert(0, metric, self.data[metric])
```

to

```
       columns = [c for c in self.data.columns if (c not in metric_names()) and c != metric]
       out = self.data[columns]
```

which allows for custom metrics.

I'll submit a merge request in a few minutes.

PS: Thanks for making this project. I really love the idea and how you structured the whole thing.

**Comment by renxida** [comment]
Here is a test, run with my modified version of reporting.py
https://gist.github.com/fba8417e04b1c9094bf924db0a2938ec

Here is the same test run with the original
https://gist.github.com/renxida/9e53e1307abd44b33e0984e1ec49937c

**Comment by mikkokotila** [comment]
Thanks a lot for this. Sorry I missed and when I saw your PR many merges has passed and some conflicts were created. I think your idea for just inferring from history object is a perfect one. I will explore it later today.

**Comment by mikkokotila** [comment]
FYI: I've added this fix directly to v.0.4.9 which should make it to daily-dev today or tomorrow the latest. Thanks! 

Closing here.

**Comment by mikkokotila** [comment]
I didn't implement it because the fix did not work. It returned an error for any other case except custom metric. So reopening.

**Comment by mikkokotila** [comment]
This is fixed in [v.0.6](https://github.com/autonomio/talos/tree/params-api-test) onwards. Closing here.
