### ISSUE TITLE
Use of Tensorboard

### ISSUE THREAD

**Issue by crzdg** [autonomio/talos#139]
I try to integrate the Tensorboard in the Talos worflow.
But getting following error,

My code looks like this: 

    tensorboard = TensorBoard(log_dir="tensorlogs/{}".format(EXPERIMENT_NAME, defineFolderTensorlogs(params)))
    out = model.fit(x_train, y_train,
                    batch_size=params['batch_size'],
                    epochs=params['epochs'],
                    verbose=0,
                    validation_data=[x_val, y_val],
                    callbacks=[tensorboard])
    return out, model

    h = ta.Scan(x, y, params=boundaries,
                model=definedModel,
                dataset_name='jass',
                experiment_no='1',
                val_split=0.2,
                grid_downsample=0.1,
                clear_tf_session=False)

Has anyone already done this before? Or any other suggestions?

**Comment by crzdg** [comment]
Your Code is not working, also without parameters. Input still 




  File "talos_experiment.py", line 108, in definedModel
    callbacks=[TensorBoard()])
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1363, in fit
    validation_steps=validation_steps)
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 264, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\keras\backend.py", line 2914, in __call__
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\client\session.py", line 1382, in __call__
    run_metadata_ptr)
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable training/Adam/Variable_1 from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/training/Adam/Variable_1)
         [[Node: training/Adam/mul_6/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_1)]]
         [[Node: loss/mul/_29 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_533_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000001B172475198>>
Traceback (most recent call last):
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\client\session.py", line 686, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000001B0ECD5E4E0>>
Traceback (most recent call last):
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\client\session.py", line 686, in __del__
TypeError: 'NoneType' object is not callable

**Comment by crzdg** [comment]
With 

`force_cpu()`

it is working.

After researching I found following Issue in TensorFlow

https://github.com/tensorflow/tensorflow/issues/11812

Might be a GPU, Memory problem?
As it is a test on my desktop only equipment with 2x GTX 670 could.

Will reply after testing on the rig in a more controlled environment.

**Comment by mikkokotila** [comment]
It could be also that you have issue with GTX670 as it has compute capability 3.0. Given force_cpu() resolves the issue.

**Comment by mikkokotila** [comment]
Closing here, feel free to open a new ticket later if you find more issues with TensorBoard.
