### ISSUE TITLE
Tuple Range Representation

### ISSUE THREAD

**Issue by crzdg** [autonomio/talos#140]
I can't find any documentation about how the Tuple represents a range in the the parameter dictionary. Is it as normal: (start, stop, step)?

I'm confused about the examples in the Jupyter Notebooks, what range does (0.1, 10, 10) represent?

**Comment by mikkokotila** [comment]
The range is (start, stop, steps) so (0.1, 10, 10) represents 10 steps between 0.1 and 10.  I.e. the last value is not length of a single step, but the number of total steps.
