### ISSUE TITLE
TensorBoard Histogram

### ISSUE THREAD

**Issue by crzdg** [autonomio/talos#141]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [x] I'm up-to-date with the latest release:
    
      pip install -U talos

- [x] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

Error Trace
```

  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\keras\engine\training.py", line 647, in _make_predict_function
    **kwargs)
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\keras\backend.py", line 2942, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\keras\backend.py", line 2782, in __init__
    with ops.control_dependencies(self.outputs):
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\framework\ops.py", line 4798, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\framework\ops.py", line 4384, in control_dependencies
    c = self.as_graph_element(c)
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\framework\ops.py", line 3339, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\Reto\Anaconda3\envs\jass-kit\lib\site-packages\tensorflow\python\framework\ops.py", line 3418, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("dense_1/Softmax:0", shape=(?, 36), dtype=float32) is not an element of this graph.
```

Following Code is used: 

https://gist.github.com/crzdg/3f85cc4383d6316e9d6b1bcb23b0e9c2

-------------------------------------------------------------------------

May be helpful:

https://stackoverflow.com/questions/46725323/keras-tensorflow-exception-while-predicting-from-multiple-threads

**Comment by mikkokotila** [comment]
Thanks. The "...not an element of this graph" is an issue that I'm not willing to deal with as there is a lot of confusion around it. It is well known that Keras is not handling this, but it needs to be explicitly handled on tf. If Keras starts to support this in some meaningful way, the problem will go away, otherwise I'm afraid not. 

What do you want to use TensorBoard for?

**Comment by mikkokotila** [comment]
By the way, are you aware of: 


```
from talos import live
model.fit(callbacks=[live()])
```

It's by no means a replacement for TensorBoard, but it resolves the most important need, which is to be able to watch epoch-by-epoch progress visually.

**Comment by crzdg** [comment]
No I'm not aware of live
Thanks for this!

Will try to use it.

Just playing around with it. Part of a project I'm doing. Just used it in the manual deployment process. Just tried to fit the actual Model into Talos and discovered this. 🗡 
No worries, I will find a way to get to some graphs :D

**Comment by mikkokotila** [comment]
How did it go? Did you get TensorBoard working?

**Comment by mikkokotila** [comment]
Closing this as it's not related with Talos, but for whom it may concern, generally this error is overcome (regardless of where it appears) by setting `talos.Scan(...clear_session=False...)`.
