### ISSUE TITLE
name 'rcParams' is not defined error with Reporting()

### ISSUE THREAD

**Issue by Kinzerfest** [autonomio/talos#142]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [v ] I'm up-to-date with the latest release:
    
      pip install -U talos

- [ v] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

-------------------------------------------------------------------------

```
KeyError                                  Traceback (most recent call last)
<ipython-input-78-b694c35410f9> in <module>()
----> 1 r.plot_regs(x='acc', y='loss')

/usr/local/lib/python3.6/dist-packages/talos/commands/reporting.py in plot_regs(self, x, y)
    104         '''
    105 
--> 106         return regs(self.data, x, y)
    107 
    108     def plot_bars(self, x, y, hue, col):

/usr/local/lib/python3.6/dist-packages/astetik/plots/regs.py in regs(data, x, y, hue, marker, fit_reg, draw_scatter, logres, palette, style, dpi, title, sub_title, x_label, y_label, legend, x_scale, y_scale, x_limit, y_limit, outliers, save)
    117 
    118     # HEADER STARTS >>>
--> 119     palette = _header(palette, style, n_colors=1, dpi=dpi)  # NOTE: y exception
    120     # <<< HEADER ENDS
    121 

/usr/local/lib/python3.6/dist-packages/astetik/style/template.py in _header(palette, style, n_colors, dpi, fig_width, fig_height)
     48     style_dic = styles(dpi)
     49     for key in style_dic.keys():
---> 50         rcParams[key] = style_dic[key]
     51 
     52     return palette

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in __setitem__(self, key, val)
    821     path = get_data_path()  # guaranteed to exist or raise
    822     fname = os.path.join(path, 'matplotlibrc')
--> 823     if not os.path.exists(fname):
    824         warnings.warn('Could not find matplotlibrc; using defaults')
    825 

KeyError: 'xtick.labelbottom is not a valid rc parameter. See rcParams.keys() for a list of valid parameters.'
```

r is the reporting object from a complete scan. This doesn't even work on the example notebook "comprehensive" on github, whatever I've tried running it is dysfunctional.

**Comment by Kinzerfest** [comment]
![image](https://user-images.githubusercontent.com/26168327/48920724-27fd8f80-ee60-11e8-9f3f-ac44f0810327.png)

The function high returns but correlate fails to run due to a key error, despite a valid key being present and used in the function above.

**Comment by fdon** [comment]
Same problem here: reporting plots not working due to:
'xtick.labelbottom is not a valid rc parameter. See rcParams.keys() for a list of valid parameters.'

name 'rcParams' is not defined

**Comment by lmvanpoppel** [comment]
> Same problem here: reporting plots not working due to:
> 'xtick.labelbottom is not a valid rc parameter. See rcParams.keys() for a list of valid parameters.'
> 
> name 'rcParams' is not defined



Hello, I have a similar problem with reporting plots:
KeyError: 'savefig.frameon is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'

Only I do not get the "name 'rcParams' is not defined"

What can I do to solve this?
