### ISSUE TITLE
Talos Objects do not exist on Mac OS 10.14.1 with pip 18.1

### ISSUE THREAD

**Issue by 00SteinsGate00** [autonomio/talos#143]
Hey there,

this is more of a general problem not specific to any model but just for the record, my model works outside of Talos with Keras and I'm up to date.

On the server that is running Linux (I think some flavor of OpenSuse) Talos seems to work fine but on my machine on Mac OS  10.14.1 nothing's there. Let me explain.

I installed Talos using
```
pip3 install talos
```
in a virtual environment. Within that environment I just start a python3 interpreter and type
```
import talos as ta
```
which works perfectly fine. As soon as I try something like
```
ta.Scan()
```
I get
```
>>> ta.Scan()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'talos' has no attribute 'Scan'
```

Typing `ta.` and using tab for autocompleting shows only my own methods but none of the ones that should be available by talos.

I tried Google and I looked through the closed issues but I didn't find anything.

Best regards

**Comment by mikkokotila** [comment]
Thanks a lot for taking the time to go through the closed issues first :) 

Do you have a folder or file named talos in your present working directory?

**Comment by 00SteinsGate00** [comment]
Thanks for the quick reply. In fact yes I do, my file was called `talos.py`and I feel incredibly stupid now :D

It failes now on import with `ModuleNotFoundError: No module named 'requests'` but that's something different, maybe a missing pip package, I'll figure that out.

Super sorry  that I have wasted your time for such a stupid mistake.

**Comment by mikkokotila** [comment]
No worries :) Yes, requests needs to be installed in python3 separately. This is fixed in the 0.4.5 where requests is installed upon Talos installation.

**Comment by 00SteinsGate00** [comment]
Yeah I figured that and installed the requests library. Thanks again 🙂

**Comment by faridjb** [comment]
hi @mikkokotila 
I have the same problem as @00SteinsGate00  said in both ubuntu 19.10 and windows 10. but I checked the folder for file or folder with the same name of Talos. I
![Screenshot from 2019-11-03 19-08-05](https://user-images.githubusercontent.com/39406281/68087671-5572fb80-fe6d-11e9-98d6-5d8fe7309225.png)
 didn't have this file or folder in my work directory . can you help me
