### ISSUE TITLE
import talos in closed network

### ISSUE THREAD

**Issue by mapmox** [autonomio/talos#147]
Hi, 

I try to import talos on a machine without network connection, but it hangs while trying to connect to some server
...
File "/home/map/anaconda3/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/map/anaconda3/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
KeyboardInterrupt

the initial line within talos is
 from .commands.reporting import Reporting

Is this connection necessary for running the tool?

Best regards,
Markus

**Comment by mikkokotila** [comment]
This only has to do with reporting, and you will be able to do everything else ok even you don't have Astetik (the error is coming from there).

**Comment by mapmox** [comment]
Ok, thanks for the quick answer!
How can I import talos without network? Since currently its running in a 
  urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
after a very long timeout.

**Comment by mikkokotila** [comment]
You would have to manually remove importing of `astetik`. You can do that from the main init.py. Then because you have removed it, you have to also remove the line where `Reporting` is imported, as that relies on `astetik`. 

I've added this to the next release, it might take a few weeks but after that it should be possible to automatically deal with this.

**Comment by mapmox** [comment]
Ok, thanks for your help!

**Comment by mikkokotila** [comment]
This is now fixed and will be rolled-out in v.0.4.6. This should be available in daily-dev later today. This needs to be fixed upstream at astetik level for the longer-term. Closing here.

**Comment by mikkokotila** [comment]
It turns out that two underlying packages (astetik and chances) both required internet connection. This will be resolved in those packages up to pypi still today, so finally it will be possible to use Talos without modification behind a closed network.
