### ISSUE TITLE
human readable format for best parameters

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/talos#149]
As per #146 let's add a list of dictionaries format for best_params in addition to the current (which is for the purpose of feeding it directly into the experiment programmatically).

**Comment by mikkokotila** [comment]
Basically we need to have a dictionary for the best parameters as opposed to array. Or the array needs to be in the format ['batch_size', 100] so it's human readable. But most likely it will be dictionary.

The more robust way would be to go through scan_object.best_model() or even better yet Evaluate(scan_object) and yield the best_params after those processes but for now that's not supported. Just thinking out loud here.

**Comment by nowittynamesleft** [comment]
Currently the documentation at [https://autonomio.github.io/docs_talos/#reporting](https://autonomio.github.io/docs_talos/#reporting) says that best_params is a dictionary, when it actually returns an array.

**Comment by mikkokotila** [comment]
Thanks :)

**Comment by mikkokotila** [comment]
Docs is now entirely updated, and this is handled as well. It's available currently only in daily-dev. Closing here.
