### ISSUE TITLE
How to run a multi-input model with talos?

### ISSUE THREAD

**Issue by TianLin0509** [autonomio/talos#155]
I really like talos and I'm new to it. 
I wonder if talos  can work at multi-input models, as I failed in my keras model. 

The code is really simple as an example
```
x = np.random.randn(100,10);
y = np.random.randn(100,1);

inputs = Input(shape=(x.shape[1],))
inputs_2 = Input(shape=(x.shape[1],))
layer = Dense(20)(inputs)
layer = Dropout(0.1)(layer)
outputs = Dense(1)(layer)
model = Model([inputs, inputs_2], outputs)
model.compile(loss='mse', optimizer='adam')

history = model.fit([x, x], y,
                    batch_size=10,
                    epochs=10,
                    verbose=2)
```

It can work well without Talos. 

Then, following the function Keras model example in github, I rewrite it  as follows:
```
x = np.random.randn(100,10);
y = np.random.randn(100,1);

def breast_cancer_model(x_train, y_train, x_val, y_val, params):
    inputs = Input(shape=(x_train.shape[1],))
    inputs_2 = Input(shape=(x_train.shape[1],))
    layer = Dense(params['first_neuron'], activation=params['activation'],
                  kernel_initializer=params['kernel_initializer'])(inputs)

    layer = Dropout(params['dropout'])(layer)

    outputs = Dense(1, activation=params['last_activation'],
                    kernel_initializer=params['kernel_initializer'])(layer)

    model = Model([inputs,inputs_2], outputs)

    model.compile(loss=params['losses'],
                  optimizer=params['optimizer'](),
                  metrics=['acc'])

    history = model.fit([x_train, x_train], y_train,
                        validation_data=[x_val, y_val],
                        batch_size=params['batch_size'],
                        epochs=params['epochs'],
                        verbose=0)

    return history, model


# then we can go ahead and set the parameter space
p = {'first_neuron':[9, 10, 11],
     'batch_size': [30],
     'epochs': [100],
     'dropout': [0],
     'kernel_initializer': ['uniform','normal'],
     'optimizer': [Nadam, Adam],
     'losses': [binary_crossentropy],
     'activation':[relu, elu],
     'last_activation': [sigmoid]}

t = ta.Scan(x=[x,x],
            y=y,
            model=breast_cancer_model,
            grid_downsample=1,
            params=p,
            dataset_name='breast_cancer',
            experiment_no='1',
            functional_model=True)
```

Unfortunately, it can't work. 
I wonder if I have made some mistakes, or talos just can't support the multi-input models.
Please help
Thanks in advance and sorry for my English

**Comment by mikkokotila** [comment]
Thanks :) 

I think the problem would arise here from the fact that x is a list where list items are arrays. What are you trying to achieve by doing it?

**Comment by TianLin0509** [comment]
Thank you for your response. as my model needs multiple input, so I want to pass my train data as list to the Scan function. Is it correct? Or how can I do let the multiple input function work with talos? Or can you modify the code I proposed as an example.
Thankyou

**Comment by mikkokotila** [comment]
It's still not clear for me why you want to input multiple inputs to a single Keras model? Could you explain more about your use-case. 

Right now you can't input a list in to Scan().

**Comment by lawrencechiukj** [comment]
Hi, I also really like to use talos, and I have the same list as input situation here.

And my use-case is from here:
http://nbviewer.jupyter.org/github/jdwittenauer/ipython-notebooks/blob/master/notebooks/keras/StructuredTimeSeries.ipynb

Overall, the idea is that you need to input each of the category features in your data to keras embedding layer to output the embedding matrix for each category feature. So for each category feature you need one input layer which will need a list of input array in keras. But besides this user-case, I think in RNN LSTM model, it also needs multiple inputs.

I am still new and please correct me if anything wrong or there is better way to do this. Thank you so much for this.

**Comment by mikkokotila** [comment]
Thanks a lot @lawrencechiukj for the great example notebook. I will try to look into this over the next few days.

**Comment by mikkokotila** [comment]
Closing here.

**Comment by gregstarr** [comment]
In your example, your train model function still takes in a numpy array for x_train. Is there a way to pass in a list for x_train?
