### ISSUE TITLE
Reporting() seems to fail 

### ISSUE THREAD

**Issue by ClarkN3** [autonomio/talos#16]
no matter what I change in the parameters i get
"TypeError: include and exclude must both be non-string sequences"
which i assume is cause by rows containing strings such 
"<class   'keras.optimizers.Adam'>"
is this due to me using my own Adam optimizer? 
other columns include 

kernel_initializer
activations
losses

..so on

**Comment by mikkokotila** [comment]
Could you post the whole trace / error message and also the code it results from.

**Comment by mikkokotila** [comment]
To avoid doubt, Reporting() is intended to be used only once you've already completed a scan and have a .csv file with the results of the scan.

**Comment by mikkokotila** [comment]
It seems to have something to do with the values in the columns that are detected to be float. Can you paste a some rows of the CSV or dump in pastebin or similar and I will try to replicate in my end. I think it should be something straightforward to resolve but might require a few more rounds of back and forth. Thanks.

**Comment by ClarkN3** [comment]
https://pastebin.com/XVW2HiTg

**Comment by mikkokotila** [comment]
Thanks. It seems that the .csv you have is not comma separated (at least that is what I see in the dump). Is that the case and if it, are you doing any manipulation to the file or that is what you get from Talos?

**Comment by ClarkN3** [comment]
Sorry, I opened it in excel without thinking

https://pastebin.com/iudEfu89

**Comment by mikkokotila** [comment]
@ClarkN3 The file you had provided opens just fine with ta.Reporting() on my machine. 

Could you try the following: 

1) save the pastebin dump to file test.csv and 

2) create python virtualenv

```
virtualenv -p python3.6 talos_test
source talos_test/bin/activate
pip install -U talos
```

3) open python console
```
python
```

4) run the code in the python console

```
import talos as ta
ta.Reporting('test.csv')
```

Then if it works, can you try the same but now in conda (as I see you are running on conda) so we eliminate the most obvious possibilities first. Thanks!

**Comment by mikkokotila** [comment]
because I could not replicate this and did not hear from you, closing this now. Let me know if it's still an issue and I'll reopen.
