### ISSUE TITLE
Requirements overwrite tensorflow gpu installation

### ISSUE THREAD

**Issue by twerkmeister** [autonomio/talos#160]
- [x] I'm up-to-date with the latest release:

Hi Mikko,

I am running into a problem with the project dependencies. The training session runs inside a docker container on another server. To that end I build a docker container starting `FROM tensorflow/tensorflow:latest-gpu-py3`. However, when I install talos in that container the tensorflow gpu version gets replaced by the cpu version, as that one is in talos' requirements. My workaround for now is deinstalling `tensorflow` and `tensorflow-gpu` and then reinstalling `tensorflow-gpu`, all after installing talos. However, that has the side effect that I need to upload a >1GB change when pushing the docker container initially.
Is there a better way of handling the tensorflow dependency inside talos?

**Comment by mikkokotila** [comment]
Thanks, I think we have to remove tensorflow from the requirements and let the user do install the version they like. Will do that for the next update which is v.0.4.6. 

For the time being you can `pip install git+https://github.com/autonomio/talos@daily-dev` (I just fixed it). 

Closing here.

Happy new year also!

**Comment by twerkmeister** [comment]
Wonderful, happy new year to you aswell! 🌟

**Comment by Walkoss** [comment]
Hi,

I'm facing this issue even when installing talos from `daily-dev`
@twerkmeister have you find a workaround ?

**Comment by mikkokotila** [comment]
@Walkoss if you create a new environment and install tensorflow first, that should work.

**Comment by Walkoss** [comment]
@mikkokotila 

Here is my Dockerfile:
```
FROM tensorflow/tensorflow:latest

RUN pip install talos
```

It installs `tensorflow` first.
As @twerkmeister said, if we delete `tensorflow` and `tensorflow-gpu` and reinstall `tensorflow-gpu` after talos, then it works.

Problem is that there is a talos's dependency that installs `tensorflow`.

**Comment by mikkokotila** [comment]
I think it's wrangle. I will handle it directly there, so this problem will go away in the future.

**Comment by mikkokotila** [comment]
This has been fixed for sometime, apologies for not updating the ticket. Closing here.
