### ISSUE TITLE
Remove dependency checking and dynamic population of install_requires from setup.py

### ISSUE THREAD

**Issue by KOLANICH** [autonomio/talos#163]
https://github.com/autonomio/talos/blob/master/setup.py#L28

It is not needed anymore, pip will update libraries only if the update is actually required. Dynamic population of that metadata field results in incorrect metadata differrent for different machines.

**Comment by mikkokotila** [comment]
Good catch.

**Comment by mikkokotila** [comment]
@KOLANICH This is done now in daily-dev. Will make its way to master/production soon no doubt. Thanks again and have a nice weekend too. Closing here.
