### ISSUE TITLE
ImportError: cannot import name '_representation'

### ISSUE THREAD

**Issue by anthonylauly** [autonomio/talos#171]
Hi, I have installed the talos by doing : 
pip install talos
The installation done successfully. But every time I do : 
import talos as ta
I got this error : 
ImportError: cannot import name '_representation'

Many Thanks,
Anthony

**Comment by mikkokotila** [comment]
This seems to be related with statsmodels. Check out the information [here](https://stackoverflow.com/questions/50391868/python-3-5-in-statsmodels-importerror-cannot-import-name-representation). Hopefully it helps :)

**Comment by anthonylauly** [comment]
thank you so much. It works well after re-installing the stastsmodels

**Comment by mikkokotila** [comment]
Great to hear :) Have a nice day as well.
