### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by bastianatte** [autonomio/talos#173]
import uproot
import pandas
import keras
import talos as ta
from sklearn.model_selection import train_test_split

from keras import layers, models
from keras.models import Sequential
from keras.layers import Dense

f = uproot.open("/path/to/the/root/file/test_func_94_double.root")
tree = f['Merged_Analysis;1']

dataset = tree.pandas.df(["z_pos","trks","spt2","spt","Dr","clos","clos_qdr","clos_tp","clos_a0","ch\
sq","ismerge"])
features = dataset.loc[:, dataset.columns != "ismerge"].values                                      \
                                                                                                    \

labels = dataset.loc[:, "ismerge"].values
X_train, y_train, x_val, y_val = train_test_split(features,
                                                  labels,
                                                  test_size=0.8,
                                                  random_state=42)

def vertex_model(x_train, y_train,x_val, y_val, params):

    model = Sequential()

    model.add(Dense(params['first_neuron'],
                    kernel_initializer='uniform',
                    activation='sigmoid'))

    model.add(Dense(units=1,
                    kernel_initializer='uniform',
                    activation='sigmoid'))

    model.compile(loss='binary_crossentropy',
                  optimizer='sgd',
                  metrics=['accuracy'])

    out = model.fit(X_train, y_train,
                    epochs=100,
                    validation_data=[x_val, y_val],
                    batch_size=50)
    return out, model

h = ta.Scan(x=X_train,
            y=y_train,
            params={'first_neuron': [4, 8, 16, 32, 64]},
            dataset_name='first_test',
            experiment_no='aaa',
            model=vertex_model,
            grid_downsample=0.1)

the x and y shapes are: 
(97010, 10)
(24253, 10)

the error that I receive is:
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "keras_talos.py", line 57, in <module>
    grid_downsample=0.1)
  File "/home/spinali/Documents/LancsUni/qual_task/virtualenv/classifier/local/lib/python2.7/site-packages/talos/scan/Scan.py", line 163, in __init__
    self._null = self.runtime()
  File "/home/spinali/Documents/LancsUni/qual_task/virtualenv/classifier/local/lib/python2.7/site-packages/talos/scan/Scan.py", line 168, in runtime
    self = scan_run(self)
  File "/home/spinali/Documents/LancsUni/qual_task/virtualenv/classifier/local/lib/python2.7/site-packages/talos/scan/scan_run.py", line 25, in scan_run
    self = result_todf(self)
  File "/home/spinali/Documents/LancsUni/qual_task/virtualenv/classifier/local/lib/python2.7/site-packages/talos/utils/results.py", line 82, in result_todf
    self.result.columns = self.result.iloc[0]
  File "/home/spinali/Documents/LancsUni/qual_task/virtualenv/classifier/local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1478, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/spinali/Documents/LancsUni/qual_task/virtualenv/classifier/local/lib/python2.7/site-packages/pandas/core/indexing.py", line 2102, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/spinali/Documents/LancsUni/qual_task/virtualenv/classifier/local/lib/python2.7/site-packages/pandas/core/indexing.py", line 2009, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

I also, in addtition, sometimes receive the following error:
IndexError: index 88770 is out of bounds for axis 0 with size 24253

The parameter used is just the first neuron cause this was aimed as a talos test.

**Comment by mikkokotila** [comment]
That will not work because what you are doing is you are downsampling a grid of 5 (total possible permutations of your params dictionary) to 10% which means that there are no more permutations left. Remove grid_downsample and you should not get this error anymore. 

For the second error, note how your x and y are of different length. They need to both be the same length, otherwise you would get an error like the second one you are getting.

**Comment by mikkokotila** [comment]
These errors have nothing to do with Talos. It's better to ask questions such as this in stackoverflow as there is a large number of people to help you resolve user support issues. 

But basically you have to make sure that the length of x_train and y_train are same, and same for x_val and y_val. Whenever you run any model, you have to make sure that your input samples and target samples are of the same length. Otherwise you will get these errors.

**Comment by bastianatte** [comment]
ok, fair enough.

Many thanks @mikkokotila, you are so kind.

Cheers!!!!!

**Comment by mikkokotila** [comment]
You're most welcome :) Feel free to open new issues if you hit a snag later. Closing here.
