### ISSUE TITLE
how to evaluate model/s from scan_object?

### ISSUE THREAD

**Issue by davide1993** [autonomio/talos#178]
Wich validation method is used to evaluate the scan object? In Evaluate class I can perform k-cross-fold validation, but I don't find anything about scan object

**Comment by mikkokotila** [comment]
cross validation is performed with f1_score binary for binary average for binary, and macro for multi-class and multi-label. MAE for continuous but we are working on our own metric "distribution of absolute error" so that might become the default. But you have to be on >=v.0.4.7. 

You might find the docstring regarding this (in v.0.4.7) useful. 

```
        '''Evaluate a model based on f1_score (all except regression)
        or mae (for regression). Supports 'binary', 'multi_class',
        'multi_label', and 'regression' evaluation.
        x : array
            The input data for making predictions
        y : array
            The ground truth for x
        model_id : int
            It's possible to evaluate a specific model based on ID. Can be None.
        folds : int
            Number of folds to use for cross-validation
        sort_metric : string
            A column name referring to the metric that was used in the scan_object
            as a performance metric. This is used for sorting the results to pick 
            for evaluation.
        shuffle : bool
            Data is shuffled before evaluation.
        mode : string
            'binary', 'multi_class', 'multi_label', or 'regression'.
        asc : bool
            False if the metric is to be optimized upwards (e.g. accuracy or f1_score)
        print_out : bool
            Print out the results. 
```
Take a look at the [source code](https://github.com/autonomio/talos/blob/daily-dev/talos/commands/evaluate.py) as well.

**Comment by mikkokotila** [comment]
To add here that the next step for evaluation is the ability to input custom evaluation metrics or at least to choose from any of the sklearn ones.

**Comment by davide1993** [comment]
Sorry I did not explain well, which metrics is uses here for evaluation:
```
scan = ta.Scan(X_train, y_train,
                params=params,
                dataset_name=dataset.name,
                x_val=X_test,  #WICH METRIC IS USED HERE???
                y_val=y_test,  #WICH METRIC IS USED HERE???
                experiment_no=date,
                model=dataset.getCNNModel,
                grid_downsample=1)
```
if k-cross-fold validation is performed wich is the value of k?

**Comment by mikkokotila** [comment]
Scan(...) does not involve cross-validation directly. x_val and y_val are treated with whichever metric you choose in your Keras model. So anything that Keras support and you set. Then  when you pick best model later, you will use that model to pick the best model, and only then cross-validation is performed.

**Comment by davide1993** [comment]
So the results reported in csv file like val_loss, val_acc, val_recall_acc.... are performed on x_val and y_val right? it's not correct here to pass the test set as I write in the previous answer, the test set have to be used after picking up the best model, then perform evaluation on that model with k-cross-validation am I wrong?
```
scan = ta.Scan(X_train, y_train,
                params=params,
                dataset_name=dataset.name,
                x_val=x_val,  #HERE VALIDATION SET AND NOT TEST SET
                y_val=y_val,  #HERE VALIDATION SET AND NOT TEST SET
                experiment_no=date,
                model=dataset.getCNNModel,
                grid_downsample=1)
```

then evaluation on test set:
```
    e = ta.Evaluate(scan)
    
    # perform the evaluation
    e.evaluate( x_test, y_test,
                model_id=None,
                folds=10,
                shuffle=True,
                metric='val_acc',
                mode = 'bynary',
                asc=False, #set to true for loss
                print_out=False)    

```

**Comment by davide1993** [comment]
i've got little dataset so I decide to split in 60% training, 20% validation and 20% testing. Maybe is not the perfect size, but with small dataset my model need data to train . Reasonably I think this is a quite god choice. When I try to evaluate with a different metric than 'val_acc' for example 'val_loss' as below
```
e.evaluate( X_test, y_test,
                model_id=None,
                folds=10,
                shuffle=True,
                metric='val_loss',
                #mode = 'bynary',
                asc=True) #set to true for loss
                #print_out=False)    
```

i get :  59.81% (+/- 14.81%)

1. why I get  a percentage?

2. what (+/- 14.81%) means?

3. if I try to specify mode or print_out I get :TypeError: evaluate() got an unexpected keyword argument 'mode', maybe because I haven't the last version of talos??? talos version: '0.4.3'

**Comment by mikkokotila** [comment]
1) it's the % of correct predictions i.e. your models is right 60% of the time
2) it means the standard deviation of the folds i.e. your cross-validation folds have std of 14.81%
3) yes you have to get on with the latest version:

First or good measure: 
`pip uninstall talos`

Then: 
`pip install git+http://github.com/autonomio/talos@dev`

OR

`pip install git+http://github.com/autonomio/talos@daily-dev` (I personally always use this)

**Comment by mikkokotila** [comment]
Closing here.

**Comment by sbhttcha** [comment]
I am using the functional api and so I have 2 inputs. When trying to use evaluate: e.evaluate([X_test_1, X_test_2], y_test.values, folds=10, mode='binary') I am getting this error:
/home/user/.local/lib/python3.6/site-packages/talos/commands/evaluate.py in evaluate(self, x, y, model_id, folds, shuffle, metric, mode, asc, print_out)
     65         model = activate_model(self.scan_object, model_id)
     66 
---> 67         kx, ky = kfold(x, y, folds, shuffle)
     68 
     69         for i in range(folds):

/home/user/.local/lib/python3.6/site-packages/talos/utils/validation_split.py in kfold(x, y, folds, shuffled)
     66 
     67     if shuffled is True:
---> 68         x, y = shuffle(x, y)
     69 
     70     out_x = []

/home/user/.local/lib/python3.6/site-packages/wrangle/shuffle.py in shuffle(x, y)
      9     random.shuffle(random_index)
     10 
---> 11     x = x[random_index]
     12     y = y[random_index]
     13 

TypeError: only integer scalar arrays can be converted to a scalar index
