### ISSUE TITLE
boxplot don't show x axis

### ISSUE THREAD

**Issue by davide1993** [autonomio/talos#183]
if I run this instruction 
`report3.plot_box( report3.data.epochs, report3.data.val_loss, hue='optimizer')`
boxplot don't show epochs why?
epochs: [200,300,400,500],

![immagine](https://user-images.githubusercontent.com/19341977/51593023-64e21300-1ef1-11e9-9ee8-806ae74cb84d.png)

**Comment by mikkokotila** [comment]
Thanks. Legend is also problem here clearly. Don't hold your breath though, plot/Reporting are low priority fixes.

**Comment by mikkokotila** [comment]
Try `report3.plot_box('epochs', 'val_loss', hue='optimizer')` instead. Closing here.
