### ISSUE TITLE
Situation with the  "clear_tf_session" of talos.Scan

### ISSUE THREAD

**Issue by TelmoAdao** [autonomio/talos#186]
Dear Talos developer,

A few days ago, I reported an issue entitled "Talos grid search freezes after a few assays investigation" ( issue #159 ), which was solved thanks to your valuable advise: to use "clear_tf_session=False".

Well, now a similar matter brought me here to ask for your advise once again. When I request talos to scan 4 diferent SGD-based LR in a VGG architecture and using  "clear_tf_session=False", after the 3rd one some memory leaks (OOMs) are issued in the console. It looks like that SGD is more demanding for graphic cards memory (btw just to recall, I am using a couple of Quadro M4000 paired through SLI). Sometimes, scan fails due to OOM error. If I use "clear_tf_session=True", talos scan ends up to freeze unexpectedly, as it was reported before ( issue #159 ).

As you already figured out, I am in the middle of a dilemma. Would you help me out, please?

In advance, thank you for your attention!

**Comment by TelmoAdao** [comment]
Hi there. My Cuda capability is 5.2. It is not recent, but I think that it is not so outdated :) My tensorflow version is 1.8.0. Do you think that I should give it a try to previous tensorflow version with these specs?

**Comment by mikkokotila** [comment]
It's worth trying. I would also search Google, SO and TF issues for something related. Generally speaking when silent die happens, it has something to do with tf and compute resources.
