### ISSUE TITLE
Suggestion: add a progress bar to Scan()

### ISSUE THREAD

**Issue by x94carbone** [autonomio/talos#19]
Perhaps [tqdm](https://github.com/tqdm/tqdm)?

**Comment by mikkokotila** [comment]
Ok great, I will add that. I'm using it in another project, and I think it should be fairly simple. I also have a working implementation of live updating plot that shows progress per epoch so will include both in the same update. It seems the progress bar should be a parameter so it can be turned off (maybe on by default?).

**Comment by x94carbone** [comment]
Sorry missed the question when I read your comment the first time. Yes I think it is standard to have a toggle for it. There must be an easy way to do that with tqdm if that's what you're using. Its important that you mentioned this since some notebooks (Google Colab...) do not play nicely with tqdm!

**Comment by x94carbone** [comment]
I think I understand. There should be ways to manually update the progress bar. Here's an [example](https://stackoverflow.com/questions/45808140/using-tqdm-progress-bar-in-a-while-loop) (I didn't test it yet).

I can look into this in more detail sometime later as well!

**Comment by mikkokotila** [comment]
@x94carbone re 'Edit' > great. I was thinking like that as well. I think there are two sides to this; something that serves the purpose of terminal and notebook use, and then secondarily for the notebook use only. For notebook it seems that a live updating matplotlib plot is an idea situation as you can also see epoch level updates (and get an idea of how the training takes place which can be really valuable especially early in the process or an automated reduction/optimization method is used). How about a very simple x out of xxx rounds left for the universal case?

**Comment by x94carbone** [comment]
@mikkokotila right I totally agree. There's got to be an easy way for the program to detect whether or not its running in a notebook or not. Regardless, since there are some notebooks that don't play nice with these progress bars, we should implement some default behavior first. Something like what you suggested should work great! Particularly, maybe something that constantly overwrites the first output line so we don't overwhelm the user with a ton of output.

**Comment by x94carbone** [comment]
We might not even have to make it that complicated actually- I may have been overthinking it. We could implement three options and let the user choose for themselves. 0 for silent running, 1 for progress bar and 2 for raw text output. Maybe that’s a better starting place than detecting the os or if the user is in a notebook. Then once we have that working we can go from there. What do you think?

**Comment by x94carbone** [comment]
I have another idea actually. We don't need a progress bar, we can do this with the Python 3 print function if we're clever. Backwards compatible via `from __future__ import print_function`, I think. I will give this a shot at some point soon.

**Comment by mikkokotila** [comment]
That would be good if we could do it very simply! :)

**Comment by mikkokotila** [comment]
I've added tqdm which is on by default. Together with some notable changes, you can find it in dev-mikko, and hopefully tomorrow in daily-dev as well (will have to do more testing, and also add some unit tests).

**Comment by Geekgurus** [comment]
This Should Help.
Example Solution From My Experience

Configuration
If #tqdm is not already installed, install it with #pip.

pip install #tqdm
Suppose the flyer in question is called flyer, an instance of the class Flyer. Find where flyer is defined in your IPython profile. Something like:

flyer = Flyer(some_arguments)
We can subclass Flyer, customizing its collect method to incorporate a progress bar.

class FlyerWithProgressBar(Flyer):

    def collect(self):
        yield from tqdm(super().collect())

flyer = FlyerWithProgressBar(some_arguments

If you have some way of knowing in advance how many data points will be yielded by collect, you can provide that information to tqdm to make it more informative. (It can predict the time remaining, for example.) Suppose we have a flyer that always produces 100 data points. The class should be defined like:

class FlyerWithProgressBar(Flyer):

    def collect(self):
        yield from tqdm(super().collect()
Or, add an attribute that can be updated interactively: 👻

**Comment by Geekgurus** [comment]
And finally it goes this way 😳

interactively:

class FlyerWithProgressBar(Flyer):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)  # pass arguments to Flyer
        self.total = 100

    def collect(self):
        yield from tqdm(super().collect(), total=self.total)
Here is a demo of FlyerWithProgressBar.

In [1]: from bluesky.plans import fly

In [2]: flyer = FlyerWithProgressBar()

In [3]: plan = fly([flyer])

In [4]: RE(plan)
100%|█████████████████████████████████████████████████| 100/100 [00:01<00:00, 92.35it/s]
Out[4]: ['3acf0eb7-96bf-4c09-b813-e715dab

**Comment by mikkokotila** [comment]
Progress bar had been added some time ago and now available in master as well as pip so closing here.
