### ISSUE TITLE
UnboundLocalError: local variable 'acc_entropy' referenced before assignment

### ISSUE THREAD

**Issue by DerTunzel** [autonomio/talos#194]
Hey, i hope it is okay to ask here for help. I could not find anything that helps my case.

- [ x] I'm up-to-date with the latest release: Hey i am on release 0.47

- [ x] I've confirmed that my Keras model works outside of Talos. Works perfectly fine with keras on a jupyter notebook

Here is part of my code that i stitched together from some examples and my jupyter notebook where the model runs just fine. :

```
#Some imports 

def minimal():

    #some constants

    #reading a file preprocessing data, vocabulary building and bringing it into a fitting structure
    
 X = np.array(xs)
     Y = np_utils.to_categorical(ys)

     p = {'first_neuron':[25,50,75,100],
          'lr': (0.8, 1.2, 3),
          'first_neuron':[4, 8, 16, 32, 64],
          'hidden_layers':[0, 1, 2, 3],
          'batch_size': (32, 64, 5),
          'epochs': [15, 20, 25, 30, 35],
          'dropout': (0, 0.2, 3),
          'weight_regulizer':[None],
          'emb_output_dims': [None],
          'shape':['brick','long_funnel'],
          'kernel_initializer': ['uniform','normal'],
          'optimizer': [Adam, Nadam, RMSprop],
          'activation':['relu', 'elu', 'sigmoid'],
          'last_activation': ['sigmoid','softmax']}

     def my_model(x_train, y_train, x_val, y_val, params):

          model = Sequential()
         
          model.add(LSTM(params['first_neuron'], input_shape=(NO_OF_SENTENCES, SENTENCE_LENGTH)))
          model.add(Dropout(params['dropout']))
	 
          #hidden_layers(model, params)
 
          #model.add(Dense(3, activation=params['last_activation'], kernel_initializer='normal'))
          model.add(Dense(3, activation=params['last_activation']))

          model.compile(loss="categorical_crossentropy", optimizer=params['optimizer'](lr=lr_normalizer(params['lr'],params['optimizer'])), metrics=["accuracy"])
    
          out = model.fit(x_train, y_train, validation_data=[x_val, y_val], batch_size=params['batch_size'], epochs=params['epochs'], verbose=0)
          print('Ende vom model')
          
          return out, model

     scan_object = ta.Scan(X, Y, model=my_model, params=p, grid_downsample=0.01)

     return scan_object
```

This is the error i get:
 
```
 File "<stdin>", line 1, in <module>
  File "C:\Users\Matunzel\Desktop\PNL\DeepLearning\AdvancedLSTM-150articles-6votes\optimization.py", line 192, in minimal
    scan_object = ta.Scan(X, Y, model=my_model, params=p, grid_downsample=0.01)
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\scan\Scan.py", line 165, in __init__
    self._null = self.runtime()
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\scan\Scan.py", line 170, in runtime
    self = scan_run(self)
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\scan\scan_run.py", line 20, in scan_run
    self = scan_round(self)
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\scan\scan_round.py", line 47, in scan_round
    self.epoch_entropy.append(epoch_entropy(_hr_out))
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\metrics\entropy.py", line 54, in epoch_entropy
    return [acc_entropy, loss_entropy]
UnboundLocalError: local variable 'acc_entropy' referenced before assignment
```

**Comment by mikkokotila** [comment]
Can you try to replace: 

`model.compile(loss="categorical_crossentropy", optimizer=params['optimizer'](lr=lr_normalizer(params['lr'],params['optimizer'])), metrics=["accuracy"])`

with: 

`model.compile(loss="categorical_crossentropy", optimizer='Adam')`

...and see what happens.

**Comment by DerTunzel** [comment]
Still the same error: `ARNING:tensorflow:From C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Ende vom model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Matunzel\Desktop\PNL\DeepLearning\AdvancedLSTM-150articles-6votes\optimization.py", line 193, in minimal
    scan_object = ta.Scan(X, Y, model=my_model, params=p, grid_downsample=0.01)
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\scan\Scan.py", line 165, in __init__
    self._null = self.runtime()
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\scan\Scan.py", line 170, in runtime
    self = scan_run(self)
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\scan\scan_run.py", line 20, in scan_run
    self = scan_round(self)
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\scan\scan_round.py", line 47, in scan_round
    self.epoch_entropy.append(epoch_entropy(_hr_out))
  File "C:\ProgramData\Miniconda3\lib\site-packages\talos\metrics\entropy.py", line 54, in epoch_entropy
    return [acc_entropy, loss_entropy]
UnboundLocalError: local variable 'acc_entropy' referenced before assignment`

**Comment by mikkokotila** [comment]
Is the data something you can share so I can run this in my end?

**Comment by DerTunzel** [comment]
sure, its just some news articles
[NewsScore_Dataset_300articles_5votes.zip](https://github.com/autonomio/talos/files/2862013/NewsScore_Dataset_300articles_5votes.zip)

**Comment by mikkokotila** [comment]
Thanks. 

Try adding `print(out.history)` in your input model after `model.fit( ... )`. Your model will return empty dictionary for history object. Did you try to run the model directly as Keras model first?

**Comment by DerTunzel** [comment]
Hey there,
you were right the history object was empty. I had a look at my code again and i had a wrong intendation when preprocessing the data. Thats why the lists was not long enough for later steps i guess. Now it is doing something and it will take some time ^^ I hope it works now as intended. Thank you very much fpr taking some time to help me. i am fairly new to python and deep learning :)

Could you point me in a direction where i can find some examples to make the most of the data i get? Thank you very much again !

**Comment by mikkokotila** [comment]
Good to hear :) When you say "get most of the data" what do you mean by this?

**Comment by DerTunzel** [comment]
i mean how to properly analyse the data i get after the tool runs through. And maybe how to set the right metrics i want so see from the tool.

**Comment by mikkokotila** [comment]
Did you look at [this](https://towardsdatascience.com/hyperparameter-optimization-with-keras-b82e6364ca53) already?

To make things more meaningful, I would rather use f1-score as a metric. 

`from talos.metrics.keras_metrics import fmeasure_acc`

**Comment by mikkokotila** [comment]
Closing here. Feel free to create new issue if needed.

**Comment by toddpi314** [comment]
@mikkokotila I run into this issue all the time where some grid-search combo results in a bad fit session. It would be ideal if the pass just ignores the missing history, reports poor results, then moves onto the next search yield.
