### ISSUE TITLE
KeyError: 'val_acc'  i tried implementing all the codes in sequence from iris.ipynb but the keyword r.high() raises this error

### ISSUE THREAD

**Issue by hr21** [autonomio/talos#196]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [ ] I'm up-to-date with the latest release:
    
      pip install -U talos

- [. ] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

-------------------------------------------------------------------------

**Comment by mikkokotila** [comment]
Try adding `validation_split=.3` (or any other value) in `model.fit()`.
