### ISSUE TITLE
IndexError: tuple index out of range when using ta.Scan

### ISSUE THREAD

**Issue by YUIWK** [autonomio/talos#198]
Hello, everyone. I am a beginner and learning Keras and Talos recently. 
I suffered a problem and can not figure out it. 
Here is my code.
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
import numpy as np
from pandas import read_csv
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

import talos as ta
from keras.optimizers import Adam, RMSprop,SGD
from keras.models import Sequential
from keras.layers import Dense
from keras.activations import relu, sigmoid
from talos.model import lr_normalizer,hidden_layers

dataset = open('E:\Data.csv')
dataset = read_csv(dataset)

values = dataset.values
values = np.delete(values, [0], axis=1)
values = values.astype('float32')
print(values.shape)

scaler = MinMaxScaler(feature_range=(0, 1))
values = scaler.fit_transform(values)

print(values.shape)
X, Y = values[:,0:4], values[:, 5]
print(X.shape, Y.shape)

X_train,X_test,Y_train, Y_test = train_test_split(X,Y, test_size=0.25, shuffle=False)
print(X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)

def SSHP_MPLs(X_train,Y_train,X_test,Y_test,p):
    model = Sequential()
    model.add(Dense(p['first_neuron'], input_dim=X_train.shape[1], activation=p['activation']))
    model.add(Dropout(p['dropout']))
    hidden_layers(model, p)
    model.add(Dense(Y_train.shape[1], activation=params['last_activation']))
    model.compile(loss='mse',optimizer=p['optimizer'](lr=lr_normalizer(p['lr'], p['optimizer'])),
                  metrics=['mse','mae'])
    history = model.fit(X_train, Y_train,
                        validation_data=[X_test, Y_test],
                        batch_size=p['batch_size'],
                        epochs=p['epochs'],
                        verbose=0)
    return history, model

p = {'lr': (0.5, 5),
     'first_neuron': [5, 10, 15],
     'hidden_layers': [1, 2],
     'batch_size': (100, 500, 1000),
     'epochs': [5],
     'dropout': (0, 0.1, 0.2),
     'optimizer': [Adam, RMSprop,SGD],
     'activation': [relu, sigmoid],
     'last_activation': [relu]}

**_ta.Scan(x=X_train,y=Y_train,params=p,model=SSHP_MPLs,x_val = X_test,y_val = Y_test)_**
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
Here is the error information.
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
IndexError                                Traceback (most recent call last)
<ipython-input-39-75e9b3cf61b6> in <module>
     65      'last_activation': [relu]}
     66 
---> 67 ta.Scan(x=X_train,y=Y_train,params=p,model=SSHP_MPLs,x_val = X_test,y_val = Y_test)

E:\Anaconda\envs\snowflakes\lib\site-packages\talos\scan\Scan.py in __init__(self, x, y, params, model, dataset_name, experiment_no, x_val, y_val, val_split, shuffle, round_limit, grid_downsample, random_method, seed, search_method, reduction_method, reduction_interval, reduction_window, reduction_threshold, reduction_metric, reduce_loss, last_epoch_value, clear_tf_session, disable_progress_bar, print_params, debug)
    161         # input parameters section ends
    162 
--> 163         self._null = self.runtime()
    164 
    165     def runtime(self):

E:\Anaconda\envs\snowflakes\lib\site-packages\talos\scan\Scan.py in runtime(self)
    165     def runtime(self):
    166 
--> 167         self = scan_prepare(self)
    168         self = scan_run(self)

E:\Anaconda\envs\snowflakes\lib\site-packages\talos\scan\scan_prepare.py in scan_prepare(self)
     40 
     41     # create the paramater object and move to self
---> 42     self.paramgrid_object = ParamGrid(self)
     43     self.param_log = self.paramgrid_object.param_log
     44     self.param_grid = self.paramgrid_object.param_grid

E:\Anaconda\envs\snowflakes\lib\site-packages\talos\parameters\ParamGrid.py in __init__(self, main_self)
     20 
     21         # convert the input to useful format
---> 22         self._p = self._param_input_conversion()
     23 
     24         # build the parameter permutation grid

E:\Anaconda\envs\snowflakes\lib\site-packages\talos\parameters\ParamGrid.py in _param_input_conversion(self)
     69                 out[param] = self._param_range(self.main_self.params[param][0],
     70                                                self.main_self.params[param][1],
---> 71                                                self.main_self.params[param][2])
     72             # all other input styles
     73             else:

IndexError: tuple index out of range
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 

I really appreciate it if you can have time to help me out! 
Thank you in advance!

**Comment by mikkokotila** [comment]
Try fixing your parameter dictionary. Right now you are for example declaring: 

`'lr': (0.5, 5)`

But it can't be like that, because the third value is missing. So you could say: 

`'lr': (0.5, 5, 10)`

...which would include 10 different values in the range between 0.5 and 5. When you use tuple input format it is in the form (start, end, no_of_steps). 

Also you have:

`'dropout': (0, 0.1, 0.2),`

...which following the same logic can't work as the last is float and can't be no_of_steps. For batch_size maybe you want to `[100, 500, 1000]` instead of `(100, 500, 1000)`. When you use list in this way, you just include those 3 discrete values.

**Comment by YUIWK** [comment]
Thanks for your quick reply! It worked! 
Obviously, they are rookie mistakes. I must learn more!
Thank you again!

**Comment by mikkokotila** [comment]
Glad to hear it was resolved :) Closing here.

**Comment by YUIWK** [comment]
Yes. I should close it when the problem was resolved. Sorry for that.
Actually, I faced another problem now... 
I am sorry to disturb you again but can you look at the codes and the error for me? I just corrected the places you showed for me and followed the below official standard codes but I could not find any clue. 
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
https://nbviewer.jupyter.org/github/autonomio/talos/blob/master/examples/Hyperparameter%20Optimization%20with%20Keras%20for%20the%20Iris%20Prediction.ipynb
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
But, I found that adding the last code `ta.Scan(x=X, y=Y, params=p, model=SSHP_MPLs)` caused the error.

Here are the codes.
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
import numpy as np
from pandas import read_csv
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import talos as ta
from keras.optimizers import Adam, RMSprop, SGD
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.activations import relu, sigmoid
from talos.model import lr_normalizer, hidden_layers

dataset = open('E:\Data.csv')
dataset = read_csv(dataset)

values = dataset.values
values = np.delete(values, [0], axis=1)
values = values.astype('float32')
print(values.shape)
scaler = MinMaxScaler(feature_range=(0, 1))
values = scaler.fit_transform(values)

print(values.shape)
X, Y = values[:, 0:4], values[:, 5]
print(X.shape, Y.shape)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=False)
print(X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)

def SSHP_MPLs(X_train, Y_train, X_test, Y_test, p):
    model = Sequential()
    model.add(Dense(p['first_neuron'], input_dim=X_train.shape[1], activation=p['activation']))
    model.add(Dropout(p['dropout']))
    hidden_layers(model, p, 1)
    model.add(Dense(Y_train.shape[0], activation=p['last_activation']))

    model.compile(loss='mse', optimizer=p['optimizer'](lr=lr_normalizer(p['lr'], p['optimizer'])),
                  metrics=['mse', 'mae'])
    history = model.fit(X_train, Y_train,
                        validation_data=[X_test, Y_test],
                        batch_size=p['batch_size'],
                        epochs=p['epochs'],
                        verbose=0)
    return history, model

p = {'lr': (0.1, 1, 10),
     'first_neuron': [5, 10, 15],
     'hidden_layers': [1, 2],
     'batch_size': [500, 1000],
     'epochs': [500],
     'dropout': (0, 0.3, 10),
     'optimizer': [Adam, RMSprop, SGD],
     'activation': [relu, sigmoid],
     'last_activation': [relu]}

ta.Scan(x=X, y=Y, params=p, model=SSHP_MPLs)
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 

Here are the output and the error information.
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
(4726, 6)
(4726, 6)
(4726, 4) (4726,)
(3544, 4) (3544,) (1182, 4) (1182,) 

  0%|          | 0/7200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:\Anaconda\envs\snowflakes\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-d8349a6483d7>", line 1, in <module>
    runfile('C:/Users/ookalab/PycharmProjects/untitled2/SSHP.py', wdir='C:/Users/ookalab/PycharmProjects/untitled2')
  File "C:\Users\ookalab\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\183.5153.39\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\ookalab\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\183.5153.39\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/ookalab/PycharmProjects/untitled2/SSHP.py", line 70, in <module>
    ta.Scan(x=X, y=Y, params=p, model=SSHP_MPLs)
  File "E:\Anaconda\envs\snowflakes\lib\site-packages\talos\scan\Scan.py", line 163, in __init__
    self._null = self.runtime()
  File "E:\Anaconda\envs\snowflakes\lib\site-packages\talos\scan\Scan.py", line 168, in runtime
    self = scan_run(self)
  File "E:\Anaconda\envs\snowflakes\lib\site-packages\talos\scan\scan_run.py", line 20, in scan_run
    self = scan_round(self)
  File "E:\Anaconda\envs\snowflakes\lib\site-packages\talos\scan\scan_round.py", line 32, in scan_round
    _hr_out, self.keras_model = ingest_model(self)
  File "E:\Anaconda\envs\snowflakes\lib\site-packages\talos\model\ingest_model.py", line 10, in ingest_model
    self.round_params)
  File "C:/Users/ookalab/PycharmProjects/untitled2/SSHP.py", line 54, in SSHP_MPLs
    verbose=0)
  File "E:\Anaconda\envs\snowflakes\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "E:\Anaconda\envs\snowflakes\lib\site-packages\keras\engine\training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "E:\Anaconda\envs\snowflakes\lib\site-packages\keras\engine\training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_3 to have shape (3308,) but got array with shape (1,)
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 

Thanks for your help in advance!

**Comment by mikkokotila** [comment]
Try changing: 

`model.add(Dense(Y_train.shape[0], activation=p['last_activation']))`

to: 

`model.add(Dense(Y_train.shape[1], activation=p['last_activation']))`

**Comment by mikkokotila** [comment]
Or if it's a binary prediction problem then just use 1 instead (because shape will return error).

**Comment by YUIWK** [comment]
Thanks! I tried to use 1 instead of Y_train.shape[1] and it worked! Using Y_train.shape[1] would return index error. Anyway, thank you for your patience!

**Comment by Gatsby2080** [comment]
results = talos.Scan(x=mat_X_train, y=mat_y_train, 
                     x_val=mat_X_val, y_val=mat_y_val,
                     params=params, 
                     model=lstm_network,
                     experiment_name='grid',
                     reduction_metric='rmspe',
                     minimize_loss=True)
##########
Here are the output and the error information.
AttributeError: 'Scan' object has no attribute 'param_grid'


talos==1.3
