### ISSUE TITLE
Index out of bound crash when using round_limit

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#200]
- [x] I'm up-to-date with the latest release:
 I am running commit 25133d69568e06a6faa6e8071ce32c519e719d4e

- [x] I've confirmed that my Keras model works outside of Talos.
 Yes
-------------------------------------------------------------------------

When running Scan with the round_limit parameter I get the folowing error

        Traceback (most recent call last):
          File "CloudMasking/learn-mask.py", line 534, in <module>
            ,round_limit=1
          File "C:\Python36\lib\site-packages\talos-0.4.6-py3.6.egg\talos\scan\Scan.py", line 163, in __init__
          File "C:\Python36\lib\site-packages\talos-0.4.6-py3.6.egg\talos\scan\Scan.py", line 168, in runtime
          File "C:\Python36\lib\site-packages\talos-0.4.6-py3.6.egg\talos\scan\scan_run.py", line 20, in scan_run
          File "C:\Python36\lib\site-packages\talos-0.4.6-py3.6.egg\talos\scan\scan_round.py", line 20, in scan_round
          File "C:\Python36\lib\site-packages\talos-0.4.6-py3.6.egg\talos\parameters\round_params.py", line 33, in round_params
        IndexError: index 22 is out of bounds for axis 0 with size 1

when running this code

        tt = talos.Scan( x=dummyX
                        ,y=dummyY
                        ,params=params
                        ,model=model
                        ,x_val=testX
                        ,y_val=testY
                        ,print_params=True
                        #,disable_progress_bar=True
                        ,search_method='random'
                        ,reduction_method='spear'
                        ,reduction_interval=15
                        ,reduction_window=30
                        ,round_limit=1
                        )

I have a tenative patch for this that I am testing right now, if this is the right approach feel free to merge my code otherwise do you know what the correct fix should be?

        diff --git a/talos/scan/scan_run.py b/talos/scan/scan_run.py
        index 927fa7f..a743b57 100644
        --- a/talos/scan/scan_run.py
        +++ b/talos/scan/scan_run.py
        @@ -1,5 +1,7 @@
         from tqdm import tqdm
        
        +import random
        +
         from ..utils.results import result_todf, peak_epochs_todf
         from .scan_round import scan_round
         from .scan_finish import scan_finish
        @@ -10,7 +12,9 @@ def scan_run(self):
             onwards from preparation. Manages round_run()'''
        
             # enforce round_limit
        -    self.param_grid = self.param_grid[:self.round_limit]
        +    #self.param_grid = self.param_grid[:self.round_limit]
        +    random.shuffle(self.param_log)
        +    self.param_log=self.param_log[:self.round_limit]
        
             # main loop for the experiment
             # NOTE: the progress bar is also updated on line 73

**Comment by JohanMollevik** [comment]
Is there a reason that round_limit is not handeled right after downsampling in ParamGrid? If moved there it might possibly be rather cleanly integrated into the fix for #201

**Comment by mikkokotila** [comment]
`round_limit` seems to working now from v.0.4.9 onwards. Closing here.
