### ISSUE TITLE
The option clear_tf_session is confusing when using other backends

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#205]
When reading the code it looks like the clear_tf_session option is in fact clearing the keras session regardless of which backend is used, this is a bit confusing if tensorflow is not the selected backend. Should this be renamed?

**Comment by mikkokotila** [comment]
This is related with #190. I agree, we should have be backend agnostic. To my understanding there should not be much in terms of preventing it. 

Do you have familiarity with Theano? i.e. is there a similar command for it?

**Comment by JohanMollevik** [comment]
Not realy, I am using cntk now but have not worked at all with their raw api just the keras abstraction.

**Comment by mikkokotila** [comment]
Closing this at the expense of #206.
