### ISSUE TITLE
Running out of GPU memory (add clear_session for all backends)

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#206]
I'm having an issu where I run out of GPU memory after about 15 tested confgurations. This leads me to belive there is a memmory leak somwhere.

Reading on keras forums a recomended way to solve this is to run

del model

after training (suposedly after saving training results)

Is talos already doing this? If not how can I replicate that as from what I understand talos is keeping a list of tested models to be later inspected from the return value of scan (or are these serialized to avoid them referencing anything).

Any ideas?

**Comment by mikkokotila** [comment]
If you are on Tensorflow, then `Scan(...clear_tf_session=True...)` should address running out of memory after an given number of permutations. 

Yes, we  store the model (serialized as json like) and weights as opposed to storing a model. Then later through various commands, we activate the model as we would after storing it on a disk.

**Comment by JohanMollevik** [comment]
I did som digging and testing

This patch seems to solve/help the problem when using cntk, how it plays with other backends I do not know

    diff --git a/talos/scan/scan_round.py b/talos/scan/scan_round.py
    index 2ed56ac..d11f09f 100644
    --- a/talos/scan/scan_round.py
    +++ b/talos/scan/scan_round.py
    @@ -1,4 +1,5 @@
     from time import strftime, time
    +import gc
    
     from keras import backend as K
    
    @@ -70,6 +71,9 @@ def scan_round(self):
         self.saved_models.append(self.keras_model.to_json())
         self.saved_weights.append(self.keras_model.get_weights())
    
    +    del self.keras_model
    +    gc.collect()
    +
         # clear tensorflow sessions (maybe)
         if self.clear_tf_session is True:
             K.clear_session()

**Comment by mikkokotila** [comment]
Perhaps the current `clear_tf_session` can change its name to 'clear_session' and accepts either None or 'tf', 'theano', and 'cntk' with the corresponding procedures implemented. What do you think?

**Comment by JohanMollevik** [comment]
Sure, that would be more clear. If that is done I think it is rather important to state this clearly in the documentation but as long as that is done it should be a good solution.

**Comment by mikkokotila** [comment]
Would just `del self.keras_model` do the job? At that point it seems safe to delete the model for all cases.

**Comment by JohanMollevik** [comment]
I do not know, I will try starting with that configuration and see if it worked tomorrow

**Comment by JohanMollevik** [comment]
The

del self.keras_model

part seems to be enough

**Comment by JohanMollevik** [comment]
I might have said all clear to early, it failed now, much later that earlier failed runs but failed it did. I will try to re-add the gc.collect() and restart and see if that makes it pass

**Comment by JohanMollevik** [comment]
I reran the test with gc.collect() and now it did not crash, so I think that both are nessecary.

**Comment by mikkokotila** [comment]
Thanks! How much do you know about gc.collect()? 

I know it's brutally effective in addressing memory issues, but is there some possible risk (for example some data changing etc). 

If we are 100% sure there is no risk to system integrity otherwise, I will test `del self.keras_model; gc.collect();` for tensorflow and theano as well and see if there is any memory issue.

**Comment by JohanMollevik** [comment]
I have no experience sadly

From the name of it it sounds very safe but better test than be sorry

**Comment by mikkokotila** [comment]
I'll do some research on this and ask around to get a better understanding of the risks associated with explicit garbage collection on Python.

**Comment by JohanMollevik** [comment]
I have been reading a bit and find no mention of gc.collect being unsafe, what I do find is for exqample the following link whioch explains what it does. https://stackoverflow.com/a/18026125/1666637

Should I make a pull request for this to be included, I have been running this scince I filed the bug with no ill effects

**Comment by mikkokotila** [comment]
Yes, it seems that the only material concern with gc.collect() is performance, which should not be an issue in our case as I'm assuming gc.collect() would not take more than a fraction of the second.

I think we should use the opportunity to make sure that Talos supports all three backends overall. I think there should be no problem with that. Do I understand correct that you are using CNTK?

**Comment by JohanMollevik** [comment]
Yes, no performance hit has been noticable when I have used it.

Yes I'm using CNTK

**Comment by foodspringleroi** [comment]
I ran into the same issue as Johan. His fix works for me :)

**Comment by mikkokotila** [comment]
This is done, so closing here. I recommend moving to v.0.6 for this and many other important improvements. 

`pip install git+https://github.com/autonomio/talos@daily-dev`
