### ISSUE TITLE
Train/Test split in Talos

### ISSUE THREAD

**Issue by franzalex1980** [autonomio/talos#213]
Hi, please I would like to ask; In regards to hyperparameter tuning in talos, can one apply the train test split function from sklearn before loading the data into the keras model, or is the split function carried out automatically inside the model?

Thank you very much and looking forward to your reply!

Alex

**Comment by mikkokotila** [comment]
You don't need to do use sklearn. Talos will handle it for you. But if you want to use sklearn, you can then pass validation data in to Scan() explicitly. See the docstring for reference. 

Closing here. Feel free to open new issue if anything.

**Comment by franzalex1980** [comment]
Thank you so much for your speedy reply, very helpful!
