### ISSUE TITLE
add CONTRIBUTE.md

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/talos#22]
Contributor guidelines are totally missing.

**Comment by x94carbone** [comment]
So after many terribly organized private repos, I have been inspired to think about this in the context of my own personal workflow and also for collaborating. @mikkokotila I'm sure you've also thought about this, but I figured why not have it here as a comment as well. Here's a proposal for the general workflow for a user, inspired by [Vincent Driessen's blog post](https://nvie.com/posts/a-successful-git-branching-model/).

1. Contributor (user) forks `autonomo/talos` to `origin/talos`.
2. user clones `origin/talos` to `local`, sets upstream branch to point to `autonomio/talos` (via `git remote add upstream ...`, where `...` is the address you see when you click on the git clone button on `autonomio/talos`) and then checks out to `dev`.
3. Immediately `git checkout -b my_feature_branch`. All work on a new feature is done on this branch or its children.
4. Bugfixes can be directly implemented on `dev`.
5. When work is done on `my_feature_branch`, user can check out to `local/dev` and ensure `dev` is up to date (`git pull upstream dev`), and then merge on their local branch: `git merge --no-ff my_feature_branch`, resolve any merge conflicts, then `git push origin dev` and open a PR. This PR will be `origin/dev > autonomo/dev`.
6. Resolve any conflicts with PR if any remain, then work is done.

The general rules could be as follows:
- Nobody, even with permission, pushes anything directly to `master`. Anything to be merged into master should be resolved via PR (I think this is good practice).
- Feature updates do not get pushed directly to master (so basically, don't do what my last PR just did). They are only pushed to `dev`.
- When a new release is ready, open a PR `dev > master` to resolve any final bug fixes.
- One more final check before `master > production` to update pypi.
- In principle, the only branches on `autonomio` that should exist in perpetuity are `master`, `dev` and `production`.
- `dev` as stated already, is meant for development and can be kinda a sandbox for resolving conflicts and adding new features.
- `master` is the next level up in development, so while not being in production it should be close to that stage. (**Suggestion:** I think we can do away with the production branch if you want, if we reserve `master` for production).
- `production` is currently the final stage for distributing the package.

Whew that was a lot! Thoughts/did I miss anything here?

**Comment by mikkokotila** [comment]
That's really great :) Thanks, will incorporate from here to the file that is online already.

**Comment by x94carbone** [comment]
My pleasure! Let me know if you'd like me to do anything on this front.

**Comment by mikkokotila** [comment]
This is now done on my dev branch. Should be on dev tomorrow. I've added on CONTRIBUTING.md both blocks as per above under their respective headings. And finished the doc now otherwise. 

Closing.
