### ISSUE TITLE
KeyError: 'val_acc' not in index

### ISSUE THREAD

**Issue by franzalex1980** [autonomio/talos#220]
Hi, I am working with a regression example, whereby the losses and metrics in the keras model were assigned as 'mse' respectively.

When I entered the function 'r.data.head()', it displayed all key informations.

But when I called the function 'r.table().head()', it shows the error below:     

                         KeyError: "['val_acc'] not in index"

Am I missing something here? I have checked in the docstring for regression problems in talos, but couldnt find any.

I would be very grateful for your assistance. Many thanks!

Alex

**Comment by mikkokotila** [comment]
`r.table()` assumes as its default value 'val_acc' but because you are working on a regression problem you don't have 'val_acc'. So you have to `r.table('rmse')` instead (where you replace 'rmse' with whatever metric you are using.

**Comment by franzalex1980** [comment]
Thanks again :)
so, I did like so : r.table('mean_squared_error') and I got what I wanted :D 
Thank you Sir 👍

**Comment by mikkokotila** [comment]
great :)
