### ISSUE TITLE
Values for mean_squared_error

### ISSUE THREAD

**Issue by franzalex1980** [autonomio/talos#221]
Hi again :),

I observed that the mean squared error values are positive, is this correct?, Because in a cross validation score (in scikit) values are negated, taking the least value as the best. 

Secondly, what does 'val_mean_squared_error' represent?  It was reported as one of the indexes. Is this relevant in the graph visualisation just like 'val_acc'.

Many thanks for your support!

**Comment by mikkokotila** [comment]
`val_mean_squared_error` is the validation data MSE. Check out the docstring for the function, and you can see there is an argument there for `ascending` ... make that `True` for loss values. You can follow this throughout Talos.

**Comment by franzalex1980** [comment]
Well understood, thanks lots for the input :)
