### ISSUE TITLE
A way to set experiment_name directly

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#222]
It would be nice to be able to set experiment_name directly and not just by setting it to dataset_name + experiment_no

**Comment by mikkokotila** [comment]
I agree, it's simpler and nothing is lost.

**Comment by JohanMollevik** [comment]
As this is merged should this be closed?

**Comment by mikkokotila** [comment]
I noted that the old approach was still present, so I'll try to clean that up today so we are just left with a single parameter.

**Comment by JohanMollevik** [comment]
That was intentional, I see no harm in allowing options to users.

**Comment by mikkokotila** [comment]
This has been implemented some time back, so closing here.
