### ISSUE TITLE
A way to end the experiment after a certain time

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#225]
It would be neat if we could have a flag to scan where it stops scanning after a certain amount of time.

Sugestion:
Add a parameter latest_start_time which specifies at which time no more iterations should be performed.

So if latest_start_time is 8am tomorrow, it would be ok to start a new iteration at 7.59 but once 8.00 has passed only the current iteration is finished and the results collected.

My use case is that I would like to start an iteration when I will stop working for the day and have it finish before I start the next day or after the weekend. Integrating it in talos prevents the guessing game of how many iterations I have time to run (which must be conservative so I don't have to abort the run and loosing the results).

latest_start_time could be either in minutes or wall clock time or some way of selecting which one.

What do you think? Is this worth to have?

**Comment by mikkokotila** [comment]
It's a great idea. I love it. Maybe this should go together with the way accidentally terminated experiment still yields a result (and can be continued). What do you think?

**Comment by JohanMollevik** [comment]
That sounds reasonable

I would like to add that being able to keep adding even to experiments that was intentionally ended is also usefull, for example if I feel that I need X more premutations to be able to analyze my data being able to add them into the same resulting Scan object would be great.

**Comment by mikkokotila** [comment]
@JohanMollevik Thanks for implementing this. I've changed the name of the `Scan()` parameter to `time_limit` so it's consistent with `round_limit`. The docstring says that it's for setting the time when the last permutation starts.

**Comment by JohanMollevik** [comment]
Excelent

**Comment by JohanMollevik** [comment]
Should we close this as it is already merged?
