### ISSUE TITLE
[daily_dev] shuffle=True causes silent duppliction of parameters

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#226]
Due to a buggy interaction between random.shuffle and numpy arrays shuffle=True silently corrupts data

See this link for a description of the bug
https://www.reddit.com/r/Python/comments/42uqqo/a_nasty_little_bug_involving_random_and_numpy/

Changing the line
import random
in ParamGrid.py
to adding numpys random solves the problem

**Comment by JohanMollevik** [comment]
Pull request https://github.com/autonomio/talos/pull/227

**Comment by mikkokotila** [comment]
Thanks. This is merged, so closing.
