### ISSUE TITLE
Some problems about Reporting() 

### ISSUE THREAD

**Issue by YUIWK** [autonomio/talos#234]
Hello, everyone. I faces three problems when using Reporting().
Could someone help me out?
Thanks for your help in advance! 

**1. The first error 
Code: r.correlate('val_loss')**
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
E:\Anaconda\envs\snowflakes\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3077             try:
-> 3078                 return self._engine.get_loc(key)
   3079             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'val_loss'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-63-a52f2c3061ff> in <module>
      1 # get correlation for hyperparameters against a metric
----> 2 r.correlate('val_loss')

E:\Anaconda\envs\snowflakes\lib\site-packages\talos\commands\reporting.py in correlate(self, metric)
     54         out = self.data[columns]
     55         out.insert(0, metric, self.data[metric])
---> 56         out = out.corr()[metric]
     57 
     58         return out[out != 1]

E:\Anaconda\envs\snowflakes\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2686             return self._getitem_multilevel(key)
   2687         else:
-> 2688             return self._getitem_column(key)
   2689 
   2690     def _getitem_column(self, key):

E:\Anaconda\envs\snowflakes\lib\site-packages\pandas\core\frame.py in _getitem_column(self, key)
   2693         # get column
   2694         if self.columns.is_unique:
-> 2695             return self._get_item_cache(key)
   2696 
   2697         # duplicate columns & possible reduce dimensionality

E:\Anaconda\envs\snowflakes\lib\site-packages\pandas\core\generic.py in _get_item_cache(self, item)
   2487         res = cache.get(item)
   2488         if res is None:
-> 2489             values = self._data.get(item)
   2490             res = self._box_item_values(item, values)
   2491             cache[item] = res

E:\Anaconda\envs\snowflakes\lib\site-packages\pandas\core\internals.py in get(self, item, fastpath)
   4113 
   4114             if not isna(item):
-> 4115                 loc = self.items.get_loc(item)
   4116             else:
   4117                 indexer = np.arange(len(self.items))[isna(self.items)]

E:\Anaconda\envs\snowflakes\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3078                 return self._engine.get_loc(key)
   3079             except KeyError:
-> 3080                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   3081 
   3082         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'val_loss'
---------------------------------------------------------------------------

**2.  The second error 
Code: r.plot_hist(metric='val_loss',bins=10)**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-83-d33dc90bbb2e> in <module>
      1 # a simple histogram
----> 2 r.plot_hist(metric='val_loss',bins=10)

E:\Anaconda\envs\snowflakes\lib\site-packages\talos\commands\reporting.py in plot_hist(self, metric, bins)
     81         '''
     82 
---> 83         return hist(self.data, metric, bins=bins)
     84 
     85     def plot_corr(self, metric='val_acc', color_grades=5):

E:\Anaconda\envs\snowflakes\lib\site-packages\astetik\plots\hist.py in hist(data, x, bins, dropna, vertical, palette, style, dpi, title, sub_title, x_label, y_label, legend, x_scale, y_scale, x_limit, y_limit, save)
    132                      color=palette[0],
    133                      vertical=vertical,
--> 134                      hist_kws=dict(alpha=1))
    135 
    136     # SCALING AND LIMITS

E:\Anaconda\envs\snowflakes\lib\site-packages\seaborn\distributions.py in distplot(a, bins, hist, kde, rug, fit, hist_kws, kde_kws, rug_kws, fit_kws, color, vertical, norm_hist, axlabel, label, ax)
    223         hist_color = hist_kws.pop("color", color)
    224         ax.hist(a, bins, orientation=orientation,
--> 225                 color=hist_color, **hist_kws)
    226         if hist_color != color:
    227             hist_kws["color"] = hist_color

E:\Anaconda\envs\snowflakes\lib\site-packages\matplotlib\__init__.py in inner(ax, data, *args, **kwargs)
   1808                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1809                         RuntimeWarning, stacklevel=2)
-> 1810             return func(ax, *args, **kwargs)
   1811 
   1812         inner.__doc__ = _add_data_doc(inner.__doc__,

E:\Anaconda\envs\snowflakes\lib\site-packages\matplotlib\axes\_axes.py in hist(self, x, bins, range, density, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, normed, **kwargs)
   6563                     "color kwarg must have one color per data set. %d data "
   6564                     "sets and %d colors were provided" % (nx, len(color)))
-> 6565                 raise ValueError(error_message)
   6566 
   6567         # If bins are not specified either explicitly or via range,
ValueError: color kwarg must have one color per data set. 1800 data sets and 1 colors were provided

**3. The third error 
Code: r.plot_corr('val_loss')
Result:**
![image](https://user-images.githubusercontent.com/40563079/53316689-326e7000-390c-11e9-83f7-1409943050b1.png)

**Comment by mikkokotila** [comment]
Do you have 'val_loss' in the data? 

`'val_loss' in list(r.data.columns)`

...should yield `True`. If not, then try one of the metrics you have in your data.

If that does not help, upgrade to the latest version first:

`pip install -U git+https://github.com/autonomio/talos@daily-def`

**Comment by YUIWK** [comment]
Thanks for your reply.
I imported the data from the generated csv file instead of the results from and tried it again and most codes about Reporting() worked! 
But I still got a wired heatmap graph!
![image](https://user-images.githubusercontent.com/40563079/53391381-8c893700-39d9-11e9-9e4e-b6ebcb0d5793.png)

By the way, I installed git and added it into the PATH variable. But I failed to reinstall talos as you said.
Is there a simpler way to install the newest talos?
![image](https://user-images.githubusercontent.com/40563079/53391474-cfe3a580-39d9-11e9-8957-a0997389ac05.png)

**Comment by mikkokotila** [comment]
Ah sorry, I made typo. It should be `daily-dev`.

**Comment by YUIWK** [comment]
Oh, thank you! I made it. And the reason why I got the wired graph I guess is that I used fixed values for epochs, batch size. I think it makes sense.

**Comment by mikkokotila** [comment]
> Oh, thank you! I made it. And the reason why I got the wired graph I guess is that I used fixed values for epochs, batch size. I think it makes sense.

Thanks for clarifying. And yes, for any column where there is only a single unique value, the heatmap would have an empty row.
