### ISSUE TITLE
conv2d layers in AutoModel

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#235]
Is it feasible to integrate adding conv2d layers into KerasModel given that conv1d layers are already there?

**Comment by mikkokotila** [comment]
I looked into this briefly, and noted conv2d takes in a 4d input (conv2d a 3d). So this lead me to think that perhaps KerasModel() could diverge into several (e.g. Model2D, Model3D, and so forth) where each would correspond to a rough use scenario (related with the kind of input data that is available). 

What do you think?

**Comment by JohanMollevik** [comment]
This probably makes sense. If done I think a list of example use cases for each should be created to validate that the model created is a good fit for problems in the real world.

**Comment by saichandrareddy1** [comment]
Is This Talos works for CONV2D with Wrapper class in keras?
is this comfortable with the fit_generator and evaluate_generator?

**Comment by mikkokotila** [comment]
@saichandrareddy1 I don't see why that would be a problem, but this ticket is unrelated. Feel free to open new issue if you like.

**Comment by mikkokotila** [comment]
I think the AutoML capabilities will end up in its own repository eventually.
