### ISSUE TITLE
Saving running time for each permutation to the output

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#236]
It would be great if the runtime of a premutation was saved together with other metrics like loss and accuracy. Right now when I look in the output csv the runtime for each premutation is missing.

**Comment by mikkokotila** [comment]
I agree. In the past I had already taken the time to investigate doing this, and if I remember correctly, the required codes (minus the logging) might already in be place. I'm a big believer in network economics and this is the critical feature in optimizing that respect.

**Comment by JohanMollevik** [comment]
Great

**Comment by mikkokotila** [comment]
The start, end, and duration times for each permutation have been captured all along, but it was not available anywhere. Initially, it will now be available as an attribute in `scan_object.round_times` from where it can be trivially merged with `scan_object.data` for analysis purpose. In the future we can add it directly to the results csv instead (where it belongs). I already have this working on  local.

**Comment by JohanMollevik** [comment]
Excelent, sounds like a plan

**Comment by mikkokotila** [comment]
This is now available in [v1.0](https://github.com/autonomio/talos/tree/1.0). Left the data in `round_times` for legacy, at least for now.

Closing here.
