### ISSUE TITLE
Optimizing hyperparameters for deep reinforcement learning problems

### ISSUE THREAD

**Issue by hanstjua** [autonomio/talos#237]
Unlike conventional machine learning problems, the x and y data for deep reinforcement learning problems keep on changing as the model is being trained. So we have to run the 'fit' function with relatively small number of epochs (in my case approx. 4 - 32 epochs) multiple times to allow the model to learn from the continuously changing x and y data.

Based on my understanding of how talos is used, it means that in order to  optimize my hyperparameters, I have to make multiple calls to the Scan() function (in my case it would be about 15000 times), which I don't think is the most effective way of doing it. Am I missing something here?

P.S. To illustrate what I am talking about, here is a project that is similar to what I am working on
https://github.com/OctThe16th/PPO-Keras/blob/master/Main.py

Specifically, take a look at line 221 onwards. In line 222, the x and y data are updated in every iteration, which are then used to train the 2 networks (actor and critic) at lines 229 and 230 for several epochs for that iteration.

**Comment by JohanMollevik** [comment]
Why do you have to restart the training after every few epochs? Is it not simpler to keep running all the epochs while changing the data during the run? The lather can be acomplished by a generator which talos supports (if a bit awkwardly).

**Comment by hanstjua** [comment]
The reason the training is restarted after every few epochs is because the data for the next round of training are actually generated by the newly trained. I am not very sure how I can use generator to change the training data.

Typically, this is how trainings are done:
1. Generate training data: This is done by generating (and storing) random inputs to be passed into current networks. Then use the predict() function to obtain and store the networks' outputs. The input-output pairs obtained in this step will be used for the upcoming training.
2. Train the networks: Done by running the fit() function with small number of epochs.
3. Generate next batch of training data: Which is basically step 1, but the data is now generated by the newly trained networks. The data used for previous training are to be completely discarded and never used anymore.

Based on these steps, do you think it's possible to use generator to remove the need for calling the fit() function multiple times?

**Comment by JohanMollevik** [comment]
What you can do is the following
If you create a generator by extending keras Sequence you have the following signature to play with

    class Generator(keras.utils.Sequence):
        def __getitem__(self,index): # returns one batch of training data (specified by index) or None at end of epoch
        def __len__(self): # returns number of training batches availible
        def on_epoch_end(self): # called at the end of each epoch

To use this you can set this up so that the current training data is stored in som class local variable at the end of each epoch you get a call to `on_epoch_end` where you can replace the training data with new data. If you need access to the model either pass a reference in before calling fit or store it in some scope accessible from the generator class.

Do you follow?

**Comment by hanstjua** [comment]
I think I understand what you mean. I'll try implementing generator in my code first to see if things will work out.
