### ISSUE TITLE
how to use Predict() to predict Y on new data X without saving ta.Scan

### ISSUE THREAD

**Issue by YUIWK** [autonomio/talos#239]
The issue is that I only save the generated csv file by which we can know val_loss or something for every epoch and select the best model based on val_loss. However, I have no idea to save ta.Scan. When I reload Jupyter Notebook and followed the below website to further check the results, I can only access to the csv file but can not to use Evaluate() or Predict(). Should I rerun the experiment and save ta.Scan or is there a way to solve it? Thanks!

https://nbviewer.jupyter.org/github/autonomio/talos/blob/master/examples/Hyperparameter%20Optimization%20with%20Keras%20for%20the%20Iris%20Prediction.ipynb

**Comment by mikkokotila** [comment]
Yes, you can do `ta.Deploy( ... )` before you wrap up, and then when you come back (or move to another system) you just do `ta.Restore( ... )`. 

Closing here. Feel free to open new issues if anything. Have fun!
