### ISSUE TITLE
Continuous metrics not working

### ISSUE THREAD

**Issue by horeilly** [autonomio/talos#25]
Hi,

When using a continuous metric such as `mse`, `Scan` will throw an error when its `_run` method is called. This happens when it calls `epoch_entropy` from `talos.metrics.entropy` which requires `val_acc` to be in the history dictionary. This only happens if `accuracy` is used as the metric. For example, if the selected metric is `mae`, `val_mean_absolute_error` will be in the history dictionary in place of `val_acc`.

Kind regards,

Harry

**Comment by mikkokotila** [comment]
Thanks for raising this. I should be able to take care of this tomorrow (Wednesday).

**Comment by horeilly** [comment]
Sounds great, thanks!

**Comment by mikkokotila** [comment]
Closing this now. Feel free to open a new one if you still have issues.
