### ISSUE TITLE
talos.Scan() returning UnboundLocalError when running

### ISSUE THREAD

**Issue by nbarrios1337** [autonomio/talos#26]
When running the Scan() method with the following parameters:

`t = talos.Scan(
    x=x, 
    y=y, 
    model=model, 
    params=p, 
    dataset_name="ECG Classifier", 
    experiment_no='10'
)`

and returns the following error:

> The model needs to have Return in format "return history, model"
> ---------------------------------------------------------------------------
> UnboundLocalError                         Traceback (most recent call last)
> <ipython-input-16-b88a13025eb1> in <module>()
>       5     params=p,
>       6     dataset_name="ECG Classifier",
> ----> 7     experiment_no='10'
>       8 )
> 
> ~\Anaconda3\envs\ECG-Research\lib\site-packages\talos\scan.py in __init__(self, x, y, params, dataset_name, experiment_no, model, val_split, shuffle, search_method, save_best_model, reduction_method, reduction_interval, reduction_window, grid_downsample, reduction_metric, talos_log_name, debug)
>      75         self.result = []
>      76         while len(self.param_log) != 0:
> ---> 77             self._null = self._run()
>      78 
>      79         self = result_todf(self)
> 
> ~\Anaconda3\envs\ECG-Research\lib\site-packages\talos\scan.py in _run(self)
>      91             print('The model needs to have Return in format "return history, model"')
>      92 
> ---> 93         self.epoch_entropy.append(epoch_entropy((_hr_out)))
>      94         _hr_out = run_round_results(self, _hr_out)
>      95 
> 
> UnboundLocalError: local variable '_hr_out' referenced before assignment

From what I can tell, the seeming lack of a return method in my model function is triggering the first error, however the model function does have it:

```
def model(x_train, y_train, x_val, y_val, params):
mdl = Sequential()
input_shape = (10*60*fields.get('fs'), 1)

#input
mdl.add(Conv1D(params['input_neuron'], 
               input_shape=input_shape,
               activation=params['activation'],
               kernel_size=(params['kernel_size'],), 
               kernel_regularizer=l2(params['l2_regularizer']),
              )
       )
if params['batch_normalization'] is True:
    mdl.add(BatchNormalization())

mdl.add(MaxPool1D(1))
mdl.add(Dropout(params['dropout']))

hidden_layers(mdl, params['hidden_layers'], params)

mdl.add(Flatten())

#output
mdl.add(Dense(1, 
              kernel_regularizer=l2(params['l2_regularizer']),
              activation=params['last_activation']
             )
       )


mdl.compile(loss=params['losses'],
             optimizer=params['optimizer'](),
             metrics=['accuracy'])

tb_callback = TensorBoard(log_dir='./logs/log80' + str(9) 
                          #+ '/' + str(run_num), write_graph=True, write_images=True
                         )

reduce_lr = ReduceLROnPlateau(monitor='val_loss', 
                              factor=0.2, 
                              patience=5, min_lr=0.001)

history = mdl.fit(x_train, 
        y_train, 
        epochs=params['epochs'], 
        #batch_size=18, 
        verbose=1, 
        validation_data=(x_val, y_val),
        callbacks=
                  [
                      tb_callback, 
                      reduce_lr
                  ]
                 )
#~~~~return method here~~~~
return history, mdl
```

I'm not sure what the second, _hr_out error is pointing out.
As reference, the hidden_layers method just add more layers depending on the respective hyperparameter that I listed in the params dictionary, which looks like:

```
p = {
    'input_neuron':(1,5,1),
    'hidden_layers':(1,4,1),
    'dropout':[p/10 for p in range(0, 6)],
    'optimizer':[Adam, SGD, rmsprop, adagrad],
    'losses':[binary_crossentropy],
    'activation':[relu, elu],
    'last_activation':[sigmoid],
    'kernel_size':(75,175,25),
    'l2_regularizer':[p/10 for p in range(0, 10)],
    'filters':(1,9,1),
    'batch_normalization':[True,False],
    'epochs':(50,250,50)
    }
```

**Comment by x94carbone** [comment]
I have run into this error before and at once point but was never able to quite pin it down. I don't think there's anything wrong with your code. @mikkokotila could this be due to some improper error handling?

**Comment by mikkokotila** [comment]
@x94carbone this is generally a result from the model object not being passed into Talos properly. The most common case is where one forgets to pass it in return, but I can see you are doing it here. What is the dimensionality of the data you are using and is it all floats/ints ... I will replicate in my end and see.

**Comment by nbarrios1337** [comment]
the data (x train and x val) is in a shape of (36, 76800, 1) and the labels are just a 1D array of size 36. The data is a 36 separate 76800-long vectors with each data point an array of length 1, containing a float. The labels are either 0 or 1.

**Comment by mikkokotila** [comment]
@nbarrios1337 thanks. Can you confirm that I got the dimensionality right. I might not have understood it correctly.

```
x = np.empty([36, 76800, 1]).shape
y = np.empty([76800]).shape
```

...do you get the same shape for your x and y?

Additionally, what is this doing:

`input_shape = (10*60*fields.get('fs'), 1)`

**Comment by mikkokotila** [comment]
@nbarrios1337 thanks. 

The culprit is the way you call hidden_layers()

`
hidden_layers(mdl, params['hidden_layers'], params)
`

but it should be: 

`hidden_layers(model, params, last_neuron)`

Note that last_neuron is always the same i.e. these input parameters are the same for every permutation. 

This case is consistent with what I had witnessed in the past; when this message comes, it means that there is an error in the model itself somewhere. 

I've also changed your 'input_neuron' to 'first_neuron' in accord with the current naming in Talos. I've changed this in dev already so in future releases it will be input_neuron in Talos to be consistent with Keras. 

The working code is here for reference:

https://pastebin.com/r28jN6KW

**Comment by nbarrios1337** [comment]
I just realized there may have been some confusion.

I didn't know talos already implemented a hidden layers method. I had actually made my own, that creates convolutional layers.

```
def hidden_layers(mdl, num_layers, params):
    count = 0
    while count <= num_layers:
        mdl.add(Conv1D(params['filters'], 
                       activation=params['activation'],
                       kernel_size=(params['kernel_size'],), 
                       kernel_regularizer=l2(params['l2_regularizer']),
                      )
               )
        if params['batch_normalization'] is True:
            mdl.add(BatchNormalization())
            
        mdl.add(MaxPool1D(1))
        mdl.add(Dropout(params['dropout']))
        
        count = count+1
```

Mimicing the for loop used in the hidden layers method you've implemented in talos, I have:

```
def hidden_layers(mdl, params):
    count = 0
    for i in range(params['hidden_layers']:
        mdl.add(Conv1D(params['filters'], 
                       activation=params['activation'],
                       kernel_size=(params['kernel_size'],), 
                       kernel_regularizer=l2(params['l2_regularizer']),
                      )
               )
        if params['batch_normalization'] is True:
            mdl.add(BatchNormalization())
            
        mdl.add(MaxPool1D(1))
        mdl.add(Dropout(params['dropout']))
        
        count = count+1
```

I've changed the model method to match the new parameters. I'm not sure what you meant to do with the last_neuron parameter.

**Comment by x94carbone** [comment]
Just a hunch: are you certain there's not an error with the model itself? Meaning, independent of Talos, does it compile properly?
