### ISSUE TITLE
Better error message when downsampling results in no permutations

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#261]
Right now if the downsampling results in no premutations, most commonly by the permutation_filter parameter we get an error message

IndexError: single positional indexer is out-of-bounds

This is a bit confusing, a better error message would be nice.

**Comment by mikkokotila** [comment]
Makes sense. This will be handled in the commit that will address #256.

**Comment by mikkokotila** [comment]
Merging this with #326. Closing here.
