### ISSUE TITLE
Per-parameter non-uniform random distributions

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#266]
Possibly a pie in the sky feature but it would be great to have per parameter random likelyhoods.

I'm right now working with a problem where it would make sense to have the low numbers much more likelly but still allow large numbers. (number of hidden conv layers)

Exactly how to work this into the design I'm not clear about but I think it worth keeping in mind.

**Comment by mikkokotila** [comment]
Totally makes sense. This will naturally fall under chances. We just have to figure out how to pass in the weights. Basically it's a weighted random function where we can decide distribution in an arbitrary manner. I think chances would handle things from receiving the distribution weights onwards. In Talos we'd need to figure out how to articulate those weights in a meaningful way given a parameter space.

**Comment by JohanMollevik** [comment]
I think the tricky part will be how to set the distribution per parameter, right now as we are only generating one random number for the entire premutation this is hard to express.
