### ISSUE TITLE
Issue with results heading when on Python 3.5

### ISSUE THREAD

**Issue by tanguycdls** [autonomio/talos#267]
Hi, 
I was running Talos on Python 3.5 and I ran into a small issue : 
In the code results.py you use a dict.keys() method to insert the results into the csv:
`for key in out.history.keys():
        t_t = array(out.history[key])
        # this handles metrics (NOTE: 'acc' have to be in metric name)
        ....`
        
While in Python 3.6 or higher the order of the .keys() method is always the same it's not the case in Python 3.5: it makes the params and score order completely random and impossible to analyze. 
The fix would be either to iterate over the header or simply put a warning while installing Talos. 

Thank you for your amazing work, the library is very good. It's really nice to be able to do hyperparameter optimization natively ! I really like the fact that we don't have to re write all our code to be compatible. 

Best, 
EDIT 
if we replace history.history and params dict by an ordered dict sorted by keys it seems to fix the issue without having to change Python version.

**Comment by mikkokotila** [comment]
Thanks :) 

What do you get with `pip freeze | grep talos` as your Talos version.

**Comment by tanguycdls** [comment]
It's the version from pip, version Talos==0.4.8. 

Thks,

**Comment by mikkokotila** [comment]
This is handled in v.0.6 onwards. This can be accessed through `pip install git+https://github.com/autonomio/talos@dev` at the moment. Closing here.
