### ISSUE TITLE
Disable stringification of the results

### ISSUE THREAD

**Issue by tik0** [autonomio/talos#271]
talos stringifies all results which makes the appending of the history with own statistics and evaluations during scan futile.
In my case, I append numpy arrays and even keras models for further evaluation to the history object.
However, here is an example commit which disables stringification and works with my evaluations: https://github.com/tik0/talos/tree/disable_stringification

I find this feature actually very useful because it is the only way to get user defined objects out of the scan loop.
If this feature is desired, I will elaborate more on that!

**Comment by mikkokotila** [comment]
I think this is related with #272.

The whole logging side of things (results basically) is the next item on the list for a complete rebuild. At the moment it is hackish to say the least. I would like it to be as human readable as possible, that would be the main criteria. As the the whole thing really comes down to accurately logging results (and they way those results are used by reducers etc) in my view it's the single most critical aspect of Talos. All the other critical features feed on it. 

Part of this is unifying the various dataframe attributes in `scan_object` into a single dataframe with the results. Namely learning entropy, round times. 

When you mention storing models, do you know that model for every permutation is stored in `scan_object`. Regarding arrays, can you give an example of what such an array may contain.

**Comment by mikkokotila** [comment]
Logging is now rebuilt. Changes take effect from v.0.6 onwards which now lives in:

`pip install git+http://github.com/autonomio/talos@dev`

Closing here.
