### ISSUE TITLE
Appending index keys in r.table()

### ISSUE THREAD

**Issue by franzalex1980** [autonomio/talos#275]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [ ] I'm up-to-date with the latest release:
    
      pip install -U talos

- [ ] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

-------------------------------------------------------------------------
Hi,

I have an issue with r.table(metric= 'mean_squared_error') displaying only 'mse' result when I also want the 'rmse' appended. Have tried to include rmse alongside the mse in the argument but returns an error. How do I do this pls?

Thanks alot!

**Comment by mikkokotila** [comment]
For `Reporting.table()` you can't do that. It intentionally removes all except the selected metric. You can do the same though through `Reporting.data` as you would otherwise with a pandas dataframe i.e.

`r.data.sort_values('mean_squared_error', ascending=False)`

**Comment by franzalex1980** [comment]
The code worked and can access all key indexes with the ascending argument!

Thanks for the great help and your contribution :)

My permission to close!
