### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by reinert** [autonomio/talos#276]
I'm trying talos in my work where I'm under a ntlm proxy network. Although I have "http_proxy" and "https_proxy" envs set, talos don't recognize them and shows me  the msg: "NO INTERNET CONNECTION: Reporting plots will not work." whenever I import it.

Is there proxy support for talos? How can I configure it?

**Comment by mikkokotila** [comment]
The internet connectivity requirement is removed in [v.0.6](https://github.com/autonomio/talos/tree/params-api-test). So if the internet connectivity problem is an issue for you, I suggest moving to v.0.6 already.  There are other important improvements in it as well.

Closing here.
