### ISSUE TITLE
Manually stop the program and view the result

### ISSUE THREAD

**Issue by AronWater** [autonomio/talos#278]
Sorry, if we set too many parameters , and don't want to wait until a month later to see the result,   Can I use keyboard interrupt(jupyter notebook) to terminate the program,   and use the object return by Scan method, to view the result of hyper parameter that are already searched

**Comment by mikkokotila** [comment]
The results are stored every permutation to a .csv in your present working directory. You can always access it. There are a lot of other things outside of results that are stored in the scan object, those you will not have access to. If you want to just wait a given time, let's say until the next day in the morning 9am, you can set that in `Scan(... max_iteration_start_time ...)`. Note that from v.0.6 onwards this is called `time_limit` consistent with the other limits that are available (or added on v.0.6).
