### ISSUE TITLE
TalosReturnError: Make sure that input model returns 'out, model' where out is history object from model.fit()

### ISSUE THREAD

**Issue by Hyypeer** [autonomio/talos#293]
I get  the error: TalosReturnError: Make sure that input model returns 'out, model' where out is history object from model.fit() 

I have checked  that the input type  for the input in Scan are bumpy arrays. My Part of my code can be seen below : 

def regression_model(X_train, y_train, X_valid, y_valid, params ):
    model = Sequential()
    model.add(Dense(10, input_dim= X_train.shape[1],
                    activation=params['activation'],
                    kernel_initializer='normal'))
    
    model.add(Dropout(params['dropout']))
    
    #hidden_layers(model,params, 1)
    
    model.add(Dense(1, activation=params['last_activation'],
                    kernel_initializer=params['kernel_initializer']))
                    
    model.compile(optimizer=params['optimizer'](lr=lr_normalizer(params['lr'], params['optimizer'])),
                  loss=params['loss'],
                  metrics= mean_squared_error)
    
    history = model.fit(X_train, y_train, 
                        validation_data=[X_valid, y_valid],
                        batch_size=params['batch_size'],
                        callbacks=[live()],
                        epochs=params['epochs'],
                        verbose=0)
    
    return history, model 
    

# then we can go ahead and set the parameter space
params = {'lr': [1],
    'first_neuron':[9],
     'hidden_layers':[0],
     'batch_size': [50],
     'epochs': [4],
     'dropout': [0.1],
     'kernel_initializer': ['normal'],
     'optimizer': [ Adam],
     'loss':[mean_squared_error],
     'activation':[relu],
     'last_activation':['linear']}
     
t = ta.Scan(x=X_CO_train,
            y=y_CO_train,
            model= regression_model, 
            params=params,
            experiment_no='1',
            
             
            print_params=True
            )

I have simplified the number parameters in  the parameter grid.

**Comment by anonymous297** [comment]
I am facing this issue. Please let me know how to resolve
