### ISSUE TITLE
Crashes with Tensorflow2.

### ISSUE THREAD

**Issue by EthanReese** [autonomio/talos#294]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [x] I'm up-to-date with the latest release:
    
      pip install -U talos

- [x] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

`Traceback (most recent call last):
  File "keras_test.py", line 98, in <module>
    dataset_name='MNIST')
  File "/Users/Ethan/venv/lib/python3.7/site-packages/talos/scan/Scan.py", line 170, in __init__
    self._null = self.runtime()
  File "/Users/Ethan/venv/lib/python3.7/site-packages/talos/scan/Scan.py", line 175, in runtime
    self = scan_run(self)
  File "/Users/Ethan/venv/lib/python3.7/site-packages/talos/scan/scan_run.py", line 18, in scan_run
    self = scan_round(self)
  File "/Users/Ethan/venv/lib/python3.7/site-packages/talos/scan/scan_round.py", line 76, in scan_round
    K.clear_session()
  File "/Users/Ethan/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 95, in clear_session
    tf.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'`
-------------------------------------------------------------------------
I found the workaround of commenting out line 76 in scan_round. It works without any issues if that is done.

**Comment by mikkokotila** [comment]
Thanks. Related with #284.

**Comment by mikkokotila** [comment]
A [much improved version of Talos](https://github.com/autonomio/talos/tree/params-api-test) will be released within 2 months or so, and I believe this is already handled in that version (v.0.6). I think the way this will take place is that v.0.6 will officially support TensorFlow 2. I think this is a top priority in terms of the next couple of months. So really great to hear that so far it's just that one thing.

Would you be willing to create an example notebook for using Talos with TensorFlow 2?

**Comment by Braintelligence** [comment]
@mikkokotila Hi there! The issue still seems to persist. Is there any way to make it work with Tensorflow2?

**Comment by stabilus** [comment]
Been trying for two days straight to get the combination of talos, keras, tensorflow on GPU working. Reinstalled nvidia drivers, cuda, cudnn all for tensorflow 2.1, cuda 10.1, cudatoolkit 10.1, all working fine with gpu under keras, until I install talos. then perfect installation gets thrown over, disinstalls of tf 2.0 and keras and other stuff. After all is done, GPU support is gone from environment.

If talos still does not support TF 2.0, could you PLEASE provide a complete list of dependencies and versions of the various modules required for talos to work with GPU support?
