### ISSUE TITLE
Is this a point that can be improved in the setting of random research of talos

### ISSUE THREAD

**Issue by YUIWK** [autonomio/talos#296]
Hello, recently I am reading the book: Deep Learning written by Goodfellow et al. In the 11th chapter, several main methods for hyperparamter tuning is discussed and it is concluded that random research is more efficient than grid research. Here is the point I want to present. Generally, in the section of random research in the book, it says that we generally define a interval for hyperparameters like [a,b] rather than some discrete values {a1, a2, b1, b2}, which can enlarge the search range without additional computational cost. So I want to ask if talos can achieve this. Thanks in advance!

**Comment by mikkokotila** [comment]
Yes, Talos supports "range" of values. Check out the corresponding section in the docs:

https://autonomio.github.io/docs_talos/#parameter-dictionary

**Comment by YUIWK** [comment]
I got it! Thanks for your reply!
