### ISSUE TITLE
NO INTERNET CONNECTION: Reporting plots will not work.

### ISSUE THREAD

**Issue by AchillesJJ** [autonomio/talos#302]
When I `import talos`, I get the following error message after a long waiting time

    NO INTERNET CONNECTION: Reporting plots will not work.

What is the problem ?

**Comment by mikkokotila** [comment]
Do you not have internet connection / are you behind a firewall? 

This issue is removed from [v.0.6](https://github.com/autonomio/talos/tree/params-api-test) onwards, so you might alternatively try that.

**Comment by mikkokotila** [comment]
Closing here. Feel free to open new issue if anything.
