### ISSUE TITLE
Fail to create pixmap with Tk_GetPixmap in TkImgPhotoInstanceSetSize

### ISSUE THREAD

**Issue by Adblu** [autonomio/talos#306]
Windows 10 ( I know ...), pycharm community, python 3.6.

During the test, it throws the error:
```
Fail to create pixmap with Tk_GetPixmap in TkImgPhotoInstanceSetSize
Process finished with exit code -2147483645
```
and stops the simulation.

**Comment by mikkokotila** [comment]
I don't think this has anything to do with Talos though. Windows 10 should be totally ok.

To be safe, can you share your model code.

**Comment by Adblu** [comment]
> I don't think this has anything to do with Talos though. Windows 10 should be totally ok.
> 
> To be safe, can you share your model code.

I suspect it has something to do with the poping out display windows at each iteration. 
Is there any way to disable them ? 

Its frustrating becouse talos allowed to run many iterations and in the middle thats whats happen.

**Comment by mikkokotila** [comment]
When you say "poping out display" do you refer to the live updating graph used in some of the examples? If yes, just remove the callback for that and the problem will go away.

**Comment by Adblu** [comment]
Problem solved :) Thank you

**Comment by lovodkin93** [comment]
I keep getting this problem too. What have you done to solve it? @Adblu

**Comment by Adblu** [comment]
@lovodkin93 Just refer to the @mikkokotila answer.
