### ISSUE TITLE
Test stops everytime that the results are displayed

### ISSUE THREAD

**Issue by antonio-fernandez** [autonomio/talos#309]
the test stops every time that the results are updated in the popup figure (acc, loss, etc). Is it possible to keep running the test without closing the figure's window? I have to close this window manually to keep running the test everytime that it is updated.
I am running the code in a ubuntu 16 machine.

**Comment by mikkokotila** [comment]
Do you refer to the live updating graph? If yes, that is intended to work only on notebook and not console.

**Comment by Adblu** [comment]
Ok, thank you. Problem solved.
