### ISSUE TITLE
first result missing from csv file

### ISSUE THREAD

**Issue by aronwc** [autonomio/talos#31]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [x] I'm up-to-date with the latest release:
    
      pip install -U talos

- [x] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

-------------------------------------------------------------------------

After fixing #30, I noticed that the first result is not saved to the .csv file.

The code [here](https://pastebin.com/vqm3EHpm) gives the following output:
```
Using TensorFlow backend.
2 scans will take roughly 0 seconds
Scan Finished!
csv output has only 2 lines instead of 3
round_epochs,val_loss,val_acc,val_fmeasure,loss,acc,fmeasure,first_neuron,hidden_layers,batch_size,epochs,dropout,kernel_initializer,optimizer,losses,activation,last_activation
 2,0.19118814039648624,0.906432733201144,0.5248427495621798,0.2075809771241854,0.8542713519915863,0.4982654840203386,10,0,30,2,0,uniform,<class 'keras.optimizers.Nadam'>,<function mean_squared_error at 0x10b3162f0>,<function relu at 0x10bc2af28>,<function sigmoid at 0x10bc2d0d0>
```

I believe the culprit is the logic in [results.py:run_round_results](https://github.com/autonomio/talos/blob/master/talos/utils/results.py#L18), which only returns the header if `round_counter==0`. I think it should return both the header and first result, or the logic in `scan.py` has to be changed.

**Comment by mikkokotila** [comment]
Thanks, this makes sense. It is a remnant from the past, and it should be fixed as it may effect use-cases where you do a small number of runs that take a long time.

**Comment by aronwc** [comment]
Hi @mikkokotila:
To be clear, I think this will affect all use cases. The reporting will ignore the first experiment run, which could possibly be the best. It seems high priority, imho.

Otherwise, thanks for a great library!

**Comment by mikkokotila** [comment]
@aronwc I'm glad you enjoy it :)

Sure I understand. What I mean is that generally the workflow involves scanning through hundreds or thousands of options, and at the end of the run you might have 10-20 that are very close to each other. But ok, I get the point that unless we have the result, we can't know (it could be notably better than others)..so I will prioritize this. Most likely tomorrow Friday.

**Comment by aronwc** [comment]
gotcha, thanks!

**Comment by mikkokotila** [comment]
This is now resolved in @dev
