### ISSUE TITLE
Run talos on terminal without notebook

### ISSUE THREAD

**Issue by antonio-fernandez** [autonomio/talos#318]
Hi everyone,

I am having troubles to run Talos from ubuntu terminal using python3. Talos runs for a while, but the memory used keep increasing and the process is killed by the OS after some time. Can someone tell me how can I run Talos without Notebook (just python code)? and how can I disable the pop up update windows that doesn't work from the terminal? 

Thank you

**Comment by BraveDistribution** [comment]
hi @antonio-fernandez,

I don't know why it wouldn't work without jupyter notebook. I am running my code from terminal - it works. 

Can you reproduce it without using talos?

**Comment by mikkokotila** [comment]
That's right, there is no general reason why Talos would not work in terminal.

The issue you are reporting seems to have to do with memory leaking in TensorFlow backend. You should be able to resolve this by reseting the graph.  Until v.0.5 you do it with `Scan( ... clear_tf_session ... )` and from v.0.6 onwards you do it with `Scan( ... clear_session ... )` (support for other backends is possible now).

Closing here. Feel free to open new issue if needed.
