### ISSUE TITLE
early_stopper wrong documentation

### ISSUE THREAD

**Issue by CodeUser777** [autonomio/talos#321]
Hi,
I just was working on a Project with keras and added talos for hyperparameter opimization.
Probably its just my mistake, but I noticed that the documentation (example) of the early_stopper implementation ist wrong. 

out = model.fit(x_train, y_train, batch_size=params['batch_size'], epochs=params['epochs'], verbose=0, validation_data=[x_val, y_val], callbacks=early_stopper(params['epochs'], mode='strict')) ```

https://autonomio.github.io/docs_talos/#probabilistic-reduction 

**correct** is to put the early_stopper call in brackets. 

out = model.fit(x_train, y_train, batch_size=params['batch_size'], epochs=params['epochs'], verbose=0, validation_data=[x_val, y_val], callbacks=**[**early_stopper(params['epochs'], mode='strict') **]**)```

It took me a bit of time to find the problem, that's why I just wanna save someone else some time ;-)

**Comment by mikkokotila** [comment]
Thanks. This is related with #307. 

As we make the move to the next LTS version, which starts from v.0.6 (now available in daily-dev branch), part of it involves ensuring that the documentation is 100% in accord with the software. It might take a little bit of time though. To that end, all kinds of contributions will be most welcome.

**Comment by mikkokotila** [comment]
This is done now, will be in the new docs once it makes to master. Closing here.
