### ISSUE TITLE
Document handling.py

### ISSUE THREAD

**Issue by x94carbone** [autonomio/talos#33]
Needs descriptive doc strings.

**Comment by mikkokotila** [comment]
This seems to be the most confusing part of the code currently, so I've cleaned it up. Basically there are two parts; creating the parameter grid and log (done once), and picking a round configuration (done repeatedly). There is also the third case of reduction, but I'm going to ignore that for now. 

I've created a class ParamGrid which handles the first part. Then for the second part we just have one easy to understand function round_params(). I will document both as part of the process.

**Comment by mikkokotila** [comment]
Ok this is done now and will be included in the next merge I do with dev, which should be tomorrow.
