### ISSUE TITLE
Test and Validation 

### ISSUE THREAD

**Issue by demisak** [autonomio/talos#333]
I'm a beginner student of neural networks and I'm using Talos to
optimize hyperparameters with Keras. I've got confused about
how you split your dataset in train and validation in the example of
Iris dataset. How did you prepare the data to use like arguments in the function like this
def iris_model(x_train, y_train, x_val, y_val, params)?

**Comment by mikkokotila** [comment]
I'm using another Autonomio package, [Wrangle](http://github.com/autonomio/wrangle). 

You can install it first:

`pip install wrangle`

And then you can split your data by:

`x_train, y_train, x_val, y_val = wrangle.array_split(x, y, .3)`

This would split your data 70/30.

**Comment by mikkokotila** [comment]
Also note that you would generally refer to these two datasets you get after the split as "train and validation". 

Closing here. Feel free to open new issue if anything.
