### ISSUE TITLE
matplotlib backend error

### ISSUE THREAD

**Issue by Vikramardham** [autonomio/talos#337]
Hi, I could not find any relevant posts, so I am opening one. Talos works on my jupyter notebook but the exact same code does not work with Jupyter Lab, is this expected behavior? Jupyter Lab throws a weird error with matplotlib backend. Is this expected?

Thanks, in advance!

**Comment by mikkokotila** [comment]
This is not related with Jupyter vs. Jupyter Labs, but on the matplotlib version each use respective in your case. Please post the entire trace as it's otherwise impossible to say more.

**Comment by mikkokotila** [comment]
Closing this. Feel free to open a new issue if anything.
