### ISSUE TITLE
Metrics for binary classification

### ISSUE THREAD

**Issue by tristankr** [autonomio/talos#341]
Why the Talos examples of binary classification with imbalanced dataset like breast cancer uses accuracy for the hyperparameter optimization?

**Comment by mikkokotila** [comment]
The end result is virtually 100%, while the dataset has a notable number of positives. At that point it does not matter. To avoid doubt, in a future example we would not want to use accuracy.

Closing here, as it's really not an issue. Feel free to open a new ticket if anything.
