### ISSUE TITLE
Missing Scan parameters in dev and daily-dev

### ISSUE THREAD

**Issue by jwc905** [autonomio/talos#345]
Issue #339 removed shuffle and grid-downsample as well as other options from the scan constructor.    

Is this functionality removed or is there a new way to access it?   I have an LSTM model with time-series data so I don't want to shuffle the data.

**Comment by mikkokotila** [comment]
Version v.0.6 onwards there are many improvements. One of it is consistent naming among the `Scan` parameters. For example, `grid_downsample` is now named `fraction_limit` but works exactly the same. `shuffle` is still there, and you can set it to False. Perhaps it should be False by default come to think of it.

**Comment by mikkokotila** [comment]
Ah, my bad, shuffle was entirely removed for this very reason in v.0.6. In other words, there is no option for Talos to shuffle your data.

Closing here. Feel free to open new issue if anything.

**Comment by jwc905** [comment]
That seems to work, thanks for the quick response.
