### ISSUE TITLE
Pandas datetools deprecated

### ISSUE THREAD

**Issue by desireevl** [autonomio/talos#346]
pandas.core.datetools has been deprecated since 0.24.0 (January 2019). Perhaps the requirements.txt could reflect the specific version requirement otherwise the code could be changed to no longer use datetools?

**Comment by mikkokotila** [comment]
I believe Talos is not using pandas datetools anywhere. Maybe you are getting the warning from an older version of some of the underlying packages, for example statstools. Can you see if you upgrade statstools on your env, if the warning persists.

**Comment by mikkokotila** [comment]
Closing here as it seems to be unrelated with Talos. Feel free to open new issue if anything.
