### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'

### ISSUE THREAD

**Issue by jwc905** [autonomio/talos#348]
The scan parameter docs say that x and y should be a Numpy ndarray and using that the scan works just fine, but when I try to Deploy I get the following error when trying to save the x and y data to csv.:

AttributeError: 'numpy.ndarray' object has no attribute 'to_csv' 

And of course, ndarray doesn't have a to_csv method,  so I'm confused by the discrepancy.   Is a Pandas Dataframe expected?  If so what format is expected? I've had trouble getting the scan to accept a Dataframe.

Note: I'm currently using the latest daily-dev release of v0.6.1

**Comment by mikkokotila** [comment]
Thanks for flagging this. It is an internal issue in Deploy I was not aware of. Will look into it.

**Comment by mikkokotila** [comment]
Please post the full trace for the error you are getting. Thanks.

**Comment by mikkokotila** [comment]
This is now fixed. Closing here. Thanks again and have a nice new week ahead as well.
