### ISSUE TITLE
MAJOR UPRADE OF TALOS 0.5 LTS to 0.6.2 on Friday 2nd of August, 2019

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/talos#359]
Dear Friends,

For the past several months, much work have gone into the next-generation of Talos, which started from v0.6.0 that was published in `daily-dev` some weeks back. Both v0.6.0 and v0.6.1 will be skipped for `master` and during today 2nd of August, 2019, Talos will move into the new Long Term Support version, which will be available from `master` and within a week or so from pypi as well. 

Support will continue for the previous LTS, which ends at v.0.5.0, which we got to a complete stability over the past 18 months. No new features will added to that version though. It will continue to have it's own branch, and can be installed through its [release package](https://github.com/autonomio/talos/releases/tag/v.0.5) or of course pypi with the corresponding version tag. 

With that, I encourage everyone to move to the new LTS starting from v.0.6.2 at your earliest convenience. We've been using it for some months now, and you get the stability of v.0.5.0 with powerful new features, many new optimizers, and a streamlined architecture that will hopefully encourage many contributions and pull requests. Also there is an all-encompassing new documentation, running on new documentation engine, with clear examples for all common use cases (generators, multi-input, multi-output, etc.). 

Thanks so much for all the support and feedback <3.

**Comment by ktokolwiek** [comment]
Hi, Thanks a lot for this update! Would you need any help releasing the updated version to pypi, or at least add a tag with v.0.6.2, so that we can fix this version as a dependency in requirements, etc.?

**Comment by mikkokotila** [comment]
@ktokolwiek thanks, v0.6.3 is now on PyPi. Actually, pypi build and deploy happens automatically upon merging `master` with `production`. We skipped a couple of versions to get the new LTS into stability first.
