### ISSUE TITLE
In repoting columns is shuffle

### ISSUE THREAD

**Issue by xeonvs** [autonomio/talos#368]
I have an error in the report output and in the best parameters
```
r=ta.Reporting(h)
r.data
r.best_params('val_loss', [],ascending=True)[0]
```
![bug](https://user-images.githubusercontent.com/11463419/62645059-27584b00-b954-11e9-8ee7-3cfd922a6043.PNG)
some columns are shuffle together, of couse when scan is processed, params printing are ok.
`{'kernel_initializer': 'he_uniform', 'dropout': 0.1, 'second_neuron': 92, 'batch_size': 96, 'epochs': 30, 'lr': 0.001, 'first_neuron': 92, 'kernel_regularizer': 0.01, 'optimizer': 'Nadam'`

My code:
```
p = {'first_neuron': [64, 92, 128],
     'second_neuron': [64, 92, 128],
     'batch_size': [64, 96, 128],
     'dropout': [0.0, 0.1, 0.2],
     'lr': [0.01, 0.02, 0.03, 0.001],
     'epochs': [30],
     'kernel_initializer': ['he_uniform', 'he_normal'],
     'kernel_regularizer': [0.1, 0.01],
     'optimizer': ['Adam', 'Nadam']
     }

h = ta.Scan(x=X_train, y=y_train, x_val=X_test, y_val=y_test,
            model=t_model_func,
            experiment_name='lstm_bidir',
            fraction_limit=0.002,
            params=p,
            print_params=True,
            seed=GLOBAL_SEED,
            reduction_method='correlation',
            reduction_interval=1,
            reduction_window=3,
            reduction_threshold=0.2,
            reduction_metric='val_loss',
            minimize_loss=True
            )

```
- [x] I'm up-to-date with the latest release:
    
      pip install -U git+git://github.com/autonomio/talos.git

- [x] I've confirmed that my Keras model works outside of Talos.

-------------------------------------------------------------------------

**Comment by mikkokotila** [comment]
What is your python version?

**Comment by xeonvs** [comment]
In colab.google Python 2.7.15+

**Comment by mikkokotila** [comment]
Talos does not support Python 2.7 as there seems to be no good reason to do it anymore. We used to do it but few months back it was given up. Do you have a particular reason for why you want to use it instead of python3? 

Which Talos version you are using?

Up until Talos v0.5 the tests still incorporate Python2.7 and it passes (but all the new development is focused on v0.6 onwards and v0.5 will not be developed further, but there is support to fix bugs for at least some time still.

**Comment by xeonvs** [comment]
>Do you have a particular reason for why you want to use it instead of python3?
Too many legacy code :(

> Which Talos version you are using?
Latest from git.

Ok, I understand you, I will plan a migration to python3

**Comment by xeonvs** [comment]
In python3 all ok and you can close issue.
Thsnks.

**Comment by mikkokotila** [comment]
That's great :)
