### ISSUE TITLE
Issue template format looks incorrect

### ISSUE THREAD

**Issue by x94carbone** [autonomio/talos#37]
For instance, trying to raise an issue...

<img width="788" alt="screen shot 2018-07-28 at 10 58 04 am" src="https://user-images.githubusercontent.com/26401020/43357823-3b195e4e-9255-11e8-8d7e-0d66687ed34e.png">

I would wager that "How to raise an issue" is not a valid issue format! @mikkokotila I can look into this if you'd like. Let me know what you think.

Note that I've opened this issue by clicking "Open a regular issue"!

**Comment by x94carbone** [comment]
No worries I've never used them either! 👍 

I was thinking exactly that. For instance, one template could be for a bug fix (where we ensure people have the proper version installed, model works outside Talos, etc...). Another could be for a suggestion of a feature (where those checks might not be required). One more for documentation. Etc...

**Comment by mikkokotila** [comment]
Something went wrong this (updated directly to master after making changes to the template). I think it has to do with the way Github.com manages the templates directly from UI (can't use both the Github.com UI way and editing the file way and then committing change). I think it might be best to handle finalizing contribution guidelines and this together (I also need to create FAQ based on the experiences so far...which would be useful for the "question to ask" issue template.

**Comment by x94carbone** [comment]
Sounds good. Let me know if you need any help!

**Comment by mikkokotila** [comment]
You're most welcome to help :) Maybe I can take care of the FAQ one, but I will wait once you have the others up and follow the same procedure as you've used in order to avoid the same I had caused now.

**Comment by mikkokotila** [comment]
This was fixed, so closing. Thanks!
