### ISSUE TITLE
Tuning mixed inputs models are failing 

### ISSUE THREAD

**Issue by MustafaKhalil-IST** [autonomio/talos#373]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [x] I'm up-to-date with the latest release:
    
      pip install -U talos

- [x] I've confirmed that my Keras model works outside of Talos.

In mixed models with a concatenate layer, the inputs are passed as a list of the np arrays of the various inputs, for instance, if we have input with images and texts, each one will be passed as an element in the list , eg., [X_images, X_texts], as the model has two inputs layer for each one, this is failing due to this error:

File venv/lib/python3.7/site-packages/talos/scan/scan_prepare.py", line 55, in scan_prepare
    self.shape = [self.x.shape, self.y.shape]
AttributeError: 'list' object has no attribute 'shape'

**Comment by mikkokotila** [comment]
Can you install the latest version:

`pip install git+https://github.com/autonomio/talos`

...and your problem should go away.

**Comment by mikkokotila** [comment]
This should not be an issue in the latest version, so assuming it as resolved. Feel free to open a new issue if anything.
