### ISSUE TITLE
Should we implement Python 2 backwards compatibility?

### ISSUE THREAD

**Issue by x94carbone** [autonomio/talos#38]
Although it is true that Python 3 is slowly becoming the new standard (at least in my experience), lots of people still use Python 2. Is there anything in the code here that might not be backwards compatible? Keras is compatible with at worst 2.7.

Note this might be as simple as requesting that Travis build with Python 2.7 and then just debugging from a forked origin/dev branch.

**Comment by x94carbone** [comment]
Let me know what happens! Also could you elaborate a bit on this?

>  I've removed 3.4 and 3.5 because of the build failure that comes from Travis due to being able to deploy just once per version to pypi

I'm sorry I just don't know enough about Travis. Specifically what do you mean about Travis being able to deploy once per version? Thanks!

**Comment by mikkokotila** [comment]
3.7 is not available on Travis looks like, and 2.7 fails on the Cervical Cancer test where spear_reducer() is used. Gives pandas KeyError on val_acc...I'll look into what's causing this...but in other words looks good. 

For Travis there is travis.yml where we can simply add the versions of python we want to test with. Then travis will run the procedures for all those versions we list separately. It's very convenient :)

**Comment by mikkokotila** [comment]
@x94carbone ...by the way are you getting all the build fail notices from the dev-mikko branch to your email?

**Comment by mikkokotila** [comment]
Ok it's resolved now. All tests passing for Python versions:

- 2.7
- 3.4
- 3.5
- 3.6

The corresponding Travis build report [here](https://travis-ci.org/autonomio/talos/builds/409327989).

I will do some QA tomorrow and get it merged with dev. Closing.
