### ISSUE TITLE
Add multi_gpu support to AutoModel

### ISSUE THREAD

**Issue by beeb** [autonomio/talos#381]
Everything is in the title! Would be lovely to be able to add a number of GPUs to use with AutoML / AutoModel.

Thanks!

**Comment by mikkokotila** [comment]
Makes total sense, will be added :)

**Comment by beeb** [comment]
When you try to use keras' `multi_gpu_model` you might find that it gives an Exception 'TypeError: object of type 'NoneType' has no len()` regarding `model.outputs`.

Searching for a solution on SO I found [this](https://stackoverflow.com/questions/53231168/how-to-use-keras-utils-multi-gpu-model-with-custom-subclassed-keras-models).

Hope you can find a solution!

**Comment by beeb** [comment]
Oh actually I managed to fix it by specifying an input shape for all network types. That's all that was missing. See my second SO link in the reply above.
