### ISSUE TITLE
ImportError: cannot import name 'live'

### ISSUE THREAD

**Issue by shivamgupta7** [autonomio/talos#382]
Hi, I have installed the talos by doing :
pip install -U talos
The installation is done successfully. But every time I do :
import talos as ta
from talos import live

I got an error :
ImportError                               Traceback (most recent call last)
<ipython-input-10-805ae8483169> in <module>()
      1 import talos as ta
----> 2 from talos import live

ImportError: cannot import name 'live'

**Comment by mikkokotila** [comment]
Try instead: 

`from talos.utils import live` 

or just call it directly after importing talos:

`talos.utils.live()`

I guess you are referencing to one of the examples (due for update).

**Comment by shivamgupta7** [comment]
Thank you.

**Comment by mikkokotila** [comment]
The [docs](https://autonomio.github.io/talos/#/) are actually up-to-date and there are many examples, but yea, the notebooks have to be brought to up-to-date.

**Comment by jtlz2** [comment]
@mikkokotila https://autonomio.github.io/docs_talos/#monitoring is not up-to-date..?

**Comment by CarlosDLMC** [comment]
Hi!
I actually am having the same problem, 
 from talos import live
is returning an error as well.

The solution you proposed (from talos.utils import live) or (talos.utils.live()) is not working anymore.
Please, can you tell me how to solve this issue?
Also, this import
from talos.metrics.keras_metrics import fmeasure_acc
is returning an error.

Thanks for your help!

**Comment by david-cros** [comment]
@CarlosDLMC Hello. Did you find a solution ? I have the same problem as you. Thanks. David

**Comment by CarlosDLMC** [comment]
Hi @david-cros , actually I just did a downgrade to an older version and it worked for me.
