### ISSUE TITLE
Metric name is hardcoded in scan_object.evaluate_models()

### ISSUE THREAD

**Issue by beeb** [autonomio/talos#385]
As seen on [this line](https://github.com/autonomio/talos/blob/efb1c6640fb9c90cc3535ed1c5639dbfadfc97b3/talos/scan/scan_addon.py#L94) and the next, the `evaluate_models` method adds the columns `eval_f1score_mean` and `eval_f1score_std` in all cases, even when the used metric is different from f1score (e.g. for "continuous" tasks)

**Comment by mikkokotila** [comment]
Somehow I totally missed this. Thanks. Will try to sort it out today.
