### ISSUE TITLE
"TypeError: constructor returned NULL" on Raspberry pi

### ISSUE THREAD

**Issue by freezly** [autonomio/talos#393]
#### 1) Confirm the below

- [x] My Python version is 3.5 or higher
- [x] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [x] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__`
not possible, because of import issue. pip3 list gives me: talos (0.6.3)

#### 3) Explain clearly what you expect to happen
Running talos via ssh or cronjob on a UI-less linux server and raspberry pi's

#### 4) Explain what actually happened
My code runs fine under Kubuntu 18.04. I want to run the same code and model on a raspberry pi and I'm connected via SSH. On Raspi I get an error as soon "import talos as ta" is called:

`Unable to init server: Could not connect: Connection refused
Unable to init server: Verbindung ist gescheitert:Connection refused

(predictor.py:18596): Gdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
File "/home/pi/git/repo/predictor.py", line 2, in
import talos as ta
File "/home/pi/.local/lib/python3.5/site-packages/talos/init.py", line 14, in
from . import utils
File "/home/pi/.local/lib/python3.5/site-packages/talos/utils/init.py", line 3, in
from kerasplotlib import TrainingLog as live
File "/home/pi/.local/lib/python3.5/site-packages/kerasplotlib/init.py", line 1, in
from kerasplotlib.traininglog import TrainingLog
File "/home/pi/.local/lib/python3.5/site-packages/kerasplotlib/traininglog.py", line 5, in
import matplotlib.pyplot as plt
File "/home/pi/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 115, in
_backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
File "/home/pi/.local/lib/python3.5/site-packages/matplotlib/backends/init.py", line 62, in pylab_setup
[backend_name], 0)
File "/home/pi/.local/lib/python3.5/site-packages/matplotlib/backends/backend_gtk3agg.py", line 9, in
from . import backend_agg, backend_gtk3
File "/home/pi/.local/lib/python3.5/site-packages/matplotlib/backends/backend_gtk3.py", line 32, in
cursors.MOVE : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL`

Seems this is a problem like this: https://stackoverflow.com/questions/31328436/typeerror-constructor-returned-null-while-importing-pyplot-in-ssh

Is talos build to run on servers or only on PC's with an UI?

#### 5) Provide a code-complete reference
1. run on raspberry pi: python3
2. send to python console: import talos as ta
3. Error happens

- [ ] My bug report includes an input model
- [ ] My bug report includes a parameter dictionary
- [ ] My bug report includes a `Scan()` command
- [ ] My bug report question includes a link to a sample of the data

NOTE: If the data is sensitive and can't be shared, [create dummy data](https://scikit-learn.org/stable/modules/classes.html#samples-generator) that mimics it.

**A self-contained Jupyter Notebook, Google Colab, or similar is highly preferred and will speed up helping you with your issue.**

-------------------------------------------------------------------------

**Comment by mikkokotila** [comment]
`os.environ["DISPLAY"]` does not return anything in osx, so I assume similar case will happen in some other distros as well. Closing this as resolving it would go quite far from the focus of Talos. Good that you found a workaround. 

This does raise an important question that have been lurking there all the while; does it really make sense to carry over all the baggage from `matplotlib` to Talos. Answer is that probably not.
