### ISSUE TITLE
word embeddings fail (fixed)

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/talos#41]
On line 232 in Scan() there is the command `K.clear_session()` which as far as I remember is there only for the sake of dealing with the memory leakage problem in old versions of TensorFlow. Using this is not possible to use word embeddings, so I've removed it and embeddings work just fine. 

The other thing is that I'm passing the embeddings as a parameter, which is kind of useful as it allows trying several different embeddings. 

This is fixed in dev today I think.

**Comment by aliceO1993** [comment]
What is the correct way to input an embedding matrix as an input parameter?

**Comment by mikkokotila** [comment]
You can do it exactly the way you would do it in a stand-alone Keras model. You don't need to change anything. Note that the model you input to Talos should not include loading pre-trained emebeddings (but that should be done before starting the experiment just once).
