### ISSUE TITLE
How to use multiple inputs in a Keras model with Talos?

### ISSUE THREAD

**Issue by peoky** [autonomio/talos#419]
There is ambiguity in using Talos for multiple inputs, which one is correct?

1. https://autonomio.github.io/talos/#/Examples_Multiple_Inputs
2. https://autonomio.github.io/talos/#/Scan?id=scan-arguments (Models with multiple inputs or outputs (list of arrays))

Also, why do i get the following error after running scan_object:
__init__() takes at least 6 arguments (7 given)

`
scan_object = talos.Scan(x = [x_train[:, 0], x_train[:, 1]],
                         y = tr_y,
                         x_val = [x_val[:, 0], x_val[:, 1]],
                         y_val = val_y,
                         params = p,
                         model = siamese_model)
`

**Comment by mikkokotila** [comment]
What do you mean by ambiguity? The docs provide a self-contained example for multiple input models. 

Try the below (you are missing `experiment_name`):

```
scan_object = talos.Scan(
    
    x=[x_train[:, 0], x_train[:, 1]], 
    y=tr_y, 
    x_val=[x_val[:, 0], x_val[:, 1]], 
    y_val=val_y, 
    params=p, 
    model=siamese_model,
    experiment_name='my_experiment'

)
```

**Comment by peoky** [comment]
Many thanks for the prompt reply.
According to '1', the multi-input part is handled in Scan():

```python
out = model.fit(x=x_train,
                    y=y_train,
                    validation_data=[x_val, y_val],
                    epochs=150,
                    batch_size=params['batch_size'],
                    verbose=0)

scan_object = talos.Scan(x=[x_train, x_train],
                         y=y_train,
                         x_val=[x_val, x_val],
                         y_val=y_val,
                         params=p,
                         model=iris_multi)
```

 but according to '2', the multi-input part is handled in Fit():

```python
out = model.fit(x=[x_train_a, x_train_b],
                y=y_train,
                validation_data=[[x_val_a, x_val_b], y_val])
```

**Comment by mikkokotila** [comment]
It's better to follow [1](https://autonomio.github.io/talos/#/Examples_Multiple_Inputs) because that will be consistent across all kinds of use-cases and also because it is the actual specific example targeting [multi-input model](https://autonomio.github.io/talos/#/Examples_Multiple_Inputs)

**Comment by peoky** [comment]
Many thanks for your help. I got my code working.
