### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by mehmettan** [autonomio/talos#42]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [x] I'm up-to-date with the latest release:
    
      pip install -U talos

- [x] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

-------------------------------------------------------------------------

    If I am not making a mistake, the current example does not fit with the latest version. Can you please update the documentation on calling Scan?

Thank you,

import talos as ta
h = ta.Scan(X, Y, params=p, experiment_name='first_test', model=drug2gene_model, grid_downsample=0.5)

TypeError                                 Traceback (most recent call last)
<ipython-input-18-c861c353fd73> in <module>()
      1 import talos as ta
----> 2 h = ta.Scan(X, Y, params=p, experiment_name='first_test', model=drug2gene_model, grid_downsample=0.5)

TypeError: __init__() got an unexpected keyword argument 'experiment_name'

**Comment by mikkokotila** [comment]
That's true. I will update the examples. Now you have to use: 

```
h = ta.Scan(x, y, 
                    params=p,
                    dataset_name=icu_stays, 
                    experiment_no='2', 
                    model=icu_stays, 
                    grid_downsample=0.1)
```

**Comment by mikkokotila** [comment]
Ok done. This will be updated in the next merge to Master. Thanks for flagging it. 

Closing here.
