### ISSUE TITLE
Column names in Analyze object do not match

### ISSUE THREAD

**Issue by christophgm** [autonomio/talos#425]
---sorry I closed the previous same-named issue by mistake ---still open

Hello,  just recognised that the Analyze object's column names do not match the content of the params dictionary...see the examples below:  I've ran an experiment with the following params:  

p = {'optimizer': [Adam, Adamax, Nadam, Adagrad, Adadelta], 'first_neuron': [5120, 1024, 512, 128, 64, 32, 16], 'batch_size': [100, 1000, 5000, 10000], 'epochs': [25], 'hidden_neuron':[1024, 512, 128, 64, 32, 16, 8, 4, 2], 'hidden_layers':[0, 1, 2, 3, 4], 'kernel_initializer': ['uniform', 'normal', 'glorot_uniform'], 'dropout': [0.0, 0.25, 0.5, 0.65, 2, 3, 4, 5, 10], 'losses': ["mape", "mse"], 'shapes': ['brick', 'triangle', 'funnel'], 'activation': ['relu'], 'lr': [0.0001, 0.0002, 0.0005, 0.0009, 0.001, 0.002, 0.005, 0.009, 0.01, 0.02, 0.035, 0.05, 0.075, 0.09, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9] } 

 After finishing and analyzing the resulting csv file as an analyze object, I get the following result:  
dir = "TalosPipeline1/" 
file = "101919222627.csv" 
t = talos.Reporting(dir + file) 
t2 = talos.Analyze(t) 
t2.data.head()  

As you see in the image below, e.g. the optimizier column is showing floats and the first_neuron column is showing functions.  Am I doing something wrong or is this a bug?  

![image](https://user-images.githubusercontent.com/33901701/67190612-888aa900-f3f0-11e9-84f9-f4107f19deb3.png)

additional comment: Maybe the screenshot below helps...it seems that the dataframe has the exact same order, as the param print out while running. But alphabetically ordered column names.

I tried to read through your code concerning the paramter setting, but I couldn't find the place, where this happens.

Maybe somebody can?!

![image](https://user-images.githubusercontent.com/33901701/67190670-a6f0a480-f3f0-11e9-84d6-af4768596069.png)

thanks and br 

 christoph

**Comment by mikkokotila** [comment]
Can you do: 

```
import talos
talos.__version__

```

What do you get?

**Comment by christophgm** [comment]
'0.6.3'

**Comment by mikkokotila** [comment]
Related with #439

**Comment by christophgm** [comment]
thanks...it's working now!
