### ISSUE TITLE
TypeError: __call__() takes 2 positional arguments but 6 were given

### ISSUE THREAD

**Issue by Dishant-P** [autonomio/talos#430]
I am trying to tune hyperparameters of a custom keras model, but always get this error. Below is the param_grid I am using:
p = {'lr': (0.5, 5, 10),
     'first_neuron':[4, 8, 16, 32, 64],
     'hidden_layers':[0, 1, 2],
     'batch_size': (10,30,64,128,256),
     'epochs': [10,20,40,80,200,500],
     'dropout': (0, 0.5, 5),
     'weight_regulizer':[None],
     'emb_output_dims': [None],
     'shape':['brick','long_funnel'],
     'optimizer': ['Adam', 'Nadam', 'RMSprop'],
     'losses': ['logcosh', 'binary_crossentropy'],
     'activation':['relu', 'elu'],
     'last_activation': ['sigmoid']}

**Comment by mikkokotila** [comment]
Can you share the actual code you are trying to execute.

**Comment by Dishant-P** [comment]
The error didn't persist, it was just due to a problem with the parameters written, it follows with an index out of range error, but it was solved using the other thread that has already been discussed upon. Thanks anyway.
