### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType objec

### ISSUE THREAD

**Issue by inanoxTM** [autonomio/talos#431]
#### 1) Confirm the below

- [x] My Python version is 3.5 or higher
- [x] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [x] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__` : '0.6.3'

#### 3) Explain clearly what you expect to happen

I am trying to optimize a model using tensorflow 2.0, the first training does well, but at the beginning of the second I get the error: TypeError: cannot unpack non-iterable NoneType object

#### 4) Explain what actually happened

TypeError: cannot unpack non-iterable NoneType objec using Tensorflow 2.0 

#### 5) Provide a code-complete reference

p = {
    'L2_reg' : [0.001,0.01],    
    'batch_size': [100],
    'lstm_cells1':[100,200,400],
     'lr':[0.001]}

x_train = [cnn_train, ann_train]
x_dev = [cnn_dev, ann_dev]

scan_object = talos.Scan(x=x_train,
                         y=y_train,
                         x_val=x_dev,
                         y_val=y_dev,
                         params=p,
                         model=build_model,
                         experiment_name='CPU')

---

**Comment by mikkokotila** [comment]
Can you give the whole trace.

**Comment by mikkokotila** [comment]
Closing this as stale.
