### ISSUE TITLE
    self.epoch_entropy.append(epoch_entropy((_hr_out)))  UnboundLocalError: local variable '_hr_out' referenced before assignment

### ISSUE THREAD

**Issue by AswinkarthikeyenAK** [autonomio/talos#44]
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [x] I'm up-to-date with the latest release:
    
      pip install -U talos

- [x] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

-------------------------------------------------------------------------
Hey, I am new to python and programming just trying to learn autoencoders. I am trying to optimize my denoising autoencoder. But i am getting this error.
    self.epoch_entropy.append(epoch_entropy((_hr_out)))

UnboundLocalError: local variable '_hr_out' referenced before assignment.

Cant figure out what needs to be done.
The code i am using is:
x_train_analytical, x_test_analytical = train_test_split(   data_analytical,
                                                            test_size=0.20, 
                                                            random_state=15)
x_train_experimental, x_test_experiment = train_test_split(    data_experiment,
                                                               test_size=0.20, 
                                                               random_state=15)

def AE(x_train_analytical,x_train_experimental,x_test_analytical,x_test_experiment,params):
#Denoising Autoencoder
    regulariser_value = 0.00015
    Input_Experiment = Input(x_train_analytical.shape[1])
    
    encoded = Dense((params['first_neuron']), activation = params['activation'],
                    activity_regularizer=regularizers.l1(regulariser_value))(Input_Experiment)
    
    decoded = Dense(500, activation=params['last_activation'])(encoded)
    
    autoencoder = Model(Input_Experiment, decoded)
    
    encoder = Model(Input_Experiment, encoded)
    
    encoded_input = Input(shape=(encoding_dim,))
    decoder_layer = autoencoder.layers[-1]
    
    decoder = Model(encoded_input, decoder_layer(encoded_input))
    
    
    model.compile(optimizer='adadelta', loss='mean_squared_error', metrics = ['acc'])
    
    from keras import callbacks
    callback = callbacks.TensorBoard(log_dir=r'xxxxxxxxxxxxxxxx/xxxxxxxxxxx', 
                                           histogram_freq=0, 
                                           write_graph=True, 
                                           write_images=True)
    
    history = model.fit(x_train_analytical,x_train_experimental, epochs=params['epochs'],
                                           batch_size = params['batch_size'], 
                                           shuffle = True,
                                           validation_data=(x_test_analytical,x_test_experiment),
                                           callbacks=[callback])
    
    return history, model

t = ta.Scan(x = x_train_analytical, y = x_train_experimental,
            model = AE, grid_downsample = 0.01, 
            params = p, dataset_name ='model_data' , experiment_no='1', shuffle = False )

Can anyone help me out in ?

**Comment by mikkokotila** [comment]
Can you share the whole trace (the list of messages where the error appears) for the error.

**Comment by AswinkarthikeyenAK** [comment]
Traceback (most recent call last):

  File "<ipython-input-64-9e189a32cb67>", line 3, in <module>
    params = p, dataset_name ='model_data' , experiment_no='1', shuffle = False )

  File "C:\ProgramData\Anaconda3\lib\site-packages\talos\scan.py", line 77, in __init__
    self._null = self._run()

  File "C:\ProgramData\Anaconda3\lib\site-packages\talos\scan.py", line 93, in _run
    self.epoch_entropy.append(epoch_entropy((_hr_out)))

UnboundLocalError: local variable '_hr_out' referenced before assignment

**Comment by mikkokotila** [comment]
Thanks. Can you try the latest version: 

```
pip uninstall talos 
pip install git+https://github.com/autonomio/talos.git@dev
```
You might still get the error after this, but it should be more descriptive and will help to identify what exactly it's wrong (it seems that there some issue in your model). The error message that says _hr_out is referenced before assignment means that 10 times out of 10.

**Comment by AswinkarthikeyenAK** [comment]
Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/autonomio/talos.git C:\Users\xxxxxx\AppData\Local\Temp\pip-req-build-7542c4l0
Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by mikkokotila** [comment]
how did you install Talos initially on your system?

**Comment by AswinkarthikeyenAK** [comment]
Anaconda prompt. 
pip install talos

**Comment by mikkokotila** [comment]
can you do 

`conda install git `

and then try again.

**Comment by AswinkarthikeyenAK** [comment]
Thanks a lot. It worked now.
I ran the program again.
t = ta.Scan(x = x_train_analytical, y = x_train_experimental,
            model = AE, grid_downsample = 0.01, 
            params = p, dataset_name ='model_data' , experiment_no='1', shuffle = False )
Traceback (most recent call last):

  File "<ipython-input-7-9e189a32cb67>", line 3, in <module>
    params = p, dataset_name ='model_data' , experiment_no='1', shuffle = False )

  File "C:\ProgramData\Anaconda3\lib\site-packages\talos\scan.py", line 195, in __init__
    self._null = self._run()

  File "C:\ProgramData\Anaconda3\lib\site-packages\talos\scan.py", line 208, in _run
    _hr_out, self.keras_model = self._model()

  File "C:\ProgramData\Anaconda3\lib\site-packages\talos\scan.py", line 239, in _model
    self.params)

  File "<ipython-input-6-a5515f6ab517>", line 8, in AE
    activity_regularizer=regularizers.l1(regulariser_value))(Input_Experiment)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\core.py", line 861, in build
    constraint=self.kernel_constraint)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\initializers.py", line 209, in __call__
    scale /= max(1., float(fan_in + fan_out) / 2)

TypeError: unsupported operand type(s) for +: 'int' and 'numpy.str_'

**Comment by AswinkarthikeyenAK** [comment]
-FYI,

This was the working code which I tried to wrap it with talos.
 #Denoising Autoencoder

Input_Experiment = Input(shape=(500,))

encoded = Dense(encoding_dim, activation = activation_function_1,
                activity_regularizer=regularizers.l1(regulariser_value))(Input_Experiment)

decoded = Dense(500, activation='tanh')(encoded)

autoencoder = Model(Input_Experiment, decoded)

encoder = Model(Input_Experiment, encoded)

encoded_input = Input(shape=(encoding_dim,))
decoder_layer = autoencoder.layers[-1]

decoder = Model(encoded_input, decoder_layer(encoded_input))


autoencoder.compile(optimizer='adadelta', loss='mean_squared_error')

from keras import callbacks
callback = callbacks.TensorBoard(log_dir=r'C:\Tensor Logs', 
                                       histogram_freq=0, 
                                       write_graph=True, 
                                       write_images=True)

autoencoder_anm_data = autoencoder.fit(x_train_ANM,x_train_EXP, epochs=epoch,
                                       batch_size = batch, shuffle = True,
                                       validation_data=(x_test_ANM,x_test_EXP),
                                       callbacks=[callback])
Data Shape.
It is a time series data with each row containing 500 time stamps
x_train_ANM = [1199,500]
x_train_EXP = [1199,500]

**Comment by mikkokotila** [comment]
The issue in your model seems to be here: 

`File "", line 8, in AE
activity_regularizer=regularizers.l1(regulariser_value))(Input_Experiment)`

Maybe you can try without that line and see what happens (as that's what's causing the error).

**Comment by x94carbone** [comment]
This is resolved in the latest version of master, correct @mikkokotila?

**Comment by mikkokotila** [comment]
@x94carbone the error message yes, we no longer swallow the actual error message. Closing here.
