### ISSUE TITLE
RuntimeError: You must compile your model before training/testing

### ISSUE THREAD

**Issue by SamBelkacem** [autonomio/talos#441]
ta.__version__  : 0.6.3

I'm using **Talos** and Google colab **TPU** to run hyperparameter tuning of a **Keras** model.

# Function to create and compile the **Keras** model

```
def create_model(x_train, y_train, x_val, y_val, params):
    # Specify a distributed strategy to use TPU
    resolver = tf.contrib.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
    tf.contrib.distribute.initialize_tpu_system(resolver)
    strategy = tf.contrib.distribute.TPUStrategy(resolver)

    # Use the distributed strategy to create and compile a Keras model
    with strategy.scope():
      deep_model = Sequential()
      deep_model.add(Dense(16, input_shape=(16,), activation=tf.nn.relu, name="relu"))
      deep_model.add(Dense(1, activation=tf.nn.sigmoid, name="sigmoid"))
      optimizer = SGD(lr=params['learn_rate'], momentum=params['momentum'])
      deep_model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
  
    # Convert data type to use TPU  
    x_train = x_train.astype('float32')
    x_val = x_val.astype('float32')
    y_train = y_train.astype('int32')
    y_val = y_val.astype('int32')

    # Fit the Keras model on the dataset
    steps_per_epoch = int(np.ceil(x_train.shape[0] / params['batch_size'])) - 1
    out = deep_model.fit(x_train, y_train, batch_size=params['batch_size'], epochs=params['epochs'], validation_data=[x_val, y_val], verbose=0, steps_per_epoch=steps_per_epoch)

    # Return the history output and the Keras model
    return out, deep_model
```

# Create a parameter distributions:

```
p = {'batch_size': [512, 1024],
        'epochs': [10],
        'learn_rate': [0.1, 0.2, 0.3],
        'momentum': [0.2, 0.4, 0.6]}    
```

# Scan the best hyperparameters of the Keras model

`scan_results = ta.Scan(x_train, y_train, params=p, model=create_model, experiment_name='exp', x_val=x_val, y_val=y_val)`

# Best model  with the highest categorical accuracy

```
R = ta.Reporting(max(glob.glob('exp/*.csv'), key=os.path.getctime))
print(R.best_params(metric='val_acc', exclude=[]))
model_id = scan_results.data['val_acc'].astype('float').argmax() - 1
model = model_from_json(scan_results.saved_models[model_id])
model.set_weights(scan_results.saved_weights[model_id])
```

# Everything works till here. However, I get this error when I retrain the model

`model.fit(x_train, y_train)`

**RuntimeError:** You must compile your model before training/testing

**Comment by SamBelkacem** [comment]
Please, is it possible to have a reply?

**Comment by mikkokotila** [comment]
Does your model work if you run it regularly without Talos?

**Comment by SamBelkacem** [comment]
Thanks for your reply. Yes, it works regularly outside of Talos. When I use Talos, I can't retrain the best model I get from scan_results.

**Comment by mikkokotila** [comment]
Actually, you can achieve exactly the same as you are doing above by `scan_results.best_model()`. 

I tested with a very simple model, and I get the same error as you do.

**Comment by mikkokotila** [comment]
I'm not sure about the implications, but recompiling before retraining seems to work.

**Comment by SamBelkacem** [comment]
> Actually, you can achieve exactly the same as you are doing above by `scan_results.best_model()`.

It's not working, I get the following error when I use `scan_results.best_model()`:

/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    138             if cls is None:
    139                 raise ValueError('Unknown ' + printable_module_name +
--> 140                                  ': ' + class_name)
    141         if hasattr(cls, 'from_config'):
    142             custom_objects = custom_objects or {}

ValueError: Unknown initializer: GlorotUniform

**Comment by SamBelkacem** [comment]
> I'm not sure about the implications, but recompiling before retraining seems to work.

I don't want to recompile the best model before retraining it because I would lose the best parameters I just searched for with Talos.

**Comment by mikkokotila** [comment]
> I don't want to recompile the best model before retraining it because I would lose the best parameters I just searched for with Talos.

Why not recompile with exactly the same hyperparameters?

**Comment by SamBelkacem** [comment]
> > I don't want to recompile the best model before retraining it because I would lose the best parameters I just searched for with Talos.
> 
> Why not recompile with exactly the same hyperparameters?

How can I do so with Talos? Thanks for your time and consideration

**Comment by SamBelkacem** [comment]
> > I don't want to recompile the best model before retraining it because I would lose the best parameters I just searched for with Talos.
> 
> Why not recompile with exactly the same hyperparameters?

How can I print the values of the best parameters (learn_rate, momentum, etc.) I just searched for with Talos?

**Comment by mikkokotila** [comment]
You can get all the parameters either from the experiment log which is stored according to the `experiment_name` in `Scan()`. Or alternatively through `scan_object.data`. 

To my understanding, you would then just want to use those to recompile the model.

**Comment by SamBelkacem** [comment]
> You can get all the parameters either from the experiment log which is stored according to the `experiment_name` in `Scan()`. Or alternatively through `scan_object.data`.
> 
> To my understanding, you would then just want to use those to recompile the model.

Yes, that's what I want to do. Thank you for your reply.

**Comment by SamBelkacem** [comment]
I'm facing another error now when I try to save the best model with Pickle: 

```
model_id = scan_results.data['val_acc'].astype('float').argmax() - 1
model = model_from_json(scan_results.saved_models[model_id])
model.set_weights(scan_results.saved_weights[model_id])

with open("best_model.pkl", 'wb') as output:
    pickle.dump(model, output, pickle.HIGHEST_PROTOCOL)
```

TypeError: can't pickle _thread.RLock objects

**Comment by mikkokotila** [comment]
Can you share the entire trace. Generally you always want to do that, as it explains exactly what is going wrong. Just seeing the error message itself is mostly not useful. 

Also it seems that this issue is now resolved, so you should open a new ticket for any new issues.

**Comment by mikkokotila** [comment]
Have a look at #156 as it provides a reference to what you are experiencing.

**Comment by SamBelkacem** [comment]
> Can you share the entire trace. Generally you always want to do that, as it explains exactly what is going wrong. Just seeing the error message itself is mostly not useful.
> 
> Also it seems that this issue is now resolved, so you should open a new ticket for any new issues.

Thanks, I will open another issue.

**Comment by mikkokotila** [comment]
Closing this as resolved.
