### ISSUE TITLE
[FEATURE REQUEST] Make iterating over epochs smarter

### ISSUE THREAD

**Issue by Thomasillo** [autonomio/talos#447]
#### 1) I think Talos should add

Caching of runs or intermediate results in order to save time when just the number of epochs changes

#### 2) Once implemented, I can see how this feature will

Save running time

#### 3) I believe this feature is

- [X] must have

#### 4) Given the chance, I'd be happy to make a PR for this feature

- [ ] definitely
- [X] possibly
- [ ] unlikely

---

**Description:**

The change of the number of epochs comes at minimal cost, when the intermediate model performance is saved. Eg when trainining a model at fixed values of hyperparameters with say 100 epochs, one could save the validation and training performance along with all other metrics for all numbers of epochs smaller than 100 at almost no additional cost.

A library like joblib might be very suitable to achieve this.

**Comment by mikkokotila** [comment]
Cutting down time sounds always attractive :) Can you share more about your idea, because I did not understand how it would help us reduce experiment time.

**Comment by mikkokotila** [comment]
It's not at all clear how your proposal would make `Scan()` faster, because it seems to just suggest to not try different epochs as a parameter. I don't think one anyways needs to try different epochs as parameter, so closing here. 

Feel free to comment and reopen if I have misunderstood.
