### ISSUE TITLE
Talos 1.0 and Support for Tensorflow 2.1

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/talos#451]
## Talos 1.0

- Supports Tensorflow and PyTorch
- Continuous development and support
- Requires TensorFlow 2.0 or higher
- Starts with version 1.0
- Installs from `pip install git+https://github.com/autonomio/talos@1.0`
- Will not work with CNTK or Theano backends

## Legacy Talos

- Supports multi-backend Keras
- No new features, support until end of 2020
- Requires TensorFlow 1.15.0 or lower
- Ends with version 0.6.x
- Installs from pip few more weeks
- Works with Tensorflow, CNTK and Theano backends

**Comment by srujansai1997** [comment]
I am unable to install talos@1.0 from the above command.  i am getting and eroor "unknown command git"

**Comment by mikkokotila** [comment]
@srujansai1997 apologies, there was a typo in the command. You can try now, it will work.

**Comment by ralanburnett** [comment]
I installed Tensorflow 2.1 and talos using the link (everything appeared to be OK).  However, when I import talos I get the following error:
ImportError                               Traceback (most recent call last)
<ipython-input-2-461141aa5c41> in <module>
      1 import tensorflow as tf
----> 2 import talos

~\Anaconda3\envs\tensorflow_2.0_gpu\lib\site-packages\talos\__init__.py in <module>
     12 
     13 # import extras
---> 14 from . import utils
     15 from . import templates
     16 from . import autom8

~\Anaconda3\envs\tensorflow_2.0_gpu\lib\site-packages\talos\utils\__init__.py in <module>
      1 # In this init we load everything under utils in the Talos namespace
      2 
----> 3 from kerasplotlib import TrainingLog as live
      4 
      5 from ..model.normalizers import lr_normalizer

~\Anaconda3\envs\tensorflow_2.0_gpu\lib\site-packages\kerasplotlib\__init__.py in <module>
----> 1 from kerasplotlib.traininglog import TrainingLog

~\Anaconda3\envs\tensorflow_2.0_gpu\lib\site-packages\kerasplotlib\traininglog.py in <module>
      6 from IPython.display import clear_output
      7 
----> 8 from keras.callbacks import Callback
      9 
     10 def loss2name(loss):

~\AppData\Roaming\Python\Python36\site-packages\keras\__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

~\AppData\Roaming\Python\Python36\site-packages\keras\utils\__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 from . import losses_utils
      8 from . import metrics_utils

~\AppData\Roaming\Python\Python36\site-packages\keras\utils\conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

~\AppData\Roaming\Python\Python36\site-packages\keras\backend\__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

~\AppData\Roaming\Python\Python36\site-packages\keras\backend\load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

~\AppData\Roaming\Python\Python36\site-packages\keras\backend\tensorflow_backend.py in <module>
     11 from tensorflow.python.ops import state_ops as tf_state_ops
     12 from tensorflow.python.keras import backend as tf_keras_backend
---> 13 from tensorflow.python.keras.utils import tf_utils
     14 from tensorflow.python.ops import functional_ops
     15 from tensorflow.python.ops import ctc_ops as ctc

ImportError: cannot import name 'tf_utils'

Should I try with Tensorflow 2.0 instead?

**Comment by mikkokotila** [comment]
The first thing is to make sure that all your own imports are in the form of `tensorflow.keras.something` and not `keras.something`.

**Comment by srujansai1997** [comment]
> @srujansai1997 apologies, there was a typo in the command. You can try now, the edited command will work.

Thank you, It worked. very efficient module.

**Comment by ralanburnett** [comment]
I got Legacy Talos to work on a remote Linux machine at my university.  That enabled me to do a clean install.  I also got everything installed for  Talos 1.0 (on the university machine, in a separate virtual environment), but I am getting an error relating to cuda when I import talos.  Is there a way to run Talos 1.0 without GPU support?  Here is the error:

>>> import talos
Using TensorFlow backend.
2020-01-27 18:30:58.239915: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64::/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/usr/local/cuda/lib64::/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/usr/local/cuda/lib64/
2020-01-27 18:30:58.240016: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64::/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/usr/local/cuda/lib64::/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/usr/local/cuda/lib64/
2020-01-27 18:30:58.240028: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
>>> exit

**Comment by ralanburnett** [comment]
tf.__version__ = 1.8.0.  that is obviously a problem.  This is for a brand new virtual environment on my local machine that doesn't even list tensorflow 1.8.0 as being installed in the environment, rather it lists tensorflow 2.1!

**Comment by mikkokotila** [comment]
> Is there a way to run Talos 1.0 without GPU support? Here is the error:

Yes. You can `pip uninstall tensorflow` and then `pip install tensorflow-cpu==2.1.0`. Recently `tensorflow` package became what used to be `tensorflow-gpu`.

**Comment by mikkokotila** [comment]
> tf.version = 1.8.0. that is obviously a problem. This is for a brand new virtual environment on my local machine that doesn't even list tensorflow 1.8.0 as being installed in the environment, rather it lists tensorflow 2.1!

What is this in reference to? I did not find any mention about v1.8.0 from the issue.

**Comment by ralanburnett** [comment]
It was in response to: "Also, in the kernel where you are getting this
error, can you do tensorflow.__version__."

**Comment by fctester9** [comment]
hi. it was working fine 2 days ago and now receiving the following error:
# Install talos
!pip install git+https://github.com/autonomio/talos@1.0 --quiet
 Building wheel for talos (setup.py) ... done

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-a74a84ec118e> in <module>()
----> 1 import talos
      2 from talos.utils import lr_normalizer

1 frames
/usr/local/lib/python3.6/dist-packages/talos/utils/__init__.py in <module>()
      8 from .generator import generator
      9 from . import gpu_utils
---> 10 import talos.metrics.keras_metrics as metrics
     11 from .sequence_generator import SequenceGenerator
     12 from .rescale_meanzero import rescale_meanzero

AttributeError: module 'talos' has no attribute 'metrics'

**Comment by mikkokotila** [comment]
@fctester9 please create a new ticket for your issue, this ticket is just to announce the support for TensorFlow 2.1.
