### ISSUE TITLE
No url found error while using random_method='quantum'

### ISSUE THREAD

**Issue by srujansai1997** [autonomio/talos#459]
hello !!
I am getting the following error if I use the argument random_method='quantum' and fraction_limit=0.1 
![Screenshot from 2020-01-28 10-23-03](https://user-images.githubusercontent.com/60318378/73236712-648def00-41b9-11ea-946f-25b10fe1f2c4.png)

**Comment by srujansai1997** [comment]
I am also getting this error when recovering best model from experiment log .

> TalosModelError: <class 'tensorflow.python.keras.optimizer_v2.adam.Adam'> is not supported by lr_normalizer

**Comment by mikkokotila** [comment]
For the first part, I have to look in the upstream package (chances). Maybe some API have changed its address. 

For the second part, when you recover model from experiment log, it will not work unless you have used string values as names of optimizers.
