### ISSUE TITLE
I have 17137  sample but scaning on 11995   samples. is there any auto splitting?

### ISSUE THREAD

**Issue by salihgunduz** [autonomio/talos#461]
First off, make sure to check your [support options](https://github.com/autonomio/talos#-how-to-get-support).

The preferred way to resolve usage related matters is through the [docs](https://autonomio.github.io/talos/#/) which are maintained up-to-date with the latest version of Talos.

If you do end up asking for support in a new issue, make sure to follow the below steps carefully.

#### 1) Confirm the below

- [x] I have looked for an answer in the [Docs](https://autonomio.github.io/talos)
- [ ] My Python version is 3.5 or higher
- [ ] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [ ] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__`

#### 3) Explain clearly what you are trying to achieve

*A description of your specific use-case and what you hope to achieve with it*

#### 4) Explain what you have already tried

*An outline of the steps that you have already taken so far*

#### 5) Provide a code-complete reference

- [ ] My support question includes an input model
- [ ] My support question includes a parameter dictionary
- [x] My support question includes a `Scan()` command
- [ ] My support question includes a link to a sample of the data

NOTE: If the data is sensitive and can't be shared, [create dummy data](https://scikit-learn.org/stable/modules/classes.html#samples-generator) that mimics it.

**A self-contained Jupyter Notebook, Google Colab, or similar is highly preferred and will speed up helping you with your issue.**

---

**Comment by mikkokotila** [comment]
Please provide more information about the issue. The headline does not make it clear.
