### ISSUE TITLE
Bibtex for citation

### ISSUE THREAD

**Issue by wkerzendorf** [autonomio/talos#462]
It doesn't quite fit into any of the categories. But could you please make a bibtex for citation purposes. Zenodo is a free way (supported by the EU - not a company) to make software easily citable.

**Comment by mikkokotila** [comment]
Thanks :) I had a look at Zenodo, and I'm not completely clearly how that would work for a open source software. It seems that the object of abstraction is "upload" ... would that in case of Talos be a specific version of Talos?

**Comment by wkerzendorf** [comment]
You can register it with zenodo as a github and then every release will get a new DOI. Happy to chat about this - ping me at `wkerzend@msu.edu`

**Comment by mikkokotila** [comment]
Thanks. I've set it up now so from the next release onward it should do it. I'll add the badge to the [citation segment of README.md](https://github.com/autonomio/talos/blob/master/README.md#-citations).

**Comment by wkerzendorf** [comment]
awesome! I'll add it to our paper - more than happy to discuss citation of codes in academia - feel free to ping me.
