### ISSUE TITLE
Error When Installing in Colab and Paperspace (Recent issue, fine 2 days ago)

### ISSUE THREAD

**Issue by fctester9** [autonomio/talos#463]
hi. it was working fine 2 days ago and now receiving the following error:

Install talos
!pip install git+https://github.com/autonomio/talos@1.0 --quiet
Building wheel for talos (setup.py) ... done

AttributeError Traceback (most recent call last)
in ()
----> 1 import talos
2 from talos.utils import lr_normalizer

1 frames
/usr/local/lib/python3.6/dist-packages/talos/utils/init.py in ()
8 from .generator import generator
9 from . import gpu_utils
---> 10 import talos.metrics.keras_metrics as metrics
11 from .sequence_generator import SequenceGenerator
12 from .rescale_meanzero import rescale_meanzero

AttributeError: module 'talos' has no attribute 'metrics'
---

**Comment by mikkokotila** [comment]
What do you get with `talos.__version__`

**Comment by fctester9** [comment]
i hope this is helpful:
Collecting git+https://github.com/autonomio/talos@1.0
  Cloning https://github.com/autonomio/talos (to revision 1.0) to /tmp/pip-req-build-zrmbbkp3
  Running command git clone -q https://github.com/autonomio/talos /tmp/pip-req-build-zrmbbkp3
  Running command git checkout -b 1.0 --track origin/1.0
  Switched to a new branch '1.0'
  Branch '1.0' set up to track remote branch '1.0' from 'origin'.
Requirement already satisfied (use --upgrade to upgrade): talos==1.0 from git+https://github.com/autonomio/talos@1.0 in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: tensorflow>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (2.1.0)
Requirement already satisfied: statsmodels>=0.11.0 in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (0.11.0)
Requirement already satisfied: wrangle in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (0.6.7)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (1.17.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (0.25.3)
Requirement already satisfied: astetik in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (1.9.9)
Requirement already satisfied: sklearn in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (0.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (4.28.1)
Requirement already satisfied: chances in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (0.1.9)
Requirement already satisfied: kerasplotlib in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (0.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from talos==1.0) (2.21.0)
Requirement already satisfied: scipy==1.4.1; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (1.4.1)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (0.9.0)
Requirement already satisfied: keras-applications>=1.0.8 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (1.0.8)
Requirement already satisfied: gast==0.2.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (0.2.2)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (1.1.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (0.34.2)
Requirement already satisfied: keras-preprocessing>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (1.15.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (3.1.0)
Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (1.11.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (1.12.0)
Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (2.1.0)
Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (0.8.1)
Requirement already satisfied: tensorflow-estimator<2.2.0,>=2.1.0rc0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (2.1.0)
Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (0.1.8)
Requirement already satisfied: protobuf>=3.8.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.0.0->talos==1.0) (3.10.0)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.6/dist-packages (from statsmodels>=0.11.0->talos==1.0) (0.5.1)
Requirement already satisfied: keras in /usr/local/lib/python3.6/dist-packages (from wrangle->talos==1.0) (2.2.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->talos==1.0) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas->talos==1.0) (2.6.1)
Requirement already satisfied: geonamescache in /usr/local/lib/python3.6/dist-packages (from astetik->talos==1.0) (1.1.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from sklearn->talos==1.0) (0.22.1)
Requirement already satisfied: ipython in /usr/local/lib/python3.6/dist-packages (from kerasplotlib->talos==1.0) (5.5.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->talos==1.0) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->talos==1.0) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->talos==1.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->talos==1.0) (2019.11.28)
Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras-applications>=1.0.8->tensorflow>=2.0.0->talos==1.0) (2.8.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (3.1.1)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (45.1.0)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (0.16.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (1.11.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (0.4.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from keras->wrangle->talos==1.0) (3.13)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn->talos==1.0) (0.14.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from ipython->kerasplotlib->talos==1.0) (1.0.18)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from ipython->kerasplotlib->talos==1.0) (0.7.5)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from ipython->kerasplotlib->talos==1.0) (4.4.1)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.6/dist-packages (from ipython->kerasplotlib->talos==1.0) (4.3.3)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/dist-packages (from ipython->kerasplotlib->talos==1.0) (2.1.3)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.6/dist-packages (from ipython->kerasplotlib->talos==1.0) (0.8.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from ipython->kerasplotlib->talos==1.0) (4.8.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (0.2.8)
Requirement already satisfied: rsa<4.1,>=3.1.4 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (4.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (4.0.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (1.3.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->kerasplotlib->talos==1.0) (0.1.8)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.2->ipython->kerasplotlib->talos==1.0) (0.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/dist-packages (from pexpect; sys_platform != "win32"->ipython->kerasplotlib->talos==1.0) (0.6.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.6/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.0.0->talos==1.0) (3.1.0)
Building wheels for collected packages: talos
  Building wheel for talos (setup.py) ... done
  Created wheel for talos: filename=talos-1.0-cp36-none-any.whl size=53700 sha256=330813ab5f1cda413299dc2f72375439c1842072ff5c28fe6f9dd6f578fc459a
  Stored in directory: /tmp/pip-ephem-wheel-cache-eq03tx9y/wheels/9f/14/d1/e58012a97c43cf2148959890b171f49e4a5e1c82a9946b2c22
Successfully built talos

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-07b57bdb60b7> in <module>()
----> 1 talos.__version__

NameError: name 'talos' is not defined

**Comment by mikkokotila** [comment]
Can you open python console (or notebook) and then run the following: 

```
import talos
talos.__version__
```
You must run those commands exactly as I have provided it, and then copy paste the output here.

**Comment by fctester9** [comment]
Using TensorFlow backend.
'1.0.0'

-working now
