### ISSUE TITLE
What can I do to reduce execution time?

### ISSUE THREAD

**Issue by nandinimatam** [autonomio/talos#466]
i have tried to execute the deep learning models using talos ,for 1000 records also it is taking lot of time for execution ,please suggest  me how to improve the speed and  decrease execution time  in talos package

**Comment by mikkokotila** [comment]
Talos does not add execution time to running the exact same model configurations in Keras or Tensorflow. That's one of the guiding principles of Talos' development. 

Have a look at the many [optimization strategies](https://autonomio.github.io/talos/#/Optimization_Strategies?id=optimization-strategies) available in Talos. They all work towards the goal of reducing the wall clock time taken to complete an experiment. 

The simplest thing you can do to get started is to use one of the [reduction limits](https://autonomio.github.io/talos/#/Scan) available in `Scan()`. You could for example just start with `talos.Scan(...round_limit=100...)` which will limit the number of permutations to 100, which are randomly picked from the total parameter space. 

You can share your parameter dictionary, and I might be able to point out some best practices there as well.

**Comment by nandinimatam** [comment]
thanks for your prompt response

**Comment by mikkokotila** [comment]
Closing this as resolved.
