### ISSUE TITLE
 getting network issue while trying optimize the parameters like fraction_limit and round_limit ?

### ISSUE THREAD

**Issue by nandinimatam** [autonomio/talos#467]
i am trying to add fraction_limit,round_limit in talos.scan function i am getting this error <class 'urllib.error.URLError'> ,this is due to connectivity issue ,how to resolve this issue,how can i able to run this without having open network ,Please suggest on this

**Comment by mikkokotila** [comment]
Is it this same issue #459. In that case just use any other random method than `quantum`. 

Otherwise, please provide the entire trace.

**Comment by nandinimatam** [comment]
thanks,please tell me why  i am getting that issue with random_method='quantum',what was reason behind it .please help on this .

**Comment by mikkokotila** [comment]
> thanks,please tell me why i am getting that issue with random_method='quantum',what was reason behind it .please help on this .

This relates with another package that handles the random methods (chances) and will have to be fixed there. So closing here. 

For the time being, simply use one of the other available random methods.
