### ISSUE TITLE
Need support how to set fraction_limit variable in talos.scan function

### ISSUE THREAD

**Issue by nandinimatam** [autonomio/talos#469]
I have added fraction_limit=0.001 to my 1000 records data , i am getting issue with this value,on what basis  we have to select value  of fraction_limit value ,
Please suggest on this 

below i am mentioning the issue here :
egressionModel failed!!!. Limiters lead to < 1 permutations.
<class 'talos.utils.exceptions.TalosDataError'> ('C:\\Users\\nandini.m\\Workspace\\EIONSVN\\EION-27 feb\\Deeplearner', 'Regression.py') 158
server code execution failed !.... 'NoneType' object is not iterable

**Comment by mikkokotila** [comment]
You can try `fraction_limit=0.01` instead (which will end up with 10 permutations). 

The error message you have posted above says it here: 

`Limiters lead to < 1 permutations.`

Closing this as resolved.
