### ISSUE TITLE
Issue with shaping 

### ISSUE THREAD

**Issue by giacomotontini** [autonomio/talos#47]
I keep getting this tedious error:

> ValueError: Error when checking input: expected gru_1_input to have 3 dimensions, but got array with shape (35361, 21)

Tried reshaping in every way but the error continues to come over... In my project I was using batch generator and fit_generator as model training method but this isn't yet supported by this library, so I'm trying to use Talos without them

```
 p = {'lr': (2, 10, 30),
     'first_neuron':[4, 8, 16, 32, 64, 128],
     'hidden_layers':[1,2,3,4,5,6],
     'batch_size': [2, 3, 4],
     'epochs': [300],
     'dropout': (0, 0.40, 10),
     'optimizer': [Adam],
     'losses': [mae],
     'activation':[relu, elu],
     'last_activation': [sigmoid, softmax]}

def iris_model(x_train, y_train, x_val, y_val, params):

    model = Sequential()
    model.add(GRU(params['first_neuron'], input_shape=(None, x_train.shape[1]), activation=params['activation']))
    model.add(Dropout(params['dropout']))
    model.add(Dense(y_train.shape[1], activation=params['last_activation']))

    model.compile(optimizer=params['optimizer'](),
                  loss=params['losses'],
                  metrics=['acc'])

    history = model.fit(x_train, y_train,
                    batch_size=params['batch_size'],
                    epochs=params['epochs'],
                    verbose=0,
                    validation_data=[x_val, y_val])

    return history, model

#x_train = x_train.reshape(1, x_train.shape[0], x_train.shape[1])
#y_train = y_train.reshape(1, y_train.shape[0], y_train.shape[1])

print(x_train_scaled.shape)
print(y_train_scaled.shape)

h = ta.Scan(x_train,
            y_train, 
            params=p,
            dataset_name='first_test',
            experiment_no = '1',
            model=iris_model, 
            grid_downsample=0.5,
            val_split=0.1,
            shuffle = False,
            reduction_metric='val_loss')
```

Shapes output: 
X=> (39291, 21)
Y=> (39291, 3)

**Comment by x94carbone** [comment]
Is GRU a 1D CNN? If so, Keras is going to expect your input to look like `(m, n, h)`, where `m` is the number of training examples, `n` the number of features, and `h` the number of channels. I see you tried something similar, but it can be fickle. You might need to play with the order.

**Comment by giacomotontini** [comment]
Well, in that case 39291 are datetime series of measurement with 6 parameter each (temperature humity etc)
It's not CNN but a RNN, so m stand for batch number(samples), n for sequence length, and h for feature... I can't understand why it need the number of samples when I don't have a batch generator, so it is just 1 sequence with tons of records

**Comment by x94carbone** [comment]
I apologize, but I'm confused. The batch size is a parameter in the training step, it indicates after how many samples we update the gradient, if I remember correctly.

An RNN? Meaning recurrent neural network? I'm not too familiar, so I'd have to see the exact form of the input to help you. That said, you might have better luck posting the issue on the Keras repo page, since this isn't a problem with Talos specifically.

That said I'll still help if I can! What is the form of GRU?

**Comment by giacomotontini** [comment]
From keras doc  GRU (and any other Recurrent Neural Network layer) need an input tensor with shape (batch_size, timesteps, input_dim).
The batch size is the number of samples within a batch; timesteps how many records in each samples and input_dim is basically the amount of feature.

Without talos it works pretty well with the same input shape
