### ISSUE TITLE
how to use talos with scikit learn pipeline 

### ISSUE THREAD

**Issue by DEEP2907** [autonomio/talos#470]
First off, make sure to check your [support options](https://github.com/autonomio/talos#-how-to-get-support).

The preferred way to resolve usage related matters is through the [docs](https://autonomio.github.io/talos/#/) which are maintained up-to-date with the latest version of Talos.

If you do end up asking for support in a new issue, make sure to follow the below steps carefully.

#### 1) Confirm the below

- [x] I have looked for an answer in the [Docs](https://autonomio.github.io/talos)
- [x] My Python version is 3.5 or higher
- [x] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [x] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__`

#### 3) Explain clearly what you are trying to achieve

*A description of your specific use-case and what you hope to achieve with it*

#### 4) Explain what you have already tried

*An outline of the steps that you have already taken so far*

#### 5) Provide a code-complete reference

- [x] My support question includes an input model
- [x] My support question includes a parameter dictionary
- [x] My support question includes a `Scan()` command
- [x] My support question includes a link to a sample of the data

NOTE: If the data is sensitive and can't be shared, [create dummy data](https://scikit-learn.org/stable/modules/classes.html#samples-generator) that mimics it.

**A self-contained Jupyter Notebook, Google Colab, or similar is highly preferred and will speed up helping you with your issue.**

---

**Comment by mikkokotila** [comment]
Talos is not intended to be used as part of a scikit pipeline but instead introduces its own pipeline. 

Closing this as resolved.
