### ISSUE TITLE
Getting issue with round_limit optimize features 

### ISSUE THREAD

**Issue by nandinimatam** [autonomio/talos#472]
No eligble random_method found. Using uniform_mersenne.

-----> regressionModel failed!!!. Sample larger than population or is negative

i am getting issue above while  i am tuning with round_limit=10 or round_limit=20 or more than that ,
it is working with round_limit=5 ,

please suggest on this issue ,why it is not working if i am increasing the round_limit .

**Comment by mikkokotila** [comment]
Please share your parameter dictionary.

**Comment by nandinimatam** [comment]
thanks i got my mistake its about parameter dictionary only.
