### ISSUE TITLE
I would to like set time limit for talos.scan model ?

### ISSUE THREAD

**Issue by nandinimatam** [autonomio/talos#475]
Please suggest me how to set time limit or early stopping for talos model .
there is time format feature is there ,please suggest one example to set the time limit for talos.scan model.

**Comment by mikkokotila** [comment]
`talos.Scan(...time_limit=2020-02-25 08:00...)` will stop the experiment no later than 25th of Feb, 2020 at 8 am. 

To get most out of Talos, I encourage you to read through the documentation: https://autonomio.github.io/talos. 

Closing this as resolved.
