### ISSUE TITLE
performance parameters are different from mine 

### ISSUE THREAD

**Issue by CarloBortone** [autonomio/talos#478]
Hi guys i specified the parameter 'batch_size': (10, 20, 30)
and in my performance log i have very strange values for batch_size, like : 18,19,13,12,17
does anyone know why?

**Comment by mikkokotila** [comment]
You have to input `[10, 20, 30]`, because tuple will create a range.

**Comment by mikkokotila** [comment]
user

**Comment by CarloBortone** [comment]
thank you
