### ISSUE TITLE
ValueError: Input 0 is incompatible with layer lstm_54: expected ndim=3, found ndim=2

### ISSUE THREAD

**Issue by PietroAmin** [autonomio/talos#479]
First off, make sure to check your [support options](https://github.com/autonomio/talos#-how-to-get-support).

The preferred way to resolve usage related matters is through the [docs](https://autonomio.github.io/talos/#/) which are maintained up-to-date with the latest version of Talos.

If you do end up asking for support in a new issue, make sure to follow the below steps carefully.

#### 1) Confirm the below

- [yes ] I have looked for an answer in the [Docs](https://autonomio.github.io/talos)
- [yes ] My Python version is 3.5 or higher
- [ yes] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [ yes] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__`: 0.6.6

#### 3) Explain clearly what you are trying to achieve

![Capture](https://user-images.githubusercontent.com/57229052/76778536-4e101700-67aa-11ea-808a-461f6a911b25.PNG)

![ww](https://user-images.githubusercontent.com/57229052/76778580-5e27f680-67aa-11ea-90ab-19a677311c59.PNG)

#### 4) Explain what you have already tried

I simply have no idea why this error is popping up as if the model is trained without scan it works fine.

#### 5) Provide a code-complete reference

- [yes ] My support question includes an input model
- [yes ] My support question includes a parameter dictionary
- [yes ] My support question includes a `Scan()` command
- [ ] My support question includes a link to a sample of the data

NOTE: If the data is sensitive and can't be shared, [create dummy data](https://scikit-learn.org/stable/modules/classes.html#samples-generator) that mimics it.

**A self-contained Jupyter Notebook, Google Colab, or similar is highly preferred and will speed up helping you with your issue.**

---

**Comment by mattou78400** [comment]
Hi,

How was the issue fixed?
I'm having the same kind of issue with predictig after a scan:
`
scan_object = talos.autom8.AutoScan(task='continuous', max_param_values=3, experiment_name='testing.new')
scan_object = scan_object.start(x=x_train, y=self.train_y, x_val = x_val, y_val = self.test_y, round_limit=2, fraction_limit=0.00001)
talos.Deploy(scan_object=scan_object, model_name='deploy', metric='mae')
[...]
loaded_model = talos.Restore('deploy.zip')
 self.pred = loaded_model .model.predict(x_val)
`
it then throws :
Input 0 of layer sequential is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [None, 393]

When the pred Xs are the same as the training_val Xs.
