### ISSUE TITLE
ValueError: Classification metrics can't handle a mix of unknown and binary targets

### ISSUE THREAD

**Issue by WilfriedOdi** [autonomio/talos#487]
Thanks a lot for suggesting a feature to Talos. Please take a moment to go through the below checklist to provide context in a way that makes it easy to take your request forward.

def qsar_oral_toxicity():
    tubes_df = pd.read_csv("qsar_oral_toxicity/qsar_oral_toxicity.csv", sep=';', decimal=',')
    tubes_df_data = tubes_df.iloc[:, :5]
    coords_test_df = tubes_df.iloc[:, 5:]

    tubes_arr = tubes_df_data.values
    coords_test = coords_test_df.values

    coord_names = coords_test_df.columns.values.tolist()

    # масштабируем все спектры к единичной дисперсии
    tubes_arr = preprocessing.scale(tubes_arr)

    # словари для реальных и предсказанных значений
    y_test_knn = {}
    y_test_mlpr = {}
    y_real = {}

    knn_params = {
        "n_neighbors": [x for x in range(15, 40, 5)],
        "weights": ["uniform", "distance"],
        "algorithm": ["ball_tree", "kd_tree"]
    }

    mlpr_params = { "hidden_layer_sizes": [
            (120, 60), (50, 40), (60)],
            "alpha": [0.0001, 0.001, 0.01],
            "learning_rate_init": [0.005, 0.001, 0.01]}

    for i in range(coords_test.shape[1]):
        X_train, X_test, y_train, y_test = train_test_split(tubes_arr, coords_test[:, i], test_size=0.25)

        X_test = X_test.astype('int')
        y_train = y_train.astype('int')

        knn = KNeighborsClassifier()
        knn_grid = GridSearchCV(knn, knn_params, cv=3, n_jobs=-1, verbose=10)
        knn_grid.fit(X_train, y_train)

        y_pred_knn = knn_grid.predict(X_test)

        acc_svc = metrics.accuracy_score(y_test, y_pred_knn)
        prec_svc = metrics.precision_score(y_test, y_pred_knn)
        rec_svc = metrics.recall_score(y_test, y_pred_knn)

**Comment by mikkokotila** [comment]
Can you share the full error trace message.
