### ISSUE TITLE
Logs last epoch metrics instead of the the best model ones.

### ISSUE THREAD

**Issue by vitormanfredini** [autonomio/talos#491]
Talos logs last epochs' metrics instead of the best epochs' metrics (determined be early stopping). This makes the csv log useless/misleading to me since it doesn't represent my saved models.

I'm using `keras.callbacks.EarlyStopping` directly so I can pass `restore_best_weights=True`. I'm aware of talos' `early_stopper` but it doesn't support the `restore_best_weights` parameter (also it just returns a `keras.callbacks.EarlyStopping` anyway). Am I missing something here?

Everything else works as expected.

My `talos.__version__` is:
0.6.4

**Comment by mikkokotila** [comment]
It used to be like that, but it's confusing and there are other problems that come with that approach.

The best practice for this line of work appears to be to set an acceptable level of result before the experiment and stop the experiment once you have achieved it. This seems to end with the least amount of well-known biases.

**Comment by StefanBloemheuvel** [comment]
@vitormanfredini,

Have you found a workaround for this problem? I also want to know the lowest val_los that a combination of hyperparameters achieved, not the last epoch...
