### ISSUE TITLE
I tried to apply talos tool to find hyperparameters on a datset but I got the error: module 'keras_preprocessing.image' has no attribute 'DataFrameIterator'

### ISSUE THREAD

**Issue by USAMAH1989** [autonomio/talos#492]
Thank you very much for reporting a bug on Talos. Before you do, please go through the below checklist carefully and make sure to prepare your bug report in a way that facilitates effective handling of the matter.

#### 1) Confirm the below

- [ ] My Python version is 3.5 or higher
- [ ] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [ ] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__`

#### 3) Explain clearly what you expect to happen

*A description of what you tried to do and what you thought should happen.*

#### 4) Explain what actually happened

*A description of the issue in Talos that you had identified*

#### 5) Provide a code-complete reference

- [ ] My bug report includes an input model
- [ ] My bug report includes a parameter dictionary
- [ ] My bug report includes a `Scan()` command
- [ ] My bug report question includes a link to a sample of the data

NOTE: If the data is sensitive and can't be shared, [create dummy data](https://scikit-learn.org/stable/modules/classes.html#samples-generator) that mimics it.

**A self-contained Jupyter Notebook, Google Colab, or similar is highly preferred and will speed up helping you with your issue.**

---

**Comment by mikkokotila** [comment]
You get this error from Keras, it has to do with your model or the Keras version you are using. Closing here, feel free to open new one if anything.
