### ISSUE TITLE
we have implemented autodl  using talos.

### ISSUE THREAD

**Issue by nandinimatam** [autonomio/talos#493]
we have developed the autodl using talos ,
problem is that , best_modelSNN = scan_object.best_model(metric='val_acc', asc=True),
not sure how it is returning the best model 
 
Not sure but it seems like it will pick lessor accuracy model rather than higher accuracy model. 
please can you give me the explaination how it is giving best model  i mean based on what it is giving best model.

**Comment by mikkokotila** [comment]
Sorry for late reply. 

It is based on a two-stepped process, where first during `Scan()` it will score each permutation. Then it will take `n` best models based on that, and use a validation metric to do k-fold and find "best" model.
