### ISSUE TITLE
Which version of Talos uses Tensorflow 1.12?

### ISSUE THREAD

**Issue by Nennemus** [autonomio/talos#501]
I am trying to install Talos on my University's computing servers, however I get an error since the version of Talos I am trying to install (version 0.6.6) relies on Tensorflow 1.14, which I do not have access to. The modules provided by my University's server, only provide Tensorflow 1.12, so I want to figure out which version of Talos I need to install to make it compatible.

**Comment by mikkokotila** [comment]
You can try `pip install pip install tensorflow==1.12` or similar.
