### ISSUE TITLE
Siamese network with multiple inputs unable to make it work

### ISSUE THREAD

**Issue by prateeksaurabh** [autonomio/talos#504]
First off, make sure to check your [support options](https://github.com/autonomio/talos#-how-to-get-support).

The preferred way to resolve usage related matters is through the [docs](https://autonomio.github.io/talos/#/) which are maintained up-to-date with the latest version of Talos.

If you do end up asking for support in a new issue, make sure to follow the below steps carefully.

#### 1) Confirm the below

- [ ] I have looked for an answer in the [Docs](https://autonomio.github.io/talos)
**Yes**
- [x] My Python version is 3.5 or higher
**3.8.3**

- [x] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
**Yes i found one issue #419 which might be similar but i am unable to figure out what was the exact issue**

- [x] I've tested that my Keras model works as a stand-alone
**Yes, my code works as stand alone that much part i hope i have tested positively**
#### 2) Include the output of:

`talos.__version__`
**0.6.4**

#### 3) Explain clearly what you are trying to achieve

*A description of your specific use-case and what you hope to achieve with it*
**I am trying to build a siamese network which inputs two inputs. However when performing talos scan i am getting error as missing 2 required positional arguments: 'y_val' and 'params'. To me this seems more of a python problem rather than talos problem but i am not so sure how to fix or troubleshoot it. I am new with python and machine learning**

#### 4) Explain what you have already tried
**My keras model without talos is working**
*An outline of the steps that you have already taken so far*

#### 5) Provide a code-complete reference
**However when i try to use talos i am unable to make it work. My code is**
```
# params = {
#               'filter1':[1,2,4,6,8,12,16,24],
#     'kernel_size1':[2,4,6,8,12],
#     'filter3' :  ['same','valid'],
#     'kernel_size3' :  [2, 32,64,128],
#     'decay' :[.1,0.01,.001,.0001,.00001,.000001],
#     'droprate1' :[.1, .2,.3],
#     'filter2':[1,2,4,6,8,12,16,24],
#     'kernel_size2':[2,4,6,8,12],
#     'droprate4' :  ['same','valid'],
#     'strides2' :  [2, 32,64,128],
#     'l2_decay_2' :[.1,0.01,.001,.0001,.00001,.000001],
#     'droprate2' :[.1, .2,.3],
#     'units1': [256,128,64,512,1024],
#     'droprate3': [.1, .2,.3],
#     'lr' :[.1,0.01,.001,.0001,.00001,.000001]   
    
#              }


p = {
    'filter1':[6],
    'kernel_size1':[4],
    'filter3' :  [1],
    'kernel_size3' :  [2],
    'decay' :[.1],
    'droprate1' :[.1],
    'filter2':[4],
    'kernel_size2':[3],
    'droprate4' :  [.1],
    'droprate2' :[.1],
    'units1': [64],
    'droprate3': [.1, .2],
    'lr' :[.1]   
    
             }
```
```
def siamese(train_first_input,train_second_input,y_train,val_first_input,val_second_input,y_val,params):
    W_init = tf.keras.initializers.he_normal(seed=100)
    b_init = tf.keras.initializers.he_normal(seed=50)

    input_shape = (24,939)
    left_input = Input(input_shape)
    right_input = Input(input_shape)

    encoder = Sequential()
    encoder.add(Conv1D(filters=params['filter1'],kernel_size=params['kernel_size1'], padding='same', activation='relu',input_shape=input_shape,kernel_initializer=W_init, bias_initializer=b_init))
    encoder.add(BatchNormalization())
    encoder.add(Dropout(params["droprate1"]))
    encoder.add(MaxPool1D())
    encoder.add(Conv1D(filters=params["filter2"],kernel_size=params['kernel_size2'], padding='same', activation='relu'))
    encoder.add(BatchNormalization())
    encoder.add(Dropout(params["droprate2"]))
    encoder.add(MaxPool1D())
    encoder.add(Conv1D(filters=params['filter3'],kernel_size=params['kernel_size3'], padding='same', activation='relu'))
    encoder.add(BatchNormalization())
    encoder.add(Dropout(params['droprate3']))
    encoder.add(MaxPool1D())
    encoder.add(Flatten())
    encoder.add(Dense(params['unit1'],activation='relu'))
    encoder.add(Dropout(params['droprate4']))

    encoded_l = encoder(left_input)
    encoded_r = encoder(right_input)
    distance = Lambda(euclidean_distance, output_shape=eucl_dist_output_shape)([encoded_l, encoded_r])
    adam = optimizers.Adam(lr=params['lr'], beta_1=0.1, beta_2=0.999,decay=params['decay'], amsgrad=False)
    earlyStopping = EarlyStopping(monitor='loss',min_delta=0,patience=3,verbose=1,restore_best_weights=False)
    callback_early_stop_reduceLROnPlateau=[earlyStopping]
    model = Model([left_input, right_input], distance)
    model.compile(loss=contrastive_loss, optimizer=adam,metrics=[accuracy])
    model.summary()
    #history = model.fit([(xtrain_np_img1).astype(np.float32),(xtrain_np_img1).astype(np.float32)],y_train_numpy,batch_size=128,verbose=1,epochs=4,validation_split=0.15,callbacks=callback_early_stop_reduceLROnPlateau)
    history = model.fit([(train_first_input).astype(np.float32),(train_second_input).astype(np.float32)],y_train,validation_data=([(val_first_input).astype(np.float32),(val_second_input).astype(np.float32)],y_val),batch_size=128,verbose=1,epochs=4,callbacks=callback_early_stop_reduceLROnPlateau)
    return model,history
```
```
t = ta.Scan(x=[xtrain_np_img1,xtrain_np_img2],y=y_train_numpy,x_val=[xtest_np_img1,xtest_np_img2],y_val=y_test_numpy,model=siamese,params=p,experiment_name='exp_1')
```
**Error::::;
TypeError: siamese() missing 2 required positional arguments: 'y_val' and 'params'**

- [x] My support question includes an input model
- [x] My support question includes a parameter dictionary
- [x] My support question includes a `Scan()` command
- [x] My support question includes a link to a sample of the data

NOTE: If the data is sensitive and can't be shared, [create dummy data](https://scikit-learn.org/stable/modules/classes.html#samples-generator) that mimics it.

**A self-contained Jupyter Notebook, Google Colab, or similar is highly preferred and will speed up helping you with your issue.**

---

**Comment by prateeksaurabh** [comment]
I forgot to give colab link
https://colab.research.google.com/drive/1VK7PQJBt-YoSOuRXLRgq4hxuIK0pNIC4?usp=sharing

**Comment by mikkokotila** [comment]
Have a look at [this example](https://autonomio.github.io/talos/#/Examples_Multiple_Inputs).

**Comment by prateeksaurabh** [comment]
Thanks for the help, I was able to make it work. Closing it now
