### ISSUE TITLE
Models have parameters which are not defined at the parameter space

### ISSUE THREAD

**Issue by BY-hash** [autonomio/talos#508]
Hello,

For example, for round_limit=3, in the first round 'batch_size': 13, for the second round: round_limit=16 and for the third round round_limit=27. 
However, in the parameter space I defined 'batch_size': (2, 30, 10).
How do I get batch_sizes which where not defined as possible batch_size in the parameter dictionary?

Thank you

**Comment by mikkokotila** [comment]
Your question is not clear. What are you trying to achieve?

**Comment by BY-hash** [comment]
How come I get expirament results with parameters values that I have not defined as possible options in the parameter space
p = {'lr': (0.5, 5, 10), 'batch_size': (32, 64, 256,512, 128,1024)...}?
For example, for the definition 'batch_size': (2, 30, 10), I got expiramnet results with batch size 13 (not one of the defined possible options of 2/30/10?

**Comment by mikkokotila** [comment]
If you want to assign specific values, then you must use `[1,2,3]` and not `(1,2,3)`
