### ISSUE TITLE
siamese fit_generator error

### ISSUE THREAD

**Issue by prateeksaurabh** [autonomio/talos#510]
First off, make sure to check your [support options](https://github.com/autonomio/talos#-how-to-get-support).

The preferred way to resolve usage related matters is through the [docs](https://autonomio.github.io/talos/#/) which are maintained up-to-date with the latest version of Talos.

If you do end up asking for support in a new issue, make sure to follow the below steps carefully.

#### 1) Confirm the below

- [ ] I have looked for an answer in the [Docs](https://autonomio.github.io/talos)
- [ X] My Python version is 3.5 or higher
**3.7.9**

- [ X] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [X ] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__`
**0.6.4**

#### 3) Explain clearly what you are trying to achieve

*A description of your specific use-case and what you hope to achieve with it*
Hello Mikko Kotila, I earlier asked issue # [504](https://github.com/autonomio/talos/issues/504). Thanks i was somehow able to make it work. But then i realized my laptop was giving me screen of death due to memory issue so i searched online and figured out i should try using fit_generator instead of fit. So  right now i am trying that but since i was busy lately so could not take up that project. Now when i am trying fit_generator and i am getting error. Since i m still new to python/machine learning i think it could be more of python issue than talos issue but any assistance would be of great help.

#### 4) Explain what you have already tried
I was able to make keras standalone (without talos) to work with a single set of parameters. But problem happens when i try setting up parameter dictonary and then run the scan. Just for sake of it i tried changing multiple ways like a) Giving only set of parameter b) parameter giving as a list . Both the times i get different error. When using a) (i.e. only one set of value) i get error as 
**TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'**
when using b) (i.e. list of values for parameters) i get error as
**ValueError: The `kernel_size` argument must be a tuple of 1 integers. Received: [2, 4, 6]**

*An outline of the steps that you have already taken so far*

#### 5) Provide a code-complete reference

- [ X] My support question includes an input model
- [ X] My support question includes a parameter dictionary
- [X ] My support question includes a `Scan()` command
- [ ] My support question includes a link to a sample of the data
(I havent provided this because for that i need to import data to google drive and i dont have enough space but if required i will make some way to do this

NOTE: If the data is sensitive and can't be shared, [create dummy data](https://scikit-learn.org/stable/modules/classes.html#samples-generator) that mimics it.

**A self-contained Jupyter Notebook, Google Colab, or similar is highly preferred and will speed up helping you with your issue.**

https://colab.research.google.com/drive/1Twssq_MiQ4RxMZ69A595SFIgs4JhG18u?usp=sharing

**Comment by prateeksaurabh** [comment]
Ok when i run below command 

print (type((p['filter1'])))

Output is 
<class 'list'>

So that means i am giving list but python is looking for int. Either i have read incorrect document or i am not able to understand document properly . Seems i am unable to write parameter dictionary properly or could be something else. I have seen few other blogs and i written parameter dictionary as per that but they didnt get any error. Wondering what mistake i am making

**Comment by prateeksaurabh** [comment]
I was just checking one link https://www.kaggle.com/sohaibanwaar1203/talos-hyper-parameter-optimization In this the code is

params = {'lr': (0.1, 0.01,1 ),
     'epochs': [10,5,15],
     'dropout': (0, 0.40, 0.8),
     'optimizer': ["Adam","Adagrad","sgd"],
     'loss': ["binary_crossentropy","mean_squared_error","mean_absolute_error"],
     'last_activation': ["softmax","sigmoid"],
     'activation' :["relu","selu","linear"],
     'clipnorm':(0.0,0.5,1),
     'decay':(1e-6,1e-4,1e-2),
     'momentum':(0.9,0.5,0.2),
     'l1': (0.01,0.001,0.0001),
     'l2': (0.01,0.001,0.0001),
     'No_of_CONV_and_Maxpool_layers':[1,2],
     'No_of_Dense_Layers': [2,3,4],
     'No_of_Units_in_dense_layers':[64,32],
     'Kernal_Size':[(3,3),(5,5)],
     'Conv2d_filters':[60,40,80,120],
     'pool_size':[(3,3),(5,5)],
     'padding':["valid","same"]
    }
    lr = params['lr']
    epochs=params['epochs']
    dropout_rate=params['dropout']
    optimizer=params['optimizer']
    loss=params['loss']
    last_activation=params['last_activation']
    activation=params['activation']
    clipnorm=params['clipnorm']
    decay=params['decay']
    momentum=params['momentum']
    l1=params['l1']
    l2=params['l2']
    No_of_CONV_and_Maxpool_layers=params['No_of_CONV_and_Maxpool_layers']
    No_of_Dense_Layers =params['No_of_Dense_Layers']
    No_of_Units_in_dense_layers=params['No_of_Units_in_dense_layers']
    Kernal_Size=params['Kernal_Size']
    Conv2d_filters=params['Conv2d_filters']
    pool_size_p=params['pool_size']
    padding_p=params['padding']
OUTPUT

print (type((params['epochs'])))
<class 'list'>
So i see even in this blog the output is list so i dont understand why it is giving error.

**Comment by mikkokotila** [comment]
I had a look at your notebook. The error message appears to be related to your inputs, and not Talos. In both instances, the final message of the trace says clearly where and how your inputs have issues. Or did I misunderstand?

**Comment by mikkokotila** [comment]
Closing here. Feel free to open new issue if anything.
