### ISSUE TITLE
install path gone?

### ISSUE THREAD

**Issue by zzhulm** [autonomio/talos#519]
I tried to install talos by
pip install --use-feature=2020-resolver  git+https://github.com/autonomio/talos@1.0
it was working couple of days ago,but now seems a problem:

Collecting git+https://github.com/autonomio/talos@1.0
  Cloning https://github.com/autonomio/talos (to revision 1.0) to /tmp/pip-req-build-muko52zm
  WARNING: Did not find branch or tag '1.0', assuming revision or ref.
ERROR: Command errored out with exit status 1: git checkout -q 1.0 Check the logs for full command output.

is there something changed? 

Thank you very much for some clues!

some update of the problem, I found you released 1.0 version so I only need to pip install talos , right?
but there is some difference , it forced the upgrade to tensorflow 2.3.1 from 2.1  and because of the conda installation of the tensorflow it destroyed the dependency can it not working, do you have the switch not to update TF?
Thanks

**Comment by mikkokotila** [comment]
Yes, you can drop the `@1.0` and just use master. Also pypi is now 1.0. 

Closing here.

**Comment by zzhulm** [comment]
Thank you mikko, is that possible not to upgrade TF 2.1 to 2.3.1? when installing talos?
