### ISSUE TITLE
Empty x and y CSV with Deploy() make impossible to use Restore()

### ISSUE THREAD

**Issue by paloma-ecg** [autonomio/talos#521]
First off, make sure to check your [support options](https://github.com/autonomio/talos#-how-to-get-support).

The preferred way to resolve usage related matters is through the [docs](https://autonomio.github.io/talos/#/) which are maintained up-to-date with the latest version of Talos.

If you do end up asking for support in a new issue, make sure to follow the below steps carefully.

#### 1) Confirm the below

- [x] I have looked for an answer in the [Docs](https://autonomio.github.io/talos)
- [x] My Python version is 3.5 or higher
- [x] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [x] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__` '1.0.0'

#### 3) Explain clearly what you are trying to achieve

I want to store my Scan object with Deploy and then get it back with Restore it.

#### 4) Explain what you have already tried

I've tried using different names and objects, even restarting the kernel. I get the ZIP data after using Deploy(), obtaining the message that "data is not 2d, dummy data written instead". As x and y CSV are empty, Restore() fails when reading them. The training data has `X.shape` is (13125, 200, 1) and `y.shape` (13125, 105) as it is categorical with 105 classes.

I don't know if I'm using them wrong, but the Scan object data gets properly saved

#### 5) Provide a code-complete reference

- [x] My support question includes an input model
- [x] My support question includes a parameter dictionary
- [x] My support question includes a `Scan()` command
- [ ] My support question includes a link to a sample of the data

NOTE: If the data is sensitive and can't be shared, [create dummy data](https://scikit-learn.org/stable/modules/classes.html#samples-generator) that mimics it.

**A self-contained Jupyter Notebook, Google Colab, or similar is highly preferred and will speed up helping you with your issue.**

---
```
def Model(x, y, x_val, y_val, params):

    model = Sequential()
    steps_per_epoch = y.shape[0] // params['batch_size']
    validation_steps = x_val.shape[0] // params['batch_size']
    
    n_outputs = y.shape[1]
    #conv1D
    model.add(Conv1D(filters = params['filters']*16, kernel_size = params['kernel_size'], 
                        strides = params['strides'], batch_input_shape = (None, x.shape[1], x.shape[2])))
    #model.add(BatchNormalization())
    #model.add(Activation('tanh'))
    #model.add(Dropout(0.5))

    # Recurrent layer
    #model.add(Dropout(params['dropout']))
    model.add(LSTM(units = params['hidden_units']*2, return_sequences = True))
    model.add(Dropout(params['dropout']))
    #model.add(LSTM(units = n_h*2, return_sequences = True))
    model.add(LSTM(units = params['hidden_units'], return_sequences = False))

    model.add(Dropout(params['dropout']))
    #model.add(BatchNormalization())
    #model.add(Dropout(0.1))
    #Dropout for regularization
    model.add(Dense(n_outputs, activation = 'softmax'))
    model.summary()
    # Compile the model
    #if params['optimizer'] == "Adam": añadir LR
    model.compile(optimizer=params['optimizer'], loss=params['loss'], metrics=['accuracy'])

    history = model.fit(x, y, epochs = params['epochs'], batch_size = params['batch_size'], 
                        steps_per_epoch = steps_per_epoch, callbacks = [early_stopper(params['min_delta'], patience=10, monitor = 'loss')],
                       validation_data = (x_val, y_val), validation_steps = validation_steps)
    
    return history, model

p = {'hidden_units':[4, 8, 16, 32, 64, 128],
     'batch_size': [50, 100, 150],
     'kernel_size': [5, 7, 9],
     'strides': [1, 2, 3],
     'epochs': [30, 40, 50],
     'dropout': [0, 0.2, 0.4, 0.6, 0.8],
     'optimizer': ['Adam', 'Nadam'],
     'kernel_initializer': ['uniform','normal'],
     'loss': ['categorical_crossentropy'],
     'last_activation': ['softmax'],
     'weight_regulizer': [None],
      'min_delta': [0.001],
      'filters': [1, 2, 3, 4]}

#2D data and numeric labels, make it suitable for the model
X = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
y = to_categorical(y_train)

scan_object = talos.Scan(x=X, y=y, params=p, model=Model, experiment_name = 'first', val_split = .2, round_limit = 3, print_params = True)

a = talos.Deploy(scan_object, 'first_try', 'val_accuracy')

object = talos.Restore('first_try.zip')
```

**Comment by mikkokotila** [comment]
You have to provide one of: 

- original data
- dummy data of the same shape
- command to produce dummy data of the same shape

**Comment by mikkokotila** [comment]
Closing this for lack activity. Feel free to re-open if still relevant.

**Comment by paleboot** [comment]
Sorry for necro-ing, I hope this is okay. I encountered the same problem, `Restore()` would fail due to empty `*_x.csv` and `*_y.csv`. Data is of 4D shape `(5118, 83, 768, 1)`, producible using the command `np.random.rand(5118, 83, 768, 1)`.

`thalos v1.0.0`
