### ISSUE TITLE
Multiple Inputs example can't run 

### ISSUE THREAD

**Issue by zzhulm** [autonomio/talos#526]
your documented example https://autonomio.github.io/talos/#/Examples_Multiple_Inputs
can't run,  first i have to change 
from tensorflow.keras.layers.merge import concatenate 
to 
from tensorflow.keras.layers  import concatenate

after that the scan call gets error
TypeError: __init__() missing 1 required positional argument: 'experiment_name'

is there anything wrong in the code or my installation issue.

Thanks

**Comment by zzhulm** [comment]
after adding experiment_name argument it can run, but i still  quite understand 1) this experiment_name argument is not needed as stated in the manual, and also experiment_name  was not listed in the manual,https://autonomio.github.io/docs_talos/#scan
2) however according to this manual  "functional_model=True" shold be needed for this example but it rejected as
"TypeError: __init__() got an unexpected keyword argument 'functional_model'"

was this docs obsolete? 

Thank you

**Comment by zzhulm** [comment]
your documents on the multi input case above seems  too simple which didn't show how to handle the real multi inputs conditions.
I tried out modifying some line to show the real 2 input,
def iris_multi(x_train, y_train, x_val, y_val, params):

    # the first side of the network
    first_input = Input(x_train[0].shape[1])
    first_hidden1 = Dense(params['left_neurons'], activation=params['activation'])(first_input)
    first_hidden2 = Dense(params['left_neurons'], activation=params['activation'])(first_hidden1)

    # the second side of the network
    second_input = Input(x_train[1].shape[1])
    second_hidden1 = Dense(params['right_neurons'], activation=params['activation'])(second_input)
    second_hidden2 = Dense(params['right_neurons'], activation=params['activation'])(second_hidden1)
    third_hidden2 = Dense(params['right_neurons'], activation=params['activation'])(second_hidden2)

    # merging the two networks
    merged = concatenate([first_hidden2, first_hidden2])

    # creating the output
    output = Dense(3, activation='softmax')(merged)

    # put the model together, compile and fit
    model = Model(inputs=[first_input, second_input], outputs=output)
    model.compile('adam',
                  'binary_crossentropy',
                  metrics=['acc', talos.utils.metrics.f1score])

    out = model.fit(x=x_train,
                    y=y_train,
                    validation_data=[x_val, y_val],
                    epochs=150,
                    batch_size=params['batch_size'],
                    verbose=0)

    return out, model


I believe  first_input = Input(x_train[0].shape[1]),  second_input = Input(x_train[1].shape[1])
make more sense, and it runs,  let me know any problem with that

Thank you

**Comment by mikkokotila** [comment]
Thank you, [https://autonomio.github.io/docs_talos/#scan](https://autonomio.github.io/docs_talos/#scan) was old docs, that is now deleted. 

Can you create an example in Google Colab for the model, so that it runs and is self-contained, and I will replace the current one with that, with reference to the notebook. I think all the examples should live on colab so people can play with it right there and then.
