### ISSUE TITLE
KeyError: 'metrics'      (in talos scan)

### ISSUE THREAD

**Issue by qboy21** [autonomio/talos#527]
@mikkokotila Sorry. The same issue persists. Here is my function, parameter space and experiment error. have you tested talos on the latest version of jupyter notebook?
## first we have to make sure to input data and params into the function
def talos_model(x_train, y_train, x_val, y_val, params):

    model = Sequential()
    model.add(LSTM(params['first_neuron'], input_shape=(X_train_seq.shape[1], X_train_seq.shape[2]),
                   kernel_initializer=params['kernel_initializer']))
    
    model.add(Dropout(params['dropout']))
    
    model.add(Dense(params['second_neuron'], activation=params['last_activation'],kernel_initializer=params['kernel_initializer']))
    
    model.add(Dropout(params['dropout']))
    
    model.add(Dense(params['third_neuron'], activation=params['last_activation'],kernel_initializer=params['kernel_initializer']))
    
    model.add(Dense(1, activation=params['last_activation'],kernel_initializer=params['kernel_initializer']))
    
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc', talos.utils.metrics.f1score])
    
    history = model.fit(X_train_seq, y_train_seq, validation_data=[X_test_seq, y_test_seq], batch_size=params['batch_size'],
                        callbacks=[talos.utils.live()], epochs=params['epochs'], verbose=0, shuffle=False)

    return history, model

## then we can go ahead and set the parameter space
p = {'first_neuron':[20,30,50],
     'second_neuron':[6,8,10],
     'third_neuron':[2,4],
     'hidden_layers':[2,3],
     'batch_size': [31,45,60],
     'epochs': [110,130,170],
     'dropout': [0.1,0.3],
     'kernel_initializer': ['normal'],     
     'activation':['relu', 'elu'],
     'last_activation': ['sigmoid']}

## and run the experiment
t = talos.Scan(x=X_train_seq,y=y_train_seq,model=talos_model, params=p, experiment_name='talos_test', round_limit=10)

# ERROR:

KeyError                                  Traceback (most recent call last)
<ipython-input-89-7c040af62ff2> in <module>
      1 # and run the experiment
----> 2 t = talos.Scan(x=X_train_seq,y=y_train_seq,model=talos_model, params=p, experiment_name='talos_test', round_limit=10)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/talos/scan/Scan.py in __init__(self, x, y, params, model, experiment_name, x_val, y_val, val_split, random_method, seed, performance_target, fraction_limit, round_limit, time_limit, boolean_limit, reduction_method, reduction_interval, reduction_window, reduction_threshold, reduction_metric, minimize_loss, disable_progress_bar, print_params, clear_session, save_weights)
    194         # start runtime
    195         from .scan_run import scan_run
--> 196         scan_run(self)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/talos/scan/scan_run.py in scan_run(self)
     24         # otherwise proceed with next permutation
     25         from .scan_round import scan_round
---> 26         self = scan_round(self)
     27         self.pbar.update(1)
     28 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/talos/scan/scan_round.py in scan_round(self)
     17     # fit the model
     18     from ..model.ingest_model import ingest_model
---> 19     self.model_history, self.round_model = ingest_model(self)
     20     self.round_history.append(self.model_history.history)
     21 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/talos/model/ingest_model.py in ingest_model(self)
      4     through Scan() model paramater.'''
      5 
----> 6     return self.model(self.x_train,
      7                       self.y_train,
      8                       self.x_val,

<ipython-input-87-7deb9ca98486> in talos_model(x_train, y_train, x_val, y_val, params)
     18     model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc', talos.utils.metrics.f1score])
     19 
---> 20     history = model.fit(X_train_seq, y_train_seq, validation_data=[X_test_seq, y_test_seq], batch_size=params['batch_size'],
     21                         callbacks=[talos.utils.live()], epochs=params['epochs'], verbose=0, shuffle=False)
     22 

~/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

~/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1077       train_function = self.make_train_function()
   1078       self._train_counter.assign(0)
-> 1079       callbacks.on_train_begin()
   1080       training_logs = None
   1081       # Handle fault-tolerance for multi-worker.

~/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/callbacks.py in on_train_begin(self, logs)
    499         if numpy_logs is None:  # Only convert once.
    500           numpy_logs = tf_utils.to_numpy_or_python_type(logs)
--> 501         callback.on_train_begin(numpy_logs)
    502 
    503   def on_train_end(self, logs=None):

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/kerasplotlib/traininglog.py in on_train_begin(self, logs)
     31 
     32     def on_train_begin(self, logs={}):
---> 33         self.base_metrics = [metric for metric in self.params['metrics'] if not metric.startswith('val_')]
     34         if self.figsize is None:
     35             self.figsize = (

KeyError: 'metrics'

_Originally posted by @qboy21 in https://github.com/autonomio/talos/issues/503#issuecomment-748510095_

**Comment by mikkokotila** [comment]
Can you create a [Colab notebook](https://colab.research.google.com/) that demonstrates the issue. 

Make sure to `!pip install talos` first.

**Comment by qboy21** [comment]
sure. I will create a notebook edited from my current one.
