### ISSUE TITLE
Using regularizers in talos with hidden layers function 

### ISSUE THREAD

**Issue by USAMAH1989** [autonomio/talos#539]
Dear Sir:

This Osama ALAtawneh, I am one of the users of your great optimization tool (talos). First of all, let me thank you for this nice tool that collected all of the optimization parameters in one experiment (run), specially neural network shape. I am writing to discuss with about the following questions that I faced through working on talos.

How could I define a range or discrete values for regularizes as an optimization parameter for hidden layers when I use hidden layers function?
Why did you enforce the hidden layer function to only use Dense layers not other types, and how could I use this function for other types of hidden layers like convolutional or LSTM layers?
I am looking forward to hear from you very soon.

Warm Regards,

**Comment by mikkokotila** [comment]
To work with layers, the preferred method is to do it inside your input model. So for example, you might have something like: 

```

param_dict = {
    ...
    'custom_hidden_layer': ['a', 'b']
    ...

}

```

And then your input model:

```
def input_model():
    ...
    if params['custom_hidden_layer'] == 'a':
        some_layer()
    elif params['custom_hidden_layer'] == 'b':
        some_other_layer()
    ...

```
It's useful to keep in mind that Talos is very flexible in the way it allows you to create any custom functions inside the input model :)

**Comment by mikkokotila** [comment]
Closing here. Feel free to open new issue if anything :)
