### ISSUE TITLE
How to use regularizers in hidden layers in Talos?

### ISSUE THREAD

**Issue by USAMAH1989** [autonomio/talos#542]
Dear Sir:
First of all, thank you so much for your quick response for issue number #539. Actually, I am still confused about how to optimize the regularizes when I use hidden layers generator as shown in Pic1 and Pic2. When I used the method shown in the attached pictures, the hidden layers generated by the generator did not include any regularizer inside when I opened the model.

![Pic 1](https://user-images.githubusercontent.com/52557059/107876628-bcd08580-6ecf-11eb-907b-0b8f965a544a.png)
![Pic2](https://user-images.githubusercontent.com/52557059/107876630-bd691c00-6ecf-11eb-9f7a-e2ec447a46af.png)

Osama ALAtawneh
02/14/2021

**Comment by mikkokotila** [comment]
Ah ok, I understand, what you are doing above, will not apply the regularizer into hidden layers via the Talos function `hidden_layers`. You don't need it, you can just handle all of that procedure in a loop, and then wrap the part with regularizers inside that loop.

**Comment by mikkokotila** [comment]
Closing here, feel free to open new ticket if anything.
