### ISSUE TITLE
Resume run possible?

### ISSUE THREAD

**Issue by zonexo** [autonomio/talos#545]
Hi,

my sch cluster restricts run to 24hr per job. So is it possible to implement some sort of resume from previous stopping point?

If so, how is it done?

Thanks!

**Comment by mikkokotila** [comment]
Related with #482 and #97. I think time to decide what to do with this.

At the moment, the "best" way would be to split the experiment into multiple experiments and then join the CSV logs at the end.

**Comment by zonexo** [comment]
ok thanks for the update!
