### ISSUE TITLE
Key duplication results in exception: param dict vs. csv file stored (e.g., 'loss')

### ISSUE THREAD

**Issue by zazula** [autonomio/talos#547]
Thank you very much for reporting a bug on Talos. Before you do, please go through the below checklist carefully and make sure to prepare your bug report in a way that facilitates effective handling of the matter.

#### 1) Confirm the below

- [ X] My Python version is 3.5 or higher
- [ X] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [ X] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__`
1.0.0

#### 3) Explain clearly what you expect to happen
Run a test using my hand-built param dictionary.  One of the keys is 'loss'.  I expected it to work.

#### 4) Explain what actually happened
Crash/exception : DataFrame has no member dtype

/opt/homebrew/Caskroom/miniforge/base/envs/jupyter-tf-m1/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5463             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5464                 return self[name]
-> 5465             return object.__getattribute__(self, name)
   5466 
   5467     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'dtype'

I added some logging to the code and discovered:

<class 'pandas.core.frame.DataFrame'>        loss      loss       metrics optimizer  rnn_alpha  \
0  0.729397  0.729397  ['accuracy']   adagrad        1.0   
1  0.193052  0.193052  ['accuracy']   adagrad        1.0   
2  1.082447  1.082447  ['accuracy']   adagrad        1.0   
3  0.768457  0.768457  ['accuracy']   adagrad        1.0   

<class 'pandas.core.frame.DataFrame'>        loss      loss       metrics optimizer  rnn_alpha  \
0  0.729397  0.729397  ['accuracy']   adagrad        1.0   
1  0.193052  0.193052  ['accuracy']   adagrad        1.0   
2  1.082447  1.082447  ['accuracy']   adagrad        1.0   
3  0.768457  0.768457  ['accuracy']   adagrad        1.0   
[...]
<class 'str'> loss
<class 'pandas.core.frame.DataFrame'>

Changing my param dict key to 'lossx' resolved the issue.

Notice the two columns labeled 'loss'.  This causes data['loss'] to return a 2-column pd.DataFrame instead of a 1-column pd.Series, which results in the DataFrame / dtype error.

**Comment by mikkokotila** [comment]
Can you share Google collab where I can run the code and investigate. If the data is sensitive, can use dummy data as long as it reproduces the issue.

**Comment by zazula** [comment]
I haven't used collab before.  I can take  a look, but the repro steps are:

1. add a key 'loss' and any value to your param dict
2. run

It will raise the exception I mentioned as Talos is using the key 'loss' for something internal.

**Comment by mikkokotila** [comment]
@zazula can you try calling it `losses` instead of `loss`.
