### ISSUE TITLE
Heatmap always have missing parts

### ISSUE THREAD

**Issue by BY-hash** [autonomio/talos#549]
Hello'

regardless of the number of experiments/their configuration, there is always 2 emty boxes in the map (each time different metrics), even if the number of their options is larger than one.
For example:
![image](https://user-images.githubusercontent.com/51758806/118540186-0348b100-b759-11eb-8bc1-a7a497577664.png)

What could be causing this?

Thank you!

**Comment by mikkokotila** [comment]
Yes, that happens. Because it does not make any functional difference, it is unlikely that it will be handled. One option would be to remove the masking, in which case it will be square shape as opposed to triangle. What do you think?

**Comment by BY-hash** [comment]
Good, Thank you!
