### ISSUE TITLE
add arguments to the function syntax

### ISSUE THREAD

**Issue by jioyoung** [autonomio/talos#556]
now there are five arguments in the talos model (x_train, y_train, x_val, y_val, params). However, if I want to add an argument that will be used in the dnn building in that function and that argument cannot be put in the "params", it is not supported now. Am I right? Thank you very much!

**Comment by mikkokotila** [comment]
You can put it inside your parameter dictionary, and then call it inside the input model as you like. This makes it possible to pass anything and everything to be processed in the model :) 

Closing here, feel free to open a new issue if anything.
