### ISSUE TITLE
Using train, val data

### ISSUE THREAD

**Issue by orko19** [autonomio/talos#557]
Hi , 
I read your tutorials and I don't understand the relation between x, y, x_train, y_train, x_val and y_val in your framework.
For example, here:
https://nbviewer.jupyter.org/github/autonomio/talos/blob/master/examples/A%20Very%20Short%20Introduction%20to%20Hyperparameter%20Optimization%20of%20Keras%20Models%20with%20Talos.ipynb
The function:
`def diabetes(x_train, y_train, x_val, y_val, params):
`
get the arguments : `x_train, y_train, x_val, y_val`
But uses x,y in the `.fit` method within it.
Moreover, in the line
`t = talos.Scan(x=x, y=y, params=p, model=diabetes, experiment_name='diabetes')
`
What are x,y?
Are they `x_train, y_train`?

**Comment by mikkokotila** [comment]
You should not mix two different concepts. One concept is the input mode `def diabetes(...)` which is an input to `Scan()`. `x` and `y` in `Scan()` are automatically handled to become `x_train`, `y_train` and so on in the input model. 

Closing here. Feel free to open new issue if anything.
