### ISSUE TITLE
Cannot replicate typical example from documentation

### ISSUE THREAD

**Issue by dragarok** [autonomio/talos#558]
Thank you very much for reporting a bug on Talos. Before you do, please go through the below checklist carefully and make sure to prepare your bug report in a way that facilitates effective handling of the matter.

#### 1) Confirm the below

- [x] My Python version is 3.5 or higher
- [x] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [x] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos.__version__`
1.0.0
`tensorflow.__version__`
2.6.0

#### 3) Explain clearly what you expect to happen

*I tried replicating the minimal example provided in the Talos docs. It should have ran successfully.*

#### 4) Explain what actually happened

*First it throws an error about experiment_name parameter. After adding that one, it threw an error regarding input.*

>   ValueError: Layer sequential_1 expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 4) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 3) dtype=float32>]

**Comment by mikkokotila** [comment]
Can you run it on Google Colab, and if you still have an share the link to the notebook in case you have an issue.
