### ISSUE TITLE
Can't find description of layer shapes 

### ISSUE THREAD

**Issue by bobyfisch** [autonomio/talos#561]
Hi,

First of all thanks for this great optimization tool for Keras, it's exactlly what I was looking for.

Sorry for placing this as an issue, I'm not sure if it would be more appropriatelly placed in discussions as it is more of a "documetnation" issue: I've been looking around the TALOS documents and I can't find any description of the available layer shapes for the hidden_layers method (https://autonomio.github.io/talos/#/Hidden_Layers?id=hidden_layers-arguments) and what each layer shape actually means for the hidden layers that it initialises.

From the names I can more or less have an intuition of what they are each doing, for example i assume 'triangle' is reducing layer shape linealy from the first layer onwards while 'funnel' is reducing it with a squared or log function - but I would like to know exactlly what each is doing.

Apart from this I have another separate request for you, could I please get the complete code that you worked with for: https://towardsdatascience.com/hyperparameter-optimization-with-keras-b82e6364ca53 I think maybe an upload of the complete code to the article would be usefull to many people. Personally i have noticed that the TALOS part of the article needs some updating when executing with the current version, but I am more interested in the commands you used to draw all the graphics. 

Thank you very much for your great work @mikkokotila!

**Comment by bobyfisch** [comment]
Found the answer by looking at the source code in : https://github.com/autonomio/talos/blob/master/talos/model/network_shape.py, however including a description of this in the docs would be great. 

Also, found some graphing function examples at: https://github.com/autonomio/talos/blob/master/talos/commands/analyze.py any more info on these utils or the notebook for the above exmaple from the twds blog, would be great, thanks!

**Comment by mikkokotila** [comment]
In the docs you will find a brief description of how to use `shapes` in [here](https://autonomio.github.io/talos/#/Hidden_Layers?id=shapes). I would not use the pre-made shapes though, but rather use the numeric inputs where you have full control.

Closing here, feel free to open new issue if anything.

**Comment by mikkokotila** [comment]
In the docs you will find a brief description of how to use `shapes` in [here](https://autonomio.github.io/talos/#/Hidden_Layers?id=shapes). I would not use the pre-made shapes though, but rather use the numeric inputs where you have full control.

Closing here, feel free to open new issue if anything.
