### ISSUE TITLE
AttributeError: module 'talos.utils' has no attribute 'ExperimentLogCallback'

### ISSUE THREAD

**Issue by bellegdi** [autonomio/talos#589]
I got the following error 
AttributeError: module 'talos.utils' has no attribute 'ExperimentLogCallback'

Please see the code below
`
    history = model.fit(x=train_imgs_scaled, y=train_labels_ohe,
                    validation_data=(validation_imgs_scaled, validation_labels_ohe),
                            batch_size=200,
                            epochs=10,
                            callbacks=[talos.utils.ExperimentLogCallback('kgt', params)],
                            verbose=1)
`
The complete code is available at the link
https://github.com/Kopfgeldjaeger/Medium_blogs_code/tree/master/2_talos_grid_search

I am using Colab. 
The Talos version is 1.3.

**Comment by mikkokotila** [comment]
You have to use `talos.callbacks.ExperimentLog()` instead. This was changed in `1.3`. Sorry for the inconvenience. Closing here, feel free to open new issue if anything.
