### ISSUE TITLE
Live is not in talos

### ISSUE THREAD

**Issue by CarlosDLMC** [autonomio/talos#590]
Hi!
I am having this problem
from talos import live
is returning an error as well.

The solution you proposed in another issue (from talos.utils import live) or (talos.utils.live()) is not working anymore.
Please, can you tell me how to solve this issue?
Also, this import
from talos.metrics.keras_metrics import fmeasure_acc
is returning an error.

Thanks for your help!

**Comment by mikkokotila** [comment]
You can just directly use the callback from `talos.callbacks.TrainingPlot()`. Closing here, feel free to open new issue if anything.
