### ISSUE TITLE
Error with Autom8 import

### ISSUE THREAD

**Issue by bwalsh1191** [autonomio/talos#592]
Thank you very much for reporting a bug on Talos. Before you do, please go through the below checklist carefully and make sure to prepare your bug report in a way that facilitates effective handling of the matter.

#### 1) Confirm the below

- [ X] My Python version is 3.5 or higher
- [x ] I have searched through the issues [Issues](https://github.com/autonomio/talos/issues) for a duplicate
- [ X] I've tested that my Keras model works as a stand-alone

#### 2) Include the output of:

`talos 1.3`

#### 3) Explain clearly what you expect to happen

when I attempt to follow the docs using Autom8 for param dictionary, using the examples provided, I expect to automatically create a param dictionary. 

#### 4) Explain what actually happened

I get an error `module talos has no attribute Autom8`

#### 5) Provide a code-complete reference

`import talos`
`import wrangle`
`p=talos.Autom8.AutoParams().params`

- [ ] My bug report includes an input model
- [ ] My bug report includes a parameter dictionary
- [ ] My bug report includes a `Scan()` command
- [ ] My bug report question includes a link to a sample of the data

NOTE: If the data is sensitive and can't be shared, [create dummy data](https://scikit-learn.org/stable/modules/classes.html#samples-generator) that mimics it or provide a command for generating it.

**A self-contained Jupyter Notebook, Google Colab, or similar is highly preferred and will speed up helping you with your issue.**

---

**Comment by mikkokotila** [comment]
Sorry, try with `p = talos.autom8.AutoParams().params`. 

Closing here. Feel free to open a new one anytime.
