### ISSUE TITLE
How use Talos with custom model declaration f.ex. model=Model() and not model = Sequential()

### ISSUE THREAD

**Issue by Jakedismo** [autonomio/talos#65]
Made some progress and got the scan running, initial problems were due to giving single integers as parameter and the scan was trying to iterate over a list of parameter values, but now I've run to a new error which is caused propably my model declaration (using model = Model(), in examples you use model=Sequential() etc.).
I take predictions from the model this way:

> autoencoder.predict(x=[train_x, np.array(train_items, dtype=np.int32).reshape(len(train_items), 1)])

- [ x] I'm up-to-date with the latest release:
    
      pip install -U talos

- [ x] I've confirmed that my Keras model works outside of Talos.

> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-97-56bd801e0b68> in <module>()
>       7             params=p,
>       8             dataset_name='movie_lens',
> ----> 9             experiment_no='1')
> 
> C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\scan\Scan.py in __init__(self, x, y, params, dataset_name, experiment_no, model, x_val, y_val, val_split, shuffle, search_method, reduction_method, reduction_interval, reduction_window, grid_downsample, reduction_threshold, reduction_metric, round_limit, talos_log_name, debug, seed, clear_tf_session, disable_progress_bar)
>     140         # input parameters section ends
>     141 
> --> 142         self._null = self.runtime()
>     143 
>     144     def runtime(self):
> 
> C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\scan\Scan.py in runtime(self)
>     145 
>     146         self = scan_prepare(self)
> --> 147         self = scan_run(self)
> 
> C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\scan\scan_run.py in scan_run(self)
>      27                      disable=self.disable_progress_bar)
>      28     while len(self.param_log) != 0:
> ---> 29         self = rounds_run(self)
>      30         self.pbar.update(1)
>      31     self.pbar.close()
> 
> C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\scan\scan_run.py in rounds_run(self)
>      59 
>      60     _hr_out = run_round_results(self, _hr_out)
> ---> 61     self._val_score = get_score(self)
>      62     write_log(self)
>      63     self.result.append(_hr_out)
> 
> C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\metrics\score_model.py in get_score(self)
>      15 
>      16     try:
> ---> 17         y_pred = self.keras_model.predict_classes(self.x_val)
>      18         return Performance(y_pred, self.y_val, self.shape, self.y_max).result
>      19 
> 
> AttributeError: 'Model' object has no attribute 'predict_classes'

**Comment by Jakedismo** [comment]
Blah now I get a CAfile error because Git is trying to use my private repo key

**Comment by Jakedismo** [comment]
It's roughly the same model as this 

from keras.layers import Input, Dense, Embedding, Flatten, Dropout, merge, Activation
from keras.models import Model
from keras.regularizers import l2

```
def create(I, U, K, hidden_activation, output_activation, q=0.5, l=0.01):
    '''
    create model
    Reference:
      Yao Wu, Christopher DuBois, Alice X. Zheng, Martin Ester.
        Collaborative Denoising Auto-Encoders for Top-N Recommender Systems.
          The 9th ACM International Conference on Web Search and Data Mining (WSDM'16), p153--162, 2016.
    :param I: number of items
    :param U: number of users
    :param K: number of units in hidden layer
    :param hidden_activation: activation function of hidden layer
    :param output_activation: activation function of output layer
    :param q: drop probability
    :param l: regularization parameter of L2 regularization
    :return: CDAE
    :rtype: keras.models.Model
    '''
    x_item = Input((I,), name='x_item')
    h_item = Dropout(q)(x_item)
    h_item = Dense(K, W_regularizer=l2(l), b_regularizer=l2(l))(h_item)

    # dtype should be int to connect to Embedding layer
    x_user = Input((1,), dtype='int32', name='x_user')
    h_user = Embedding(input_dim=U, output_dim=K, input_length=1, W_regularizer=l2(l))(x_user)
    h_user = Flatten()(h_user)

    h = merge([h_item, h_user], mode='sum')
    if hidden_activation:
        h = Activation(hidden_activation)(h)
    y = Dense(I, activation=output_activation)(h)

    return Model(input=[x_item, x_user], output=y)
```
Just slight modifications to return history and model

**Comment by x94carbone** [comment]
@Jakedismo just to clarify, this is a known issue and is addressed in the version of Talos that @mikkokotila posted. Basically there was a catch-all statement that spit out the error message you're seeing regardless of the error.

If what you posted above is the model function you're trying to import to Talos, it won't work because the arguments are not in the right format.

Also, in a more recent version of Talos (on the `Master` branch) you can manually specify the validation and training sets independently if you want.

Does this help at all?

**Comment by Jakedismo** [comment]
So I got talos installed from masterbranch have been running to some erros I'm using parameter like this: 
```
 I=train_x.shape[1]
U=len(train_items)

p = {  'K': [20, 50],
          'hidden_activation':['relu','tanh','elu'],
          'output_activation': 'sigmoid',
          'q': [0.5, 0.2, 0.05, 0.001],
          'l': [0.1,0.01,0.001,0.0001],
          'loss': ['mean_absolute_error','categorical_crossentropy','logcosh'],
          'optimizer': ['Adam, Nadam'],
          'n_epochs': [100],
          'batch_size':[64,128,256]}
```
But I keep getting errors like this, atleast from parameters q and l and the datasets. Would really like to try this out before I resort to writing a SGD algorithm for the hyperparameter optimization.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-64-a37e658c4580> in <module>()
      5         model=item_ae_model,
      6         dataset_name='first_test',
----> 7         experiment_no='k', debug=True)

C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\scan\Scan.py in __init__(self, x, y, params, dataset_name, experiment_no, model, x_val, y_val, val_split, shuffle, search_method, reduction_method, reduction_interval, reduction_window, grid_downsample, reduction_threshold, reduction_metric, round_limit, talos_log_name, debug, seed, clear_tf_session, disable_progress_bar)
    140         # input parameters section ends
    141 
--> 142         self._null = self.runtime()
    143 
    144     def runtime(self):

C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\scan\Scan.py in runtime(self)
    145 
    146         self = scan_prepare(self)
--> 147         self = scan_run(self)

C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\scan\scan_run.py in scan_run(self)
     27                      disable=self.disable_progress_bar)
     28     while len(self.param_log) != 0:
---> 29         self = rounds_run(self)
     30         self.pbar.update(1)
     31     self.pbar.close()

C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\scan\scan_run.py in rounds_run(self)
     48 
     49     # compile the model
---> 50     _hr_out, self.keras_model = ingest_model(self)
     51 
     52     # create log and other stats

C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\talos\model\ingest_model.py in ingest_model(self)
      5                       self.x_val,
      6                       self.y_val,
----> 7                       self.round_params)

<ipython-input-63-6cf243f8a2b8> in item_ae_model(train_x, train_y, val_x, val_y, params)
     28     history = model.fit(x=train_x, y=train_y,
     29                        batch_size=params['batch_size'], epochs=params['n_epochs'], verbose=1,
---> 30                        validation_data=[val_x, val_y])
     31                        #validation_data=[[test_x, test_x_items], test_x])
     32 

C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1703                               initial_epoch=initial_epoch,
   1704                               steps_per_epoch=steps_per_epoch,
-> 1705                               validation_steps=validation_steps)
   1706 
   1707     def evaluate(self, x=None, y=None,

C:\ProgramData\Anaconda3\envs\DataScienceEnv\lib\site-packages\keras\engine\training.py in _fit_loop(self, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
   1175                 indices_for_conversion_to_dense.append(i)
   1176 
-> 1177         for epoch in range(initial_epoch, epochs):
   1178             # Reset stateful metrics
   1179             for m in self.stateful_metric_functions:

TypeError: 'numpy.str_' object cannot be interpreted as an integer

**Comment by Jakedismo** [comment]
```
ta.Scan([train_x, train_x_items], train_x,
        x_val=[test_x, test_x_items],
        y_val = test_x,
        params=p,
        model=item_ae_model,
        dataset_name='first_test',
        experiment_no='k', debug=True)
```

**Comment by Jakedismo** [comment]
`def DAE_CF(x_train, y_train, x_val, y_val, params):
    #model = Model()
    user_input = Input((train_x.shape[1],), name='user_input')
    #model.add(user_input)
    h_user = Dropout(1)(user_input)
    #model.add(h_user)
    #h_item = Embedding(input_dim=I, output_dim=K, input_length=1, W_regularizer=l2(l))(item_input)
    encoded = Dense(50, W_regularizer=l2(params['lr']), b_regularizer=l2(params['lr']))(h_user)
    #model.add(encoded)
    
    item_input = Input((1,), dtype='int32', name='item_input')
    #model.add(item_input)
    h_item = Embedding(input_dim=len(y_train), output_dim=50, input_length=1, W_regularizer=l2(params['lr']))(item_input)
    #model.add(h_item)
    decoded = Flatten()(h_item)
    #model.add(decoded)

    h = merge([encoded, decoded], mode='sum')
    if hidden_activation:
        h = Activation(params['hidden_activation'])(h)
    y = Dense(train_x.shape[1], activation=params['output_activation'])(h)
    #model.add(y)
    model = Model(input=[user_input, item_input], output=y) 
    #model.add(autoencoder)
    
    encoder = Model(user_input, encoded)
    encoded_input = Input((50,), name='encoded_input')
    decoder_layer = autoencoder.layers[-1]
    decoder = Model(encoded_input, decoder_layer(encoded_input))

    model.compile(loss=params['loss'], optimizer=params['optimizer'], metrics=[metrics.rmse, 'accuracy'])
    history = autoencoder.fit(x=x_train, y=y_train,
                       batch_size=batch_size, epochs=n_epochs, verbose=1,
                       validation_data=[x_val, y_val])
    return history, model`

**Comment by timvhamme** [comment]
Same problem here. I have not a Sequential model, but a Model(), a Model has not got a predict_classes(). I;m using Keras 2.2.0

  File "/usr/local/lib/python3.5/dist-packages/talos/scan/Scan.py", line 142, in __init__
    self._null = self.runtime()
  File "/usr/local/lib/python3.5/dist-packages/talos/scan/Scan.py", line 147, in runtime
    self = scan_run(self)
  File "/usr/local/lib/python3.5/dist-packages/talos/scan/scan_run.py", line 29, in scan_run
    self = rounds_run(self)
  File "/usr/local/lib/python3.5/dist-packages/talos/scan/scan_run.py", line 61, in rounds_run
    self._val_score = get_score(self)
  File "/usr/local/lib/python3.5/dist-packages/talos/metrics/score_model.py", line 17, in get_score
    y_pred = self.keras_model.predict_classes(self.x_val)
AttributeError: 'Model' object has no attribute 'predict_classes'

**Comment by PTerrier** [comment]
@timvhamme,  I found a solution for this problem: modify the score_model.py file as follows

    from .performance import Performance

    def get_score(self):

    #y_pred = self.keras_model.predict_classes(self.x_val)  # not supported by Model()
    y_prob = self.keras_model.predict(self.x_val)    # supported by Model()
    y_pred = y_prob.argmax(axis=-1)  # return the class
    return Performance(y_pred, self.y_val, self.shape, self.y_max).result

**Comment by mikkokotila** [comment]
This is related with #39, #42 and #64. It looks like in #64 we've just agreed to add this fix as a parameter into Talos. Should have it pushed to dev over the next few days. The way it will work is to to use:

`experimental_functional_support=True` 

...in Scan()

**Comment by mikkokotila** [comment]
This is now [fixed](https://github.com/autonomio/talos/commit/d9b2c0b90d4f749152f0389a559dfd412e0a9e79) in the current dev branch.
