### ISSUE TITLE
How to get the scan results? 

### ISSUE THREAD

**Issue by kazlink** [autonomio/talos#69]
The scan works just fine for me but I'm not able to get the results. In one of the examples, Reporting class is used to retreive results from a csv but there's no code how to get that csv filled with the scan results.

**Comment by mikkokotila** [comment]
Depending on the dataset_name and experiment_no parameters in Scan() you are going to get an experiment log for example iris_1.csv and then you have to: 

```
import talos as ta
ta.Reporting(iris_1.csv)
```

**Comment by kazlink** [comment]
Thank you. I have found that file in the working directory.
