### ISSUE TITLE
Reporting of loss and accuracy 

### ISSUE THREAD

**Issue by C0NTRIBUTE** [autonomio/talos#7]
This is now handled in a way where both accuracy and loss are reported in terms of the peak epoch, which will automatically result in having a very high loss because it tends to report the first epoch loss. As an intermediate solution maybe can check the string label in the dictionary, and it it contains loss, take the minimum, and otherwise take the maximum. Accuracy is harder as it often does not have the word acc.

**Comment by mikkokotila** [comment]
This is now somewhat handled.
