### ISSUE TITLE
Comparison with hyperas

### ISSUE THREAD

**Issue by iofjuupasli** [autonomio/talos#93]
https://github.com/maxpumperla/hyperas
It seems that heperas is the main competitor for hyperparameter optimization for keras.
Can you please provide in docs some comparison with it, so to better understand what is better suit the specific task.

**Comment by mikkokotila** [comment]
Thanks, that is a good idea. What do you think are the most important features that hyperas does have, and which ones are important for hyperparameter optimization (with Keras) hyperas does not have?

**Comment by mikkokotila** [comment]
@iofjuupasli any suggestions / inputs?

**Comment by iofjuupasli** [comment]
@mikkokotila no, I'm not an expert in both tools
