### ISSUE TITLE
Sparse matrix support

### ISSUE THREAD

**Issue by optidatascience** [autonomio/talos#94]
The current code has a bug when x is a sparse matrix. 

Wonder if you can change `len(self.x)` to `self.x.shape[0]` at 3 places: 1 occurrence in scan.py and 2 occurrences in utils/validation_split.py. 

Thank you.

**Comment by mikkokotila** [comment]
Thanks. I will test that nothing breaks from the change and then make it. Will update there once it's pushed to daily-dev.

**Comment by mikkokotila** [comment]
I believe this was handled and has made its way to 0.4.4. Closing here. 

Thanks again.

**Comment by manosprom** [comment]
Hello old issue (but is it really fixed?)
i am using talos==0.4.9 and still getting the error

`TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]`

scan_prepare.py still using `len()`

I wonder if this should probably be reopened.
